// Peggle: Dual Shot
// #ID = 17633

LevelsIds = {
1:{"levelID":0x30310000, "name":"Peggleland"},
2:{"levelID":0x30320000, "name":"Slip and Slide"},
3:{"levelID":0x30330000, "name":"Bjorn's Gazebo"},
4:{"levelID":0x30340000, "name":"Das Bucket"},
5:{"levelID":0x30350000, "name":"Snow Day"},
6:{"levelID":0x30360000, "name":"Birdy's Crib"},
7:{"levelID":0x30370000, "name":"Buffalo Wings"},
8:{"levelID":0x30380000, "name":"Skate Park"},
9:{"levelID":0x30390000, "name":"Spiral of Doom"},
10:{"levelID":0x31300000, "name":"Mr. Peepers"},
11:{"levelID":0x31310000, "name":"Scarab Crunch"},
12:{"levelID":0x31320000, "name":"Infinite Cheese"},
13:{"levelID":0x31330000, "name":"Ra Deal"},
14:{"levelID":0x31340000, "name":"Croco-Gator Pit"},
15:{"levelID":0x31350000, "name":"The Fever Level"},
16:{"levelID":0x31360000, "name":"The Amoeban"},
17:{"levelID":0x31370000, "name":"The Last Flower"},
18:{"levelID":0x31380000, "name":"We Come in Peace"},
19:{"levelID":0x31390000, "name":"Maid in Space"},
20:{"levelID":0x32300000, "name":"Getting the Spare"},
21:{"levelID":0x32310000, "name":"Pearl Clam"},
22:{"levelID":0x32320000, "name":"Insane Aquarium"},
23:{"levelID":0x32330000, "name":"Tasty Waves"},
24:{"levelID":0x32340000, "name":"Our Favorite Eel"},
25:{"levelID":0x32350000, "name":"Love Story"},
26:{"levelID":0x32360000, "name":"Waves"},
27:{"levelID":0x32370000, "name":"Spiderweb"},
28:{"levelID":0x32380000, "name":"Blockers"},
29:{"levelID":0x32390000, "name":"Baseball"},
30:{"levelID":0x33300000, "name":"Vermin"},
31:{"levelID":0x33310000, "name":"Holland Oats"},
32:{"levelID":0x33320000, "name":"I Heart Flowers"},
33:{"levelID":0x33330000, "name":"Workin From Home"},
34:{"levelID":0x33340000, "name":"Tula's Ride"},
35:{"levelID":0x33350000, "name":"70 and Sunny"},
36:{"levelID":0x33360000, "name":"Win a Monkey"},
37:{"levelID":0x33370000, "name":"Dog Pinball"},
38:{"levelID":0x33380000, "name":"Spin Again"},
39:{"levelID":0x33390000, "name":"Roll 'Em"},
40:{"levelID":0x34300000, "name":"Five of a Kind"},
41:{"levelID":0x34310000, "name":"The Love Moat"},
42:{"levelID":0x34320000, "name":"Doom With a View"},
43:{"levelID":0x34330000, "name":"Rhombi"},
44:{"levelID":0x34340000, "name":"9 Luft Balloons"},
45:{"levelID":0x34350000, "name":"Twisted Sisters"},
46:{"levelID":0x34360000, "name":"Spin Cycle"},
47:{"levelID":0x34370000, "name":"The Dude Abides"},
48:{"levelID":0x34380000, "name":"When Pigs Fly"},
49:{"levelID":0x34390000, "name":"Yang, Yin"},
50:{"levelID":0x35300000, "name":"Zen Frog"},
51:{"levelID":0x35310000, "name":"Paw Reader"},
52:{"levelID":0x35320000, "name":"End of Time"},
53:{"levelID":0x35330000, "name":"Billions & Billions"},
54:{"levelID":0x35340000, "name":"Don't Panic"},
55:{"levelID":0x35350000, "name":"Beyond Reason"},
56:{"levelID":0x30315F6E, "name":"Crimewave"},
57:{"levelID":0x30325F6E, "name":"Call for Help"},
58:{"levelID":0x30335F6E, "name":"Horsepower"},
59:{"levelID":0x30345F6E, "name":"Just Desserts"},
60:{"levelID":0x30355F6E, "name":"Bjorn Identity"},
61:{"levelID":0x30365F6E, "name":"Experiment X"},
62:{"levelID":0x30375F6E, "name":"Brrrzap!"},
63:{"levelID":0x30385F6E, "name":"Antitoxic"},
64:{"levelID":0x30395F6E, "name":"Breakthrough"},
65:{"levelID":0x31305F6E, "name":"Smartiness"},
66:{"levelID":0x31315F6E, "name":"Scary Night"},
67:{"levelID":0x31325F6E, "name":"Seasick"},
68:{"levelID":0x31335F6E, "name":"NOOOOO!!!"},
69:{"levelID":0x31345F6E, "name":"Twitching Hour"},
70:{"levelID":0x31355F6E, "name":"Nowhere Stairs"},
71:{"levelID":0x31365F6E, "name":"Step Right Up"},
72:{"levelID":0x31375F6E, "name":"Parade!"},
73:{"levelID":0x31385F6E, "name":"Me-YOWWWW!"},
74:{"levelID":0x31395F6E, "name":"Jump the Squid"},
75:{"levelID":0x32305F6E, "name":"Death Defying"},
76:{"levelID":0x32315F6E, "name":"Bowl of Drome"},
77:{"levelID":0x32325F6E, "name":"Arrivance"},
78:{"levelID":0x32335F6E, "name":"Last Ball"},
79:{"levelID":0x32345F6E, "name":"Explodious"},
80:{"levelID":0x32355F6E, "name":"Perfectified"},
81:{"levelID":0x32365F6E, "name":"Pollution Picnic"},
82:{"levelID":0x32375F6E, "name":"Vast Visitor"},
83:{"levelID":0x32385F6E, "name":"Eiffel Power"},
84:{"levelID":0x32395F6E, "name":"Old Friends"},
85:{"levelID":0x33305F6E, "name":"Au Revoir"},
86:{"levelID":0x33315F6E, "name":"Founding Fathers"},
87:{"levelID":0x33325F6E, "name":"The Henge"},
88:{"levelID":0x33335F6E, "name":"Many Minarets"},
89:{"levelID":0x33345F6E, "name":"It's a Dry Heat"},
90:{"levelID":0x33355F6E, "name":"Wallflower"},
91:{"levelID":0x33365F6E, "name":"Inferno"},
92:{"levelID":0x33375F6E, "name":"Water Wings"},
93:{"levelID":0x33385F6E, "name":"Steppin' Out"},
94:{"levelID":0x33395F6E, "name":"Fire Eater"},
95:{"levelID":0x34305F6E, "name":"Letting Off Steam"},
96:{"levelID":0x34315F6E, "name":"X Marks the Loot"},
97:{"levelID":0x34325F6E, "name":"Beats Driving"},
98:{"levelID":0x34335F6E, "name":"Tomb of Doom"},
99:{"levelID":0x34345F6E, "name":"I Love Carats"},
100:{"levelID":0x34355F6E, "name":"Great Ball of Ire"},
101:{"levelID":0x34365F6E, "name":"Pick One"},
102:{"levelID":0x34375F6E, "name":"Turn it to Zen"},
103:{"levelID":0x34385F6E, "name":"Wild Thing"},
104:{"levelID":0x34395F6E, "name":"We Will Rock You"},
105:{"levelID":0x35305F6E, "name":"Feel the Noize"},
106:{"levelID":0x35315F6E, "name":"Psyclone"},
107:{"levelID":0x35325F6E, "name":"Why you Buggin'?"},
108:{"levelID":0x35335F6E, "name":"Wyrm Sign"},
109:{"levelID":0x35345F6E, "name":"The Rising"},
110:{"levelID":0x35355F6E, "name":"Shadowshine"},
111:{"levelID":0x30315F71, "name":"Q1: Flamingo Sqall"},
112:{"levelID":0x30325F71, "name":"Q2: Magician Girl"},
113:{"levelID":0x30335F71, "name":"Q3: Roar of the Ancient"},
114:{"levelID":0x30345F71, "name":"Q4: Egyptian Treasure"},
115:{"levelID":0x30355F71, "name":"Q5: Garden Dewdrop"},
116:{"levelID":0x30365F71, "name":"Q6: Home Sweet Bjorn"},
117:{"levelID":0x30375F71, "name":"Q7: Satori"},
118:{"levelID":0x30385F71, "name":"Q8: Alien Attack!"},
119:{"levelID":0x30395F71, "name":"Q9: Yhtapelet"},
120:{"levelID":0x31305F71, "name":"Q10: Bubbbbbbbbllle"},
}

Levels = {
0x30310000:"Peggleland",
0x30320000:"Slip and Slide",
0x30330000:"Bjorn's Gazebo",
0x30340000:"Das Bucket",
0x30350000:"Snow Day",
0x30360000:"Birdy's Crib",
0x30370000:"Buffalo Wings",
0x30380000:"Skate Park",
0x30390000:"Spiral of Doom",
0x31300000:"Mr. Peepers",
0x31310000:"Scarab Crunch",
0x31320000:"Infinite Cheese",
0x31330000:"Ra Deal",
0x31340000:"Croco-Gator Pit",
0x31350000:"The Fever Level",
0x31360000:"The Amoeban",
0x31370000:"The Last Flower",
0x31380000:"We Come in Peace",
0x31390000:"Maid in Space",
0x32300000:"Getting the Spare",
0x32310000:"Pearl Clam",
0x32320000:"Insane Aquarium",
0x32330000:"Tasty Waves",
0x32340000:"Our Favorite Eel",
0x32350000:"Love Story",
0x32360000:"Waves",
0x32370000:"Spiderweb",
0x32380000:"Blockers",
0x32390000:"Baseball",
0x33300000:"Vermin",
0x33310000:"Holland Oats",
0x33320000:"I Heart Flowers",
0x33330000:"Workin From Home",
0x33340000:"Tula's Ride",
0x33350000:"70 and Sunny",
0x33360000:"Win a Monkey",
0x33370000:"Dog Pinball",
0x33380000:"Spin Again",
0x33390000:"Roll 'Em",
0x34300000:"Five of a Kind",
0x34310000:"The Love Moat",
0x34320000:"Doom With a View",
0x34330000:"Rhombi",
0x34340000:"9 Luft Balloons",
0x34350000:"Twisted Sisters",
0x34360000:"Spin Cycle",
0x34370000:"The Dude Abides",
0x34380000:"When Pigs Fly",
0x34390000:"Yang, Yin",
0x35300000:"Zen Frog",
0x35310000:"Paw Reader",
0x35320000:"End of Time",
0x35330000:"Billions & Billions",
0x35340000:"Don't Panic",
0x35350000:"Beyond Reason",
0x30315F6E:"Crimewave",
0x30325F6E:"Call for Help",
0x30335F6E:"Horsepower",
0x30345F6E:"Just Desserts",
0x30355F6E:"Bjorn Identity",
0x30365F6E:"Experiment X",
0x30375F6E:"Brrrzap!",
0x30385F6E:"Antitoxic",
0x30395F6E:"Breakthrough",
0x31305F6E:"Smartiness",
0x31315F6E:"Scary Night",
0x31325F6E:"Seasick",
0x31335F6E:"NOOOOO!!!",
0x31345F6E:"Twitching Hour",
0x31355F6E:"Nowhere Stairs",
0x31365F6E:"Step Right Up",
0x31375F6E:"Parade!",
0x31385F6E:"Me-YOWWWW!",
0x31395F6E:"Jump the Squid",
0x32305F6E:"Death Defying",
0x32315F6E:"Bowl of Drome",
0x32325F6E:"Arrivance",
0x32335F6E:"Last Ball",
0x32345F6E:"Explodious",
0x32355F6E:"Perfectified",
0x32365F6E:"Pollution Picnic",
0x32375F6E:"Vast Visitor",
0x32385F6E:"Eiffel Power",
0x32395F6E:"Old Friends",
0x33305F6E:"Au Revoir",
0x33315F6E:"Founding Fathers",
0x33325F6E:"The Henge",
0x33335F6E:"Many Minarets",
0x33345F6E:"It's a Dry Heat",
0x33355F6E:"Wallflower",
0x33365F6E:"Inferno",
0x33375F6E:"Water Wings",
0x33385F6E:"Steppin' Out",
0x33395F6E:"Fire Eater",
0x34305F6E:"Letting Off Steam",
0x34315F6E:"X Marks the Loot",
0x34325F6E:"Beats Driving",
0x34335F6E:"Tomb of Doom",
0x34345F6E:"I Love Carats",
0x34355F6E:"Great Ball of Ire",
0x34365F6E:"Pick One",
0x34375F6E:"Turn it to Zen",
0x34385F6E:"Wild Thing",
0x34395F6E:"We Will Rock You",
0x35305F6E:"Feel the Noize",
0x35315F6E:"Psyclone",
0x35325F6E:"Why you Buggin'?",
0x35335F6E:"Wyrm Sign",
0x35345F6E:"The Rising",
0x35355F6E:"Shadowshine",
0x30315F71:"Q1: Flamingo Sqall",
0x30325F71:"Q2: Magician Girl",
0x30335F71:"Q3: Roar of the Ancient",
0x30345F71:"Q4: Egyptian Treasure",
0x30355F71:"Q5: Garden Dewdrop",
0x30365F71:"Q6: Home Sweet Bjorn",
0x30375F71:"Q7: Satori",
0x30385F71:"Q8: Alien Attack!",
0x30395F71:"Q9: Yhtapelet",
0x31305F71:"Q10: Bubbbbbbbbllle",
}

DayLevels = {
    1:{"value":1, "points":5, "title":"A Brief Introduction to Peggle", "description":"Complete Bjorn's day stages in Adventure Mode"},
2:{"value":2, "points":5, "title":"Multiball Madness", "description":"Complete Jimmy Lightning's day stages in Adventure Mode"},
3:{"value":3, "points":5, "title":"The Faces of the Pyramid", "description":"Complete Kat Kut's day stages in Adventure Mode"},
4:{"value":4, "points":5, "title":"The Splendor of the Space Blast", "description":"Complete Splork's day stages in Adventure Mode"},
5:{"value":5, "points":5, "title":"Flippers Keep It Going", "description":"Complete Claude's day stages in Adventure Mode"},
6:{"value":6, "points":5, "title":"The Mysteries of the Spooky Ball", "description":"Complete Renfield's day stages in Adventure Mode"},
7:{"value":7, "points":5, "title":"Grow With the Flower Power", "description":"Complete Tula's day stages in Adventure Mode"},
8:{"value":8, "points":5, "title":"Lucky Spin For the Win", "description":"Complete Warren's day stages in Adventure Mode"},
9:{"value":9, "points":5, "title":"The Awesome Force of the Fireball", "description":"Complete Lord Cinderbottom's day stages in Adventure Mode"},
10:{"value":10, "points":5, "title":"The Way of the Zen Ball", "description":"Complete Master Hu's day stages in Adventure Mode"},
}

NightLevels = {
    1:{"value":1, "points":5, "title":"Undercover Unicorn", "description":"Complete Bjorn's night stages in Adventure Mode"},
2:{"value":2, "points":5, "title":"Rad Scientist", "description":"Complete Jimmy Lightning's night stages in Adventure Mode"},
3:{"value":3, "points":5, "title":"Circus Daredevil", "description":"Complete Kat Kut's night stages in Adventure Mode"},
4:{"value":4, "points":5, "title":"Perfect Bowler", "description":"Complete Splork's night stages in Adventure Mode"},
5:{"value":5, "points":5, "title":"Raging Kaiju", "description":"Complete Claude's night stages in Adventure Mode"},
6:{"value":6, "points":5, "title":"Impressive Painter", "description":"Complete Renfield's night stages in Adventure Mode"},
7:{"value":7, "points":5, "title":"World Traveler", "description":"Complete Tula's night stages in Adventure Mode"},
8:{"value":8, "points":5, "title":"Treasure Hunter", "description":"Complete Warren's night stages in Adventure Mode"},
9:{"value":9, "points":5, "title":"Fearless Firefighter", "description":"Complete Lord Cinderbottom's night stages in Adventure Mode"},
10:{"value":10, "points":5, "title":"Rock Legend", "description":"Complete Master Hu's night stages in Adventure Mode"},
}
savePointer = tbyte(0x100a64)
currentLevel = dword_be(tbyte(0x100a64) + 0xc5)
gameMode = byte(0x0dfe28)
adventure = 0x01
quickPlay = 0x02
duel = 0x03
challenges = 0x04

gameState = dword(0x138410)
inGame = 0x01
levelEnd = 0x02

inGamePointer = tbyte(0x13b7d8)

completeLevelsStart = 0x100b38
completeLevelsEnd = 0x100b46
scoreIngame = dword(0x135e54)

challengesStart = 0x100b10
challengesEnd = 0x100b1a

currentDayWorld = byte(0x100ad1)
beatPeggle = bit0(0x100ac4)
currentNightWorld = byte(0x100af1)
beatPeggleNights = bit1(0x100ac4)

function ProgressionDay(value){
    logic = gameMode == adventure &&
    savePointer != 0 &&
    currentDayWorld == value && prev(currentDayWorld) == value - 1
    return logic
}

for level in DayLevels{
    achievement(
        title = DayLevels[level]["title"],
        description = DayLevels[level]["description"],
        points = DayLevels[level]["points"],
        trigger = ProgressionDay(DayLevels[level]["value"])
    )
}

achievement("The True Test of a Master", "Complete the final exam day stages in Adventure Mode", 10, 
gameMode == adventure &&
    savePointer != 0 &&
    beatPeggle > prev(beatPeggle)
)


function ProgressionNight(value){
    logic = gameMode == adventure &&
    savePointer != 0 &&
    currentNightWorld == value && prev(currentNightWorld) == value - 1
    return logic
}

for level in NightLevels{
    achievement(
        title = NightLevels[level]["title"],
        description = NightLevels[level]["description"],
        points = NightLevels[level]["points"],
        trigger = ProgressionNight(NightLevels[level]["value"])
    )
}

achievement("Reach for the Dawn", "Complete the final exam night stages in Adventure Mode", 10, 
gameMode == adventure &&
    savePointer != 0 &&
    beatPeggleNights > prev(beatPeggleNights)
)

HundredPercent = {
    1:{"value":1, "points":3, "title":"Stage Apprentice", "description":"Get 100% on 1 stage"},
2:{"value":5, "points":5, "title":"Stellar Start", "description":"Get 100% on 5 stages"},
3:{"value":10, "points":5, "title":"Perfect Progress", "description":"Get 100% on 10 stages"},
4:{"value":20, "points":5, "title":"Stage Streaker", "description":"Get 100% on 20 stages"},
5:{"value":30, "points":5, "title":"Flawless Fiver", "description":"Get 100% on 30 stages"},
6:{"value":40, "points":5, "title":"Perfect Ten", "description":"Get 100% on 40 stages"},
7:{"value":50, "points":5, "title":"Master of Many", "description":"Get 100% on 50 stages"},
8:{"value":75, "points":10, "title":"Staging Success", "description":"Get 100% on 75 stages"},
9:{"value":100, "points":10, "title":"Stage Centurion", "description":"Get 100% on 100 stages"},
10:{"value":110, "points":10, "title":"Stage Conqueror", "description":"Get 100% on 110 stages"},
11:{"value":119, "points":50, "title":"Peggle Perfectionist", "description":"Get 100% on 119 stages"},
}

function LevelsComplete(){
    sum = 0
    
    for address in range(completeLevelsStart, completeLevelsEnd){
        sum = sum + bitcount(address)
    }
    return sum
}



function ChallengesSum(){
    sum = 0
    for address in range(challengesStart, challengesEnd){
        sum = sum + bitcount(address)
    }
    sum = sum + bit0(0x100b1b) + bit1(0x100b1b)
    return sum
}

function HundredLogic(value){
    logic = 
    gameMode >= 1 && gameMode <= 4 &&
    savePointer != 0  &&
    measured(LevelsComplete() == value) && prev(LevelsComplete()) == value - 1
    return logic
}

for cheevo in HundredPercent{
    achievement(
        HundredPercent[cheevo]["title"],
        HundredPercent[cheevo]["description"],
        HundredPercent[cheevo]["points"],
        HundredLogic(HundredPercent[cheevo]["value"])
    )
}

Challenges = {
    1:{"value":10, "points":5, "title":"Initiate's Feat", "description":"Complete 10 challenges"},
2:{"value":20, "points":5, "title":"Peggle Pathfinders", "description":"Complete 20 challenges"},
3:{"value":30, "points":5, "title":"Trials Tackled", "description":"Complete 30 challenges"},
4:{"value":40, "points":5, "title":"Mastery Milestone", "description":"Complete 40 challenges"},
5:{"value":50, "points":5, "title":"Peggle Prowess", "description":"Complete 50 challenges"},
6:{"value":60, "points":10, "title":"Trials Triumph", "description":"Complete 60 challenges"},
7:{"value":70, "points":10, "title":"Skillful Showdown", "description":"Complete 70 challenges"},
8:{"value":80, "points":10, "title":"Challenge Champion", "description":"Complete 80 challenges"},
9:{"value":90, "points":50, "title":"Peggle Grandmaster", "description":"Complete all 90 challenges"},
}


function ChallengeLogic(value){
    logic = 
    gameMode >= 1 && gameMode <= 4 &&
    savePointer != 0  &&
    measured(ChallengesSum() == value) && prev(ChallengesSum()) == value - 1
    return logic
}

for cheevo in Challenges{
    achievement(
        Challenges[cheevo]["title"],
        Challenges[cheevo]["description"],
        Challenges[cheevo]["points"],
        ChallengeLogic(Challenges[cheevo]["value"])
    )
}


Bitflags = {
    1:{"value":bit6(0x100b35), "points":2, "title":"Supreme Completion", "description":"Collect 100 gems"},
2:{"value":bit7(0x100b35), "points":3, "title":"Magician Girl", "description":"Collect 300 gems"},
3:{"value":bit0(0x100b36), "points":4, "title":"Roar of the Ancient", "description":"Collect 500 gems"},
4:{"value":bit3(0x100b36), "points":5, "title":"Home Sweet Bjorn", "description":"Collect 1000 gems"},
5:{"value":bit4(0x100b36), "points":5, "title":"Satori", "description":"Score 1,000,000 cumulative style shots points"},
6:{"value":bit5(0x100b36), "points":5, "title":"Alien Attack!", "description":"Shoot the ball 1000 times"},
7:{"value":bit6(0x100b36), "points":5, "title":"Yhtapelet", "description":"Score 500,000 points in a single level"},
}

function BitflagLogic(value){
    logic = 
    gameMode >= 1 && gameMode <= 4 &&
    savePointer != 0  &&
    value > prev(value)
    return logic
}

for cheevo in Bitflags{
    achievement(
        Bitflags[cheevo]["title"],
        Bitflags[cheevo]["description"],
        Bitflags[cheevo]["points"],
        BitflagLogic(Bitflags[cheevo]["value"])
    )
}









//Level Leaderboards
for level in LevelsIds{
    leaderboard(
    title = LevelsIds[level]["name"], 
    description = "Top Score", 
    start =
    savePointer != 0 &&
    savePointer == prev(savePointer) &&
    (gameMode == adventure || gameMode == quickPlay) &&
    gameState == levelEnd && prev(gameState) == inGame &&
    currentLevel == prev(currentLevel) &&
    currentLevel == LevelsIds[level]["levelID"]
    , 
    cancel = always_false(), 
    submit = always_true(), 
    value = measured(scoreIngame), 
    format="VALUE", 
    lower_is_better=false)
}

Mode = {
    0x01:"Adventure Mode",
    0x02:"Quick Play Mode",
    0x03:"Duel Mode",
    0x04:"Challenge Mode"
}


rich_presence_conditional_display(gameState != 1, "Not in a level | 100% Levels: {0}/120 | Challenges: {1}/90",
    rich_presence_value("completeLevels", measured(LevelsComplete())),
    rich_presence_value("challenges", measured(ChallengesSum()))
)
rich_presence_display("{0} | {1} | Score: {2} | 100% Levels: {3}/120 | Challenges: {4}/90",
    rich_presence_lookup("mode", gameMode, Mode),
    rich_presence_lookup("level", currentLevel, Levels),
    rich_presence_value("score", measured(scoreIngame)),
    rich_presence_value("completeLevels", measured(LevelsComplete())),
    rich_presence_value("challenges", measured(ChallengesSum()))
)