// Super Monkey Ball Deluxe
// #ID = 20491


//Stage IDs Beginner
BeginnerIDs = {
    1: {"id": 0x0321},
    2: {"id": 0x0322},
    3: {"id": 0x0323},
    4: {"id": 0x0324},
    5: {"id": 0x00c9},
    6: {"id": 0x00ca},
    7: {"id": 0x00cb},
    8: {"id": 0x00cc},
    9: {"id": 0x0002},
    10: {"id": 0x037b},
    11: {"id": 0x03a4},
    12: {"id": 0x03aa},
    13: {"id": 0x03c6},
    14: {"id": 0x03b2},
    15: {"id": 0x03c4},
    16: {"id": 0x03b9},
    17: {"id": 0x03c5},
    18: {"id": 0x03b4},
    19: {"id": 0x03c3},
    20: {"id": 0x00cd},
    21: {"id": 0x0325},
    22: {"id": 0x0326},
    23: {"id": 0x0327},
    24: {"id": 0x0328},
    25: {"id": 0x0329},
    26: {"id": 0x00cf},
    27: {"id": 0x00d0},
    28: {"id": 0x00d1},
    29: {"id": 0x00d2},
    30: {"id": 0x03c0},
    31: {"id": 0x03cf},
    32: {"id": 0x03a3},
    33: {"id": 0x03bd},
    34: {"id": 0x03a7},
    35: {"id": 0x03b8},
    36: {"id": 0x03b1},
    37: {"id": 0x03a9},
    38: {"id": 0x03ad},
    39: {"id": 0x03ce},
    40: {"id": 0x03ca},   
}
//Stage Ids Beginner Extra
BeginnerExtraIDs = {
    1: {"id": 0x0385},
    2: {"id": 0x0386},
    3: {"id": 0x0387},
    4: {"id": 0x03c2},
    5: {"id": 0x03a5},
    6: {"id": 0x00d3},
    7: {"id": 0x00d4},
    8: {"id": 0x00d5},
    9: {"id": 0x00d6},
    10: {"id": 0x00d7},
    11: {"id": 0x03bf},
    12: {"id": 0x03d0},
    13: {"id": 0x03ba},
    14: {"id": 0x03b3},
    15: {"id": 0x03bb},
    16: {"id": 0x00d8},
    17: {"id": 0x00d9},
    18: {"id": 0x00da},
    19: {"id": 0x00db},
    20: {"id": 0x00dc},  
}
//Stage Ids Advanced
AdvancedIDs = {
    1: {"id": 0x032b},
    2: {"id": 0x032c},
    3: {"id": 0x032d},
    4: {"id": 0x032e},
    5: {"id": 0x032f},
    6: {"id": 0x0330},
    7: {"id": 0x0331},
    8: {"id": 0x0332},
    9: {"id": 0x02f4},
    10: {"id": 0x037c},
    11: {"id": 0x03c7},
    12: {"id": 0x03cc},
    13: {"id": 0x03c8},
    14: {"id": 0x03b5},
    15: {"id": 0x03bc},
    16: {"id": 0x03b0},
    17: {"id": 0x03c1},
    18: {"id": 0x03b6},
    19: {"id": 0x03cd},
    20: {"id": 0x037d},
    21: {"id": 0x0007},
    22: {"id": 0x0008},
    23: {"id": 0x0009},
    24: {"id": 0x000a},
    25: {"id": 0x000c},
    26: {"id": 0x00e3},
    27: {"id": 0x00e4},
    28: {"id": 0x00e5},
    29: {"id": 0x02c7},
    30: {"id": 0x00e1},
    31: {"id": 0x0336},
    32: {"id": 0x0337},
    33: {"id": 0x0338},
    34: {"id": 0x0339},
    35: {"id": 0x033a},
    36: {"id": 0x02f5},
    37: {"id": 0x02f6},
    38: {"id": 0x02f7},
    39: {"id": 0x02f8},
    40: {"id": 0x00e6}, 
    41: {"id": 0x00e8},
    42: {"id": 0x00e9},
    43: {"id": 0x00ea},
    44: {"id": 0x00eb},
    45: {"id": 0x00ec},
    46: {"id": 0x02c8},
    47: {"id": 0x02c9},
    48: {"id": 0x02ca},
    49: {"id": 0x02cb},
    50: {"id": 0x00f0},
    51: {"id": 0x0340},
    52: {"id": 0x0341},
    53: {"id": 0x0342},
    54: {"id": 0x0343},
    55: {"id": 0x0344},
    56: {"id": 0x0219},
    57: {"id": 0x021a},
    58: {"id": 0x021b},
    59: {"id": 0x021c},
    60: {"id": 0x03af},
    61: {"id": 0x0013},
    62: {"id": 0x0014},
    63: {"id": 0x0015},
    64: {"id": 0x0016},
    65: {"id": 0x0017},
    66: {"id": 0x02bd},
    67: {"id": 0x02be},
    68: {"id": 0x02bf},
    69: {"id": 0x02c0},
    70: {"id": 0x03ac},   
}
//Stage Ids Advanced Extra
AdvancedExtraIDs = {
    1: {"id": 0x0385},
    2: {"id": 0x0388},
    3: {"id": 0x0389},
    4: {"id": 0x0387},
    5: {"id": 0x038a},
    6: {"id": 0x00fb},
    7: {"id": 0x00fc},
    8: {"id": 0x00fd},
    9: {"id": 0x00fe},
    10: {"id": 0x00ff},
    
    11: {"id": 0x03a6},
    12: {"id": 0x03b7},
    13: {"id": 0x03be},
    14: {"id": 0x03ab},
    15: {"id": 0x03cb},
    16: {"id": 0x0100},
    17: {"id": 0x0101},
    18: {"id": 0x0102},
    19: {"id": 0x0103},
    20: {"id": 0x0104},  
}
//Stage Ids Expert
ExpertIDs = {
    1: {"id": 0x0349},
    2: {"id": 0x034a},
    3: {"id": 0x034b},
    4: {"id": 0x034c},
    5: {"id": 0x034d},
    6: {"id": 0x034e},
    7: {"id": 0x034f},
    8: {"id": 0x0350},
    9: {"id": 0x02fa},
    10: {"id": 0x037e},
    
    11: {"id": 0x001c},
    12: {"id": 0x001d},
    13: {"id": 0x001e},
    14: {"id": 0x001f},
    15: {"id": 0x0021},
    16: {"id": 0x02c1},
    17: {"id": 0x02c2},
    18: {"id": 0x02c3},
    19: {"id": 0x02cc},
    20: {"id": 0x037f},
    
    21: {"id": 0x0354},
    22: {"id": 0x0355},
    23: {"id": 0x0356},
    24: {"id": 0x0357},
    25: {"id": 0x0358},
    26: {"id": 0x02fb},
    27: {"id": 0x02fc},
    28: {"id": 0x02fd},
    29: {"id": 0x02fe},
    30: {"id": 0x0109},
    
    31: {"id": 0x0027},
    32: {"id": 0x0028},
    33: {"id": 0x0029},
    34: {"id": 0x002a},
    35: {"id": 0x002b},
    36: {"id": 0x02c4},
    37: {"id": 0x02c5},
    38: {"id": 0x02c6},
    39: {"id": 0x02cd},
    40: {"id": 0x010e}, 
    
    41: {"id": 0x035e},
    42: {"id": 0x035f},
    43: {"id": 0x0360},
    44: {"id": 0x0361},
    45: {"id": 0x0362},
    46: {"id": 0x0363},
    47: {"id": 0x0364},
    48: {"id": 0x0365},
    49: {"id": 0x02ff},
    50: {"id": 0x0118},
    
    51: {"id": 0x011a},
    52: {"id": 0x011b},
    53: {"id": 0x011c},
    54: {"id": 0x011d},
    55: {"id": 0x011e},
    56: {"id": 0x011f},
    57: {"id": 0x0120},
    58: {"id": 0x0121},
    59: {"id": 0x02ce},
    60: {"id": 0x0122},
    
    61: {"id": 0x0368},
    62: {"id": 0x0369},
    63: {"id": 0x036a},
    64: {"id": 0x036b},
    65: {"id": 0x036c},
    66: {"id": 0x036d},
    67: {"id": 0x036e},
    68: {"id": 0x036f},
    69: {"id": 0x0300},
    70: {"id": 0x012c},
    
    71: {"id": 0x0032},
    72: {"id": 0x0033},
    73: {"id": 0x0034},
    74: {"id": 0x0035},
    75: {"id": 0x0036},
    76: {"id": 0x0037},
    77: {"id": 0x0038},
    78: {"id": 0x0039},
    79: {"id": 0x02cf},
    80: {"id": 0x03ae},
    
    81: {"id": 0x0372},
    82: {"id": 0x0373},
    83: {"id": 0x0374},
    84: {"id": 0x0375},
    85: {"id": 0x0376},
    86: {"id": 0x0377},
    87: {"id": 0x0378},
    88: {"id": 0x0379},
    89: {"id": 0x037a},
    90: {"id": 0x03c9},
    
    91: {"id": 0x003c},
    92: {"id": 0x003d},
    93: {"id": 0x003e},
    94: {"id": 0x003f},
    95: {"id": 0x0040},
    96: {"id": 0x0041},
    97: {"id": 0x0042},
    98: {"id": 0x0043},
    99: {"id": 0x0044},
    100: {"id": 0x03a8}, 
}
//Stage Ids Expert Extra
ExpertExtraIDs = {
    1: {"id": 0x0137},
    2: {"id": 0x0138},
    3: {"id": 0x0139},
    4: {"id": 0x013a},
    5: {"id": 0x013b},
    6: {"id": 0x013c},
    7: {"id": 0x013d},
    8: {"id": 0x013e},
    9: {"id": 0x013f},
    10: {"id": 0x0140},
    
    11: {"id": 0x0385},
    12: {"id": 0x038b},
    13: {"id": 0x0388},
    14: {"id": 0x038c},
    15: {"id": 0x038d},
    16: {"id": 0x038e},
    17: {"id": 0x038f},
    18: {"id": 0x0387},
    19: {"id": 0x0390},
    20: {"id": 0x0391},  
}
//Stage Ids Master
MasterIDs = {
    1: {"id": 0x02d5},
    2: {"id": 0x02d6},
    3: {"id": 0x02d7},
    4: {"id": 0x02d8},
    5: {"id": 0x02d9},
    6: {"id": 0x0146},
    7: {"id": 0x0147},
    8: {"id": 0x0148},
    9: {"id": 0x0149},
    10: {"id": 0x014a},
    
    11: {"id": 0x0399},
    12: {"id": 0x039a},
    13: {"id": 0x039b},
    14: {"id": 0x039c},
    15: {"id": 0x039d},
    16: {"id": 0x039e},
    17: {"id": 0x039f},
    18: {"id": 0x03a0},
    19: {"id": 0x03a1},
    20: {"id": 0x03a2},  
}
//Stage Ids Master Extra
MasterExtraIDs = {
    1: {"id": 0x014b},
    2: {"id": 0x014c},
    3: {"id": 0x014d},
    4: {"id": 0x014e},
    5: {"id": 0x014f},
    6: {"id": 0x0150},
    7: {"id": 0x0151},
    8: {"id": 0x0152},
    9: {"id": 0x0153},
    10: {"id": 0x03d2},
}  
//Stage Ids World 1
World1IDs = {
    1: {"id": 0x00c9},
    2: {"id": 0x01f6},
    3: {"id": 0x01cd},
    4: {"id": 0x01ce},
    5: {"id": 0x00cb},
    6: {"id": 0x01f7},
    7: {"id": 0x01f8},
    8: {"id": 0x0001},
    9: {"id": 0x01cf},
    10: {"id": 0x0002},
    
    11: {"id": 0x0003},
    12: {"id": 0x01d0},
    13: {"id": 0x0004},
    14: {"id": 0x01f9},
    15: {"id": 0x0005},
    16: {"id": 0x01fa},
    17: {"id": 0x01d1},
    18: {"id": 0x0006},
    19: {"id": 0x00ca},
    20: {"id": 0x00cc},  
}
//Stage Ids World 2
World2IDs = {
    1: {"id": 0x0007},
    2: {"id": 0x01fb},
    3: {"id": 0x01d2},
    4: {"id": 0x01d3},
    5: {"id": 0x0009},
    6: {"id": 0x01fc},
    7: {"id": 0x01fd},
    8: {"id": 0x000b},
    9: {"id": 0x01d4},
    10: {"id": 0x000c},
    
    11: {"id": 0x000d},
    12: {"id": 0x01d5},
    13: {"id": 0x000e},
    14: {"id": 0x01ff},
    15: {"id": 0x000f},
    16: {"id": 0x0200},
    17: {"id": 0x01d6},
    18: {"id": 0x0010},
    19: {"id": 0x0008},
    20: {"id": 0x000a},  
}
//Stage Ids World 3
World3IDs = {
    1: {"id": 0x00e7},
    2: {"id": 0x0201},
    3: {"id": 0x01d7},
    4: {"id": 0x01d8},
    5: {"id": 0x00e9},
    6: {"id": 0x0202},
    7: {"id": 0x0202},
    8: {"id": 0x00eb},
    9: {"id": 0x01d9},
    10: {"id": 0x00ec},
    
    11: {"id": 0x00ed},
    12: {"id": 0x01da},
    13: {"id": 0x00ee},
    14: {"id": 0x0204},
    15: {"id": 0x00ef},
    16: {"id": 0x0205},
    17: {"id": 0x01db},
    18: {"id": 0x0011},
    19: {"id": 0x00e8},
    20: {"id": 0x00ea},  
}
//Stage Ids World 4
World4IDs = {
    1: {"id": 0x0012},
    2: {"id": 0x0206},
    3: {"id": 0x01dc},
    4: {"id": 0x01dd},
    5: {"id": 0x0014},
    6: {"id": 0x0209},
    7: {"id": 0x020a},
    8: {"id": 0x0016},
    9: {"id": 0x01de},
    10: {"id": 0x0017},
    
    11: {"id": 0x0018},
    12: {"id": 0x01df},
    13: {"id": 0x0019},
    14: {"id": 0x020b},
    15: {"id": 0x001a},
    16: {"id": 0x020c},
    17: {"id": 0x01e0},
    18: {"id": 0x001b},
    19: {"id": 0x0013},
    20: {"id": 0x0015},  
}
//Stage Ids World 5
World5IDs = {
    1: {"id": 0x001c},
    2: {"id": 0x020d},
    3: {"id": 0x001d},
    4: {"id": 0x001e},
    5: {"id": 0x020f},
    6: {"id": 0x001f},
    7: {"id": 0x0020},
    8: {"id": 0x0211},
    9: {"id": 0x0021},
    10: {"id": 0x0213},
    
    11: {"id": 0x0022},
    12: {"id": 0x0214},
    13: {"id": 0x0023},
    14: {"id": 0x0215},
    15: {"id": 0x0024},
    16: {"id": 0x0216},
    17: {"id": 0x0025},
    18: {"id": 0x0217},
    19: {"id": 0x020e},
    20: {"id": 0x0210},  
}
//Stage Ids World 6
World6IDs = {
    1: {"id": 0x0026},
    2: {"id": 0x0218},
    3: {"id": 0x0027},
    4: {"id": 0x0028},
    5: {"id": 0x021a},
    6: {"id": 0x0029},
    7: {"id": 0x002a},
    8: {"id": 0x021c},
    9: {"id": 0x002b},
    10: {"id": 0x021d},
    
    11: {"id": 0x002c},
    12: {"id": 0x021e},
    13: {"id": 0x002d},
    14: {"id": 0x021f},
    15: {"id": 0x002e},
    16: {"id": 0x0220},
    17: {"id": 0x002f},
    18: {"id": 0x0221},
    19: {"id": 0x0219},
    20: {"id": 0x021b},  
}
//Stage Ids World 7
World7IDs = {
    1: {"id": 0x0119},
    2: {"id": 0x0222},
    3: {"id": 0x011a},
    4: {"id": 0x011b},
    5: {"id": 0x0224},
    6: {"id": 0x011c},
    7: {"id": 0x011d},
    8: {"id": 0x0228},
    9: {"id": 0x011e},
    10: {"id": 0x0229},
    
    11: {"id": 0x011f},
    12: {"id": 0x022a},
    13: {"id": 0x0120},
    14: {"id": 0x022b},
    15: {"id": 0x0121},
    16: {"id": 0x022c},
    17: {"id": 0x0030},
    18: {"id": 0x022d},
    19: {"id": 0x0223},
    20: {"id": 0x0227},  
}
//Stage Ids World 8
World8IDs = {
    1: {"id": 0x0031},
    2: {"id": 0x022e},
    3: {"id": 0x0032},
    4: {"id": 0x0033},
    5: {"id": 0x0231},
    6: {"id": 0x0034},
    7: {"id": 0x0035},
    8: {"id": 0x0233},
    9: {"id": 0x0036},
    10: {"id": 0x0234},
    
    11: {"id": 0x0037},
    12: {"id": 0x0235},
    13: {"id": 0x0038},
    14: {"id": 0x0236},
    15: {"id": 0x0039},
    16: {"id": 0x0237},
    17: {"id": 0x003a},
    18: {"id": 0x0238},
    19: {"id": 0x022f},
    20: {"id": 0x0232},  
}
//Stage Ids World 9
World9IDs = {
    1: {"id": 0x003b},
    2: {"id": 0x0239},
    3: {"id": 0x003c},
    4: {"id": 0x003d},
    5: {"id": 0x023c},
    6: {"id": 0x003e},
    7: {"id": 0x003f},
    8: {"id": 0x023e},
    9: {"id": 0x0040},
    10: {"id": 0x023f},
    
    11: {"id": 0x0041},
    12: {"id": 0x0240},
    13: {"id": 0x0042},
    14: {"id": 0x0241},
    15: {"id": 0x0043},
    16: {"id": 0x0242},
    17: {"id": 0x0044},
    18: {"id": 0x0243},
    19: {"id": 0x023b},
    20: {"id": 0x023d},  
}
//Stage Ids World 10
World10IDs = {
    1: {"id": 0x0155},
    2: {"id": 0x0245},
    3: {"id": 0x0156},
    4: {"id": 0x0157},
    5: {"id": 0x0247},
    6: {"id": 0x0158},
    7: {"id": 0x0159},
    8: {"id": 0x0249},
    9: {"id": 0x015a},
    10: {"id": 0x024a}, 
    11: {"id": 0x015b},
    12: {"id": 0x024b},
    13: {"id": 0x015c},
    14: {"id": 0x024c},
    15: {"id": 0x015d},
    16: {"id": 0x024d},
    17: {"id": 0x015e},
    18: {"id": 0x024e},
    19: {"id": 0x0246},
    20: {"id": 0x0248},  
}
Worlds = {
    1: {"name": "Wilds Isle", "points": 3},
    2: {"name": "Cataclysmal Boiling", "points": 4},
    3: {"name": "Under the Sea", "points": 4},
    4: {"name": "Cetacean's Interior", "points": 5},
    5: {"name": "Banana Land", "points": 5},
    6: {"name": "Steaming Vessel", "points": 5},
    7: {"name": "Cleanse Gadget", "points": 5},
    8: {"name": "Timekeeper's Workshop", "points": 5},
    9: {"name": "Monkey to the Moon", "points": 5},
    10: {"name": "Top Banana", "points": 10},
}


//Normal game Stuff
LevelID = word(0x4ba1fc)
Timer = word(0x52f5b4)
NormalGameState = 0x52f5b0
CompletedStage = bit5(NormalGameState)
TimeStopped = bit3(NormalGameState)
Replay = bit4(NormalGameState)
InGame = bit0(0x4c2f50) == 0
NotInGame = bit0(0x4c2f50) == 1
//Menu stuff
//0x541190 [8-bit] Mode Select
MainMode = byte(0x541190)
MainGame = 0x00 
PartyGame = 0x01 
Options = 0x02
//0x541198 [8-bit] Main Game Select
MainGameSelect = byte(0x541198)
StoryMode = 0x00 
ChallengeMode = 0x01
CompetitionMode = 0x02
PracticeMode = 0x03 
//0x541194 [8-bit] Number of Players
NumberOfPlayers = byte(0x541194)
//0x54119b [8-bit] Challenge Mode - Mode Select
ChallengeModeSelect1 = byte(0x00541199)
ChallengeModeSelect2 = byte(0x0054119a)
ChallengeModeSelect3 = byte(0x0054119b)
ChallengeModeSelect4 = byte(0x0054119c)
Beginner = 0x00
Advanced = 0x01
Expert = 0x02
Master = 0x03
Ultimate = 0x04
//Party game select
PartyGameSelect = byte(0x00541191)
MonkeyRaceDX = 0x00
MonkeyFightDX = 0x01
//0x4c2f00 [N-bit] Pause Flag
//Bit 3 = 1 if Paused, 0 if not
Paused = bit3(0x4c2f00) == 1
//0x52f834 [32-bit] Ultimate Level Results - Number of stages cleared
UltimateStagesCleared = dword(0x52f834)
//0x52f838 [32-bit] Ultimate Level Results - Time [Frames]
UltimateTime = dword(0x52f838)
//0x52f83c [32-bit] Ultimate Level Results - Points
UltimatePoints = dword(0x52f83c)
//0x52f840 [32-bit] Ultimate Level Results - Maximum number of consecutive completions
UltimateCompletions = dword(0x52f840)
//0x52f848 [32-bit] Ultimate Level Results - Number of continues used
UltimateContinues = dword(0x52f848)
//0x52f84c [32-bit] Ultimate Level Results - Number of lost monkeys
UltimateMonkeys = dword(0x52f84c)
//0x52f850 [32-bit] Ultimate Level Results - Number of bananas collected
UltimateBananas = dword(0x52f850)

//Story Mode 0x515c04 Current World
CurrentWorld = byte(0x515c04)
//0x57b8c4 [8-bit] Story Mode - Quantity of levels beaten
StoryBeaten = byte(0x57b8c4)
//0x57b8b8 [32-bit] Story Mode - 1st Save - Time (Frames)
StoryMode1stSave = dword(0x57b8b8)
//0x541200 [8-bit] Menu Progress
//0xff = Title Screen
MenuProgress = byte(0x541200)
TitleScreen = 0xff
TitleScreen2 = 0x00

function MenuProgressCheck(){
    return 
    MenuProgress != TitleScreen &&
    MenuProgress != TitleScreen2
}

//World Cheevos
function WorldProgression(world, name, description, points){
    if (world != 10){
    achievement(
        name, description, points,
        trigger = 
        MenuProgressCheck() &&
        MainMode == MainGame &&
        MainGameSelect == StoryMode &&
        prev(CurrentWorld) == world-1 &&
        CurrentWorld == world
    )
    }else{
        achievement(
        name, description, points,
        trigger = 
        MenuProgressCheck() &&
        MainMode == MainGame &&
        MainGameSelect == StoryMode &&
        prev(LevelID) != 0x00c5 &&
        LevelID == 0x00c5
    )
    }   
}

for world in Worlds{
   WorldProgression(world, Worlds[world]["name"], "[Story Mode] Clear World " + world, Worlds[world]["points"])
}

NULL = 0xffff
WarpGoal = word(0x0052f5ea)
Blue = 0x00
Green = 0x01
Red = 0x02
Yes = 0x01

Play = 0x00
Paused = 0x01
Reverse = 0x02
FastForward = 0x03
FastReverse = 0x04
//Level Challenges

LevelChallenges = {

1:{"title":"Still An Obvious Shortcut","LevelName":"HAIRPIN","ID1":BeginnerIDs[3]["id"],"ID2":World1IDs[6]["id"],"description":"Reach the goal in 3 seconds or less","Points":2,"TotalSec":60,"SpeedrunSec":3,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
2:{"title":"I Love Bridges","LevelName":"WIDE BRIDGE","ID1":BeginnerIDs[4]["id"],"ID2":World1IDs[7]["id"],"description":"Reach the goal in 10 seconds or less","Points":2,"TotalSec":60,"SpeedrunSec":10,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
3:{"title":"Do A Kickflip!","LevelName":"HOLLOW","ID1":BeginnerIDs[6]["id"],"ID2":World1IDs[19]["id"],"description":"Collect the banana bunch and reach the goal in 10 seconds or less","Points":3,"TotalSec":60,"SpeedrunSec":10,"Comp1":"<","BananaQty":NULL,"BananaBunch":1,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
4:{"title":"Braille Appreciator","LevelName":"BUMPY","ID1":BeginnerIDs[7]["id"],"ID2":World1IDs[5]["id"],"description":"Collect all bananas and reach the goal","Points":4,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":Yes,"Speed":NULL,"Comp2":"NULL"},
5:{"title":"What's This Button Do?","LevelName":"SWITCHES","ID1":BeginnerIDs[8]["id"],"ID2":World1IDs[20]["id"],"description":"Enter the green warp goal","Points":3,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":Green,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
6:{"title":"Platform Tour","LevelName":"FLOATERS","ID1":BeginnerIDs[9]["id"],"ID2":World1IDs[10]["id"],"description":"Collect all bananas and reach the goal","Points":3,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":Yes,"Speed":NULL,"Comp2":"NULL"},
7:{"title":"Getting Edgy","LevelName":"EDGE","ID1":BeginnerIDs[11]["id"],"ID2":World1IDs[3]["id"],"description":"Collect both banana bunches and reach the goal","Points":5,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":2,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
8:{"title":"Elevator Action","LevelName":"ESCALATORS","ID1":BeginnerIDs[12]["id"],"ID2":World1IDs[4]["id"],"description":"Collect 25 or more bananas and reach the goal in 30 seconds or less","Points":3,"TotalSec":60,"SpeedrunSec":30,"Comp1":"<","BananaQty":25,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
9:{"title":"Wall Master","LevelName":"SERPENTINE","ID1":BeginnerIDs[13]["id"],"ID2":World1IDs[9]["id"],"description":"Collect all bananas and reach the goal","Points":5,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":Yes,"Speed":NULL,"Comp2":"NULL"},
10:{"title":"Swirl Skipper","LevelName":"SWIRL","ID1":BeginnerIDs[14]["id"],"ID2":World1IDs[12]["id"],"description":"Reach the goal in 15 seconds or less","Points":3,"TotalSec":60,"SpeedrunSec":15,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
11:{"title":"Wall Master 2","LevelName":"COMPOSITION","ID1":BeginnerIDs[16]["id"],"ID2":World2IDs[3]["id"],"description":"Collect all banana bunches and reach the goal","Points":10,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":6,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
12:{"title":"Monkey-Go-Round","LevelName":"DYNAMO","ID1":BeginnerIDs[17]["id"],"ID2":World2IDs[4]["id"],"description":"Collect all bananas and reach the goal","Points":2,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":Yes,"Speed":NULL,"Comp2":"NULL"},
13:{"title":"Gutter Punch","LevelName":"GUTTER","ID1":BeginnerIDs[19]["id"],"ID2":World2IDs[12]["id"],"description":"Reach the goal in 4 seconds or less","Points":4,"TotalSec":60,"SpeedrunSec":4,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
14:{"title":"Slopestyle","LevelName":"RISING INCLINES","ID1":BeginnerIDs[20]["id"],"ID2":BeginnerIDs[20]["id"],"description":"Collect all bananas","Points":5,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":Yes,"Speed":NULL,"Comp2":"NULL"},
15:{"title":"Nope To Slope","LevelName":"SLOPES","ID1":BeginnerIDs[21]["id"],"ID2":World1IDs[14]["id"],"description":"Reach the goal in 5 seconds or less","Points":3,"TotalSec":60,"SpeedrunSec":5,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
16:{"title":"This Achievement Is No Longer Sponsored By Dole®","LevelName":"BLOCKS","ID1":BeginnerIDs[23]["id"],"ID2":World2IDs[2]["id"],"description":"Collect all bananas and reach the goal in 30 seconds or less","Points":4,"TotalSec":60,"SpeedrunSec":30,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":Yes,"Speed":NULL,"Comp2":"NULL"},
17:{"title":"Not A Single One","LevelName":"JUMP SINGLE","ID1":BeginnerIDs[24]["id"],"ID2":World2IDs[6]["id"],"description":"Reach the goal without collecting bananas","Points":2,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":0,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
18:{"title":"Acing The Test","LevelName":"EXAM-A","ID1":BeginnerIDs[25]["id"],"ID2":World2IDs[7]["id"],"description":"Reach the goal in 10 seconds or less","Points":4,"TotalSec":60,"SpeedrunSec":10,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
19:{"title":"Tubtastic","LevelName":"TUB","ID1":BeginnerIDs[26]["id"],"ID2":World1IDs[11]["id"],"description":"Reach the goal in 7 seconds or less","Points":10,"TotalSec":60,"SpeedrunSec":7,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
20:{"title":"Slider Flyover","LevelName":"SLIDERS","ID1":BeginnerIDs[27]["id"],"ID2":World1IDs[13]["id"],"description":"Reach the goal in 10 seconds or less","Points":5,"TotalSec":60,"SpeedrunSec":10,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
21:{"title":"Dangerous Activities","LevelName":"SPINNING TOP","ID1":BeginnerIDs[28]["id"],"ID2":World1IDs[15]["id"],"description":"Collect all bananas and reach the goal","Points":4,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":Yes,"Speed":NULL,"Comp2":"NULL"},
22:{"title":"Picking At Scabs","LevelName":"SCABROUS","ID1":BeginnerIDs[30]["id"],"ID2":BeginnerIDs[30]["id"],"description":"Collect all bananas in 45 seconds or less","Points":4,"TotalSec":60,"SpeedrunSec":45,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":Yes,"Speed":NULL,"Comp2":"NULL"},
23:{"title":"Jolt Bolt","LevelName":"JOLT CHANNEL","ID1":BeginnerIDs[31]["id"],"ID2":World2IDs[17]["id"],"description":"Collect all bananas and reach the goal","Points":4,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":Yes,"Speed":NULL,"Comp2":"NULL"},
24:{"title":"Sewer Surfing","LevelName":"SEWER","ID1":BeginnerIDs[34]["id"],"ID2":World3IDs[9]["id"],"description":"Reach the goal in 12 seconds or less","Points":4,"TotalSec":60,"SpeedrunSec":12,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
25:{"title":"I Hate Bridges","LevelName":"ARC BRIDGES","ID1":BeginnerIDs[35]["id"],"ID2":World3IDs[12]["id"],"description":"Reach the goal in 13 seconds or less","Points":4,"TotalSec":60,"SpeedrunSec":13,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
26:{"title":"Speeder Teeter","LevelName":"TEETER","ID1":BeginnerIDs[37]["id"],"ID2":BeginnerIDs[37]["id"],"description":"Reach the goal in 15 seconds or less","Points":2,"TotalSec":60,"SpeedrunSec":15,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
27:{"title":"Nightmare Wire","LevelName":"CATWALK","ID1":BeginnerIDs[39]["id"],"ID2":BeginnerIDs[39]["id"],"description":"Survive the thinnest path and reach the goal","Points":25,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":7,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
28:{"title":"AKA: RGG","LevelName":"AV LOGO","ID1":BeginnerExtraIDs[3]["id"],"ID2":BeginnerExtraIDs[3]["id"],"description":"Collect all bananas and reach the goal","Points":5,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":Yes,"Speed":NULL,"Comp2":"NULL"},
29:{"title":"Unsafe Swimming","LevelName":"BUOY","ID1":BeginnerExtraIDs[5]["id"],"ID2":BeginnerExtraIDs[5]["id"],"description":"Reach the goal without collecting any bananas","Points":2,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":0,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
30:{"title":"Rook Behavior","LevelName":"BUMPY CHECK","ID1":BeginnerExtraIDs[7]["id"],"ID2":World2IDs[8]["id"],"description":"Reach the goal in 10 seconds or less","Points":4,"TotalSec":60,"SpeedrunSec":10,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
31:{"title":"Bad Button","LevelName":"ALTERNATIVE","ID1":BeginnerExtraIDs[8]["id"],"ID2":World2IDs[18]["id"],"description":"Collect all bananas with the fast forward switch on and reach the goal","Points":5,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":Yes,"Speed":FastForward,"Comp2":"="},
32:{"title":"AiAi's Secret Family Technique","LevelName":"BEAD SCREEN","ID1":BeginnerExtraIDs[10]["id"],"ID2":World5IDs[7]["id"],"description":"Reach the goal without pressing any switch","Points":4,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":Play,"Comp2":"="},
33:{"title":"Coil Foil","LevelName":"COIL RAMP","ID1":BeginnerExtraIDs[11]["id"],"ID2":BeginnerExtraIDs[11]["id"],"description":"Reach the goal in 4 seconds or less","Points":10,"TotalSec":60,"SpeedrunSec":4,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
34:{"title":"French Flavoring","LevelName":"MILLEFEUILLE","ID1":BeginnerExtraIDs[12]["id"],"ID2":BeginnerExtraIDs[12]["id"],"description":"Collect all bananas and reach the goal","Points":2,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":Yes,"Speed":NULL,"Comp2":"NULL"},
35:{"title":"Surfing Lessions","LevelName":"WAVER","ID1":BeginnerExtraIDs[13]["id"],"ID2":BeginnerExtraIDs[13]["id"],"description":"Enter the green warp goal","Points":5,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":Green,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
36:{"title":"Watch Out For The Stairs","LevelName":"TREADS","ID1":BeginnerExtraIDs[15]["id"],"ID2":BeginnerExtraIDs[15]["id"],"description":"Collect the banana bunch and reach the goal in 15 seconds or less","Points":5,"TotalSec":60,"SpeedrunSec":15,"Comp1":"<","BananaQty":NULL,"BananaBunch":1,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
37:{"title":"Super Monkey Cube","LevelName":"FLUCTUATION","ID1":BeginnerExtraIDs[16]["id"],"ID2":World5IDs[17]["id"],"description":"Reach the goal in 10 seconds or less","Points":4,"TotalSec":60,"SpeedrunSec":10,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
38:{"title":"Path To The Center","LevelName":"FOLDERS","ID1":BeginnerExtraIDs[17]["id"],"ID2":World6IDs[17]["id"],"description":"Collect all bananas and reach the goal in 13 seconds or less","Points":25,"TotalSec":60,"SpeedrunSec":13,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":Yes,"Speed":NULL,"Comp2":"NULL"},
39:{"title":"Skip Hospital Bills With One Easy Trick!","LevelName":"BIRTH","ID1":BeginnerExtraIDs[20]["id"],"ID2":BeginnerExtraIDs[20]["id"],"description":"Reach the goal without pressing the pause switch","Points":3,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":Paused,"Comp2":"!="},
40:{"title":"Scenic Route","LevelName":"WALKING","ID1":AdvancedIDs[2]["id"],"ID2":World2IDs[16]["id"],"description":"Collect all bananas and reach the goal","Points":2,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":Yes,"Speed":NULL,"Comp2":"NULL"},
41:{"title":"Repulsive Bananas","LevelName":"REPULSE","ID1":AdvancedIDs[3]["id"],"ID2":World3IDs[2]["id"],"description":"Reach the goal without collecting any bananas in 6 seconds or less","Points":3,"TotalSec":60,"SpeedrunSec":6,"Comp1":"<","BananaQty":0,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
42:{"title":"Bridge Over Troubled Bottomless Pit","LevelName":"NARROW BRIDGE","ID1":AdvancedIDs[4]["id"],"ID2":World3IDs[6]["id"],"description":"Reach the goal in 10 seconds or less","Points":4,"TotalSec":60,"SpeedrunSec":10,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
43:{"title":"Careful Curves","LevelName":"CURVES","ID1":AdvancedIDs[6]["id"],"ID2":World3IDs[14]["id"],"description":"Reach the goal without collecting any bananas in 6 seconds or less","Points":5,"TotalSec":60,"SpeedrunSec":6,"Comp1":"<","BananaQty":0,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
44:{"title":"Will The Real AiAi Please Stand Up?","LevelName":"BLOCKS SLIM","ID1":AdvancedIDs[8]["id"],"ID2":World4IDs[2]["id"],"description":"Collect all the bananas and reach the goal in 40 seconds or less","Points":5,"TotalSec":60,"SpeedrunSec":40,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":Yes,"Speed":NULL,"Comp2":"NULL"},
45:{"title":"Greener String","LevelName":"CHOICE","ID1":AdvancedIDs[9]["id"],"ID2":World4IDs[6]["id"],"description":"Enter the green warp goal","Points":25,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":Green,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
46:{"title":"Jump For Joy","LevelName":"JUMP RAMP","ID1":AdvancedIDs[11]["id"],"ID2":World4IDs[3]["id"],"description":"Collect all bananas and reach the goal in 12 seconds or less","Points":4,"TotalSec":60,"SpeedrunSec":12,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":Yes,"Speed":NULL,"Comp2":"NULL"},
47:{"title":"Dentistry","LevelName":"HOUNDS TOOTH","ID1":AdvancedIDs[12]["id"],"ID2":World4IDs[4]["id"],"description":"Reach the goal without collecting any bananas","Points":2,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":0,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
48:{"title":"GACT Pact","LevelName":"D.N.A.","ID1":AdvancedIDs[13]["id"],"ID2":World4IDs[9]["id"],"description":"Enter the green warp goal in 7 seconds or less","Points":10,"TotalSec":60,"SpeedrunSec":7,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":Green,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
49:{"title":"Deep Sea Rolls","LevelName":"SCROLLS","ID1":AdvancedIDs[15]["id"],"ID2":World4IDs[17]["id"],"description":"Collect all bananas and reach the goal in 20 seconds or less","Points":4,"TotalSec":60,"SpeedrunSec":20,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":Yes,"Speed":NULL,"Comp2":"NULL"},

50:{"title":"Cliff Skiff","LevelName":"CLIFF","ID1":AdvancedIDs[16]["id"],"ID2":AdvancedIDs[16]["id"],"description":"Reach the goal in 5 seconds or less","Points":4,"TotalSec":60,"SpeedrunSec":5,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
51:{"title":"Semicircle Adventures","LevelName":"CONCENTRIC","ID1":AdvancedIDs[17]["id"],"ID2":AdvancedIDs[17]["id"],"description":"Reach the goal in 10 seconds or less","Points":5,"TotalSec":60,"SpeedrunSec":10,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
52:{"title":"Touched Down","LevelName":"STADIUM","ID1":AdvancedIDs[18]["id"],"ID2":AdvancedIDs[18]["id"],"description":"Reach the goal in 6 seconds or less","Points":3,"TotalSec":60,"SpeedrunSec":6,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
53:{"title":"Roll-Playing Game","LevelName":"DUNGEON","ID1":AdvancedIDs[19]["id"],"ID2":AdvancedIDs[19]["id"],"description":"Reach the goal in 25 seconds or less","Points":4,"TotalSec":60,"SpeedrunSec":25,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
54:{"title":"Bankrupt","LevelName":"BANKS","ID1":AdvancedIDs[21]["id"],"ID2":World2IDs[1]["id"],"description":"Reach the goal in  6 seconds or less without collecting any bananas","Points":3,"TotalSec":60,"SpeedrunSec":6,"Comp1":"<","BananaQty":0,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
55:{"title":"Speed Eating","LevelName":"EATEN FLOOR","ID1":AdvancedIDs[22]["id"],"ID2":World2IDs[19]["id"],"description":"Reach the goal in 8 seconds or less","Points":5,"TotalSec":60,"SpeedrunSec":8,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
56:{"title":"Hopped Up","LevelName":"HOPPERS","ID1":AdvancedIDs[23]["id"],"ID2":World2IDs[5]["id"],"description":"Reach the goal with the fast forward switch on","Points":2,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":FastForward,"Comp2":"="},
57:{"title":"Thrillville","LevelName":"COASTER","ID1":AdvancedIDs[24]["id"],"ID2":World2IDs[20]["id"],"description":"Collect any banana bunch after you enter the goal","Points":3,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":1,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
58:{"title":"Do The Worm","LevelName":"INCHWORMS","ID1":AdvancedIDs[27]["id"],"ID2":World2IDs[13]["id"],"description":"Enter the red warp goal","Points":4,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":Red,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
59:{"title":"Pole Positioning","LevelName":"TOTALITARIANISM","ID1":AdvancedIDs[28]["id"],"ID2":World2IDs[15]["id"],"description":"Collect all bananas and reach the goal with the fast forward switch on","Points":3,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":Yes,"Speed":FastForward,"Comp2":"="},
60:{"title":"Shred It Up","LevelName":"BOARD PARK","ID1":AdvancedIDs[30]["id"],"ID2":AdvancedIDs[30]["id"],"description":"Collect all bananas","Points":10,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":Yes,"Speed":NULL,"Comp2":"NULL"},
61:{"title":"Unstoppable","LevelName":"STOPPERS","ID1":AdvancedIDs[33]["id"],"ID2":World4IDs[16]["id"],"description":"Reach the goal in 4 seconds or less","Points":5,"TotalSec":60,"SpeedrunSec":4,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
62:{"title":"Bent Out Of Shape, Again","LevelName":"FLOOR BENT","ID1":AdvancedIDs[34]["id"],"ID2":World5IDs[2]["id"],"description":"Reach the goal in 12 seconds or less without collecting any bananas","Points":5,"TotalSec":60,"SpeedrunSec":12,"Comp1":"<","BananaQty":0,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
63:{"title":"Treadmill Jumps","LevelName":"CONVEYOR","ID1":AdvancedIDs[35]["id"],"ID2":World5IDs[19]["id"],"description":"Reach the goal in 5 seconds or less","Points":1,"TotalSec":30,"SpeedrunSec":5,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
64:{"title":"Class Act","LevelName":"EXAM-B","ID1":AdvancedIDs[36]["id"],"ID2":World5IDs[5]["id"],"description":"Reach the goal in 10 seconds or less","Points":3,"TotalSec":60,"SpeedrunSec":10,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
65:{"title":"Runaway Goal","LevelName":"CHASER","ID1":AdvancedIDs[37]["id"],"ID2":World5IDs[20]["id"],"description":"Enter the red warp goal","Points":2,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":Red,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
66:{"title":"Double Bump","LevelName":"JUMP DOUBLE","ID1":AdvancedIDs[38]["id"],"ID2":World5IDs[8]["id"],"description":"Reach the goal in 3 seconds or less","Points":3,"TotalSec":30,"SpeedrunSec":3,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
67:{"title":"Motorized Monkey Machine","LevelName":"REVERSIBLE GEAR","ID1":AdvancedIDs[41]["id"],"ID2":World3IDs[19]["id"],"description":"Collect all bananas and reach the goal","Points":25,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":Yes,"Speed":NULL,"Comp2":"NULL"},
68:{"title":"Precarious Pebbles","LevelName":"STEPPING STONES","ID1":AdvancedIDs[42]["id"],"ID2":World3IDs[5]["id"],"description":"Collect the banana bunch and reach the goal","Points":4,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":1,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
69:{"title":"Super Monkey Ballin'","LevelName":"DRIBBLES","ID1":AdvancedIDs[43]["id"],"ID2":World3IDs[20]["id"],"description":"Reach the goal with the fast forward switch on","Points":5,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":FastForward,"Comp2":"="},
70:{"title":"Internet Browsing","LevelName":"URL","ID1":AdvancedIDs[44]["id"],"ID2":World3IDs[8]["id"],"description":"Reach the goal in 8 seconds or less","Points":10,"TotalSec":60,"SpeedrunSec":8,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
71:{"title":"Mad Ring Collector","LevelName":"MAD RINGS","ID1":AdvancedIDs[45]["id"],"ID2":World3IDs[10]["id"],"description":"Collect all bananas and reach the goal","Points":5,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":Yes,"Speed":NULL,"Comp2":"NULL"},
72:{"title":"Storm Chaser","LevelName":"TWISTER","ID1":AdvancedIDs[47]["id"],"ID2":World3IDs[13]["id"],"description":"Reach the goal in 7 seconds or less","Points":3,"TotalSec":60,"SpeedrunSec":7,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
73:{"title":"Cascade Catch","LevelName":"CASCADE","ID1":AdvancedIDs[48]["id"],"ID2":World3IDs[15]["id"],"description":"Reach the goal in 5 seconds or less","Points":10,"TotalSec":60,"SpeedrunSec":5,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
74:{"title":"Tony Hawk's Pro Baller","LevelName":"PRO SKATERS","ID1":AdvancedIDs[49]["id"],"ID2":World4IDs[1]["id"],"description":"Enter the green warp goal","Points":5,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":Green,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
75:{"title":"Tony Hawk's Pro Baller 2","LevelName":"RAMPAGE","ID1":AdvancedIDs[50]["id"],"ID2":AdvancedIDs[50]["id"],"description":"Collect all bananas","Points":5,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":Yes,"Speed":NULL,"Comp2":"NULL"},
76:{"title":"Bananantless Lion","LevelName":"ANT LION","ID1":AdvancedIDs[51]["id"],"ID2":World5IDs[12]["id"],"description":"Reach the goal without collecting any bananas","Points":1,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":0,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
77:{"title":"Rebounder DX","LevelName":"COLLAPSE","ID1":AdvancedIDs[52]["id"],"ID2":World5IDs[14]["id"],"description":"Reach the goal in 5 seconds or less","Points":3,"TotalSec":60,"SpeedrunSec":5,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
78:{"title":"Warping The Easier Way","LevelName":"LABYRINTH","ID1":AdvancedIDs[54]["id"],"ID2":World5IDs[18]["id"],"description":"Enter the green warp goal in 3 seconds or less","Points":2,"TotalSec":60,"SpeedrunSec":3,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":Green,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
79:{"title":"Tidal Tempest","LevelName":"WAVY JUMP","ID1":AdvancedIDs[56]["id"],"ID2":World6IDs[19]["id"],"description":"Collect all bananas and reach the goal","Points":3,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":Yes,"Speed":NULL,"Comp2":"NULL"},
80:{"title":"Spiked Run","LevelName":"SPIKY","ID1":AdvancedIDs[57]["id"],"ID2":World6IDs[5]["id"],"description":"Reach the goal in 6 seconds or less","Points":5,"TotalSec":30,"SpeedrunSec":6,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
81:{"title":"No Rest For The Wicked","LevelName":"UNREST","ID1":AdvancedIDs[58]["id"],"ID2":World6IDs[20]["id"],"description":"Reach the goal in 3 seconds or less","Points":2,"TotalSec":30,"SpeedrunSec":3,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
82:{"title":"Search For The Endurance","LevelName":"POLAR","ID1":AdvancedIDs[59]["id"],"ID2":World6IDs[8]["id"],"description":"Collect all bananas and reach the goal","Points":3,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":Yes,"Speed":NULL,"Comp2":"NULL"},
83:{"title":"Hair Stylist","LevelName":"GIANT COMB","ID1":AdvancedIDs[61]["id"],"ID2":World4IDs[19]["id"],"description":"Reach the goal in 10 seconds or less","Points":4,"TotalSec":60,"SpeedrunSec":10,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
84:{"title":"I Love Bees","LevelName":"BEEHIVE","ID1":AdvancedIDs[62]["id"],"ID2":World4IDs[5]["id"],"description":"Collect all bananas and reach the goal","Points":3,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":Yes,"Speed":NULL,"Comp2":"NULL"},
85:{"title":"Wall Runner","LevelName":"DYNAMIC MAZE","ID1":AdvancedIDs[63]["id"],"ID2":World4IDs[20]["id"],"description":"Reach the goal in 10 seconds or less","Points":5,"TotalSec":60,"SpeedrunSec":10,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
86:{"title":"First Try","LevelName":"LAUNCHERS","ID1":AdvancedIDs[65]["id"],"ID2":World4IDs[10]["id"],"description":"Enter the green warp goal in 13 seconds or less","Points":5,"TotalSec":60,"SpeedrunSec":13,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":Green,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
87:{"title":"The First Dime","LevelName":"COIN SLOTS","ID1":AdvancedIDs[67]["id"],"ID2":World4IDs[13]["id"],"description":"Enter the green warp goal","Points":10,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":Green,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
88:{"title":"Speedsaw Bridges","LevelName":"SEESAW BRIDGES","ID1":AdvancedIDs[68]["id"],"ID2":World4IDs[15]["id"],"description":"Reach the goal in 30 seconds or less","Points":5,"TotalSec":60,"SpeedrunSec":30,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
89:{"title":"Arachnophobia","LevelName":"ARTHROPOD","ID1":AdvancedIDs[69]["id"],"ID2":World4IDs[18]["id"],"description":"Reach the goal in 8 seconds or less","Points":5,"TotalSec":60,"SpeedrunSec":8,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
90:{"title":"Walkthrough","LevelName":"PUZZLE","ID1":AdvancedExtraIDs[3]["id"],"ID2":AdvancedExtraIDs[3]["id"],"description":"Reach the goal in 5 seconds or less","Points":10,"TotalSec":60,"SpeedrunSec":5,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
91:{"title":"Weightless Sphere","LevelName":"HEAVY SPHERE","ID1":AdvancedExtraIDs[7]["id"],"ID2":AdvancedExtraIDs[7]["id"],"description":"Reach the goal without pressing the switch","Points":10,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":Paused,"Comp2":"="},
92:{"title":"Staggering Moves","LevelName":"STAGGER","ID1":AdvancedExtraIDs[8]["id"],"ID2":AdvancedExtraIDs[8]["id"],"description":"Reach the goal in 11 seconds or less","Points":10,"TotalSec":60,"SpeedrunSec":11,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
93:{"title":"Unidentified Flying Banana","LevelName":"UFO","ID1":AdvancedExtraIDs[9]["id"],"ID2":AdvancedExtraIDs[9]["id"],"description":"Collect all bananas and reach the goal","Points":5,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":Yes,"Speed":NULL,"Comp2":"NULL"},
94:{"title":"Hoop, Skip, And Many Jumps","LevelName":"RING BRIDGES","ID1":AdvancedExtraIDs[10]["id"],"ID2":AdvancedExtraIDs[10]["id"],"description":"Reach the goal in 10 seconds or less","Points":5,"TotalSec":60,"SpeedrunSec":10,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
95:{"title":"Maze Madness","LevelName":"CHAOS","ID1":AdvancedExtraIDs[11]["id"],"ID2":AdvancedExtraIDs[11]["id"],"description":"Collect at least 50 bananas and reach the goal","Points":5,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":50,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
96:{"title":"Turning Is Optional","LevelName":"TILT MAZE","ID1":AdvancedExtraIDs[12]["id"],"ID2":AdvancedExtraIDs[12]["id"],"description":"Reach the goal in 8 seconds or less","Points":5,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
97:{"title":"Tricky Triangles","LevelName":"FRACTAL","ID1":AdvancedExtraIDs[13]["id"],"ID2":AdvancedExtraIDs[13]["id"],"description":"Reach the goal without collecting any bananas","Points":10,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":0,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
98:{"title":"King Of The Hills","LevelName":"HILLS","ID1":AdvancedExtraIDs[14]["id"],"ID2":AdvancedExtraIDs[14]["id"],"description":"Enter the green warp goal in 11 seconds or less","Points":4,"TotalSec":60,"SpeedrunSec":11,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":Green,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
99:{"title":"Thunderdome","LevelName":"DOMES","ID1":AdvancedExtraIDs[16]["id"],"ID2":AdvancedExtraIDs[16]["id"],"description":"Reach the goal in 7 seconds or less","Points":2,"TotalSec":60,"SpeedrunSec":7,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
100:{"title":"Long Faller","LevelName":"LONG SLIDER","ID1":AdvancedExtraIDs[18]["id"],"ID2":AdvancedExtraIDs[18]["id"],"description":"Reach the goal in 8 seconds or less","Points":4,"TotalSec":60,"SpeedrunSec":8,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
101:{"title":"Lattice Longitude","LevelName":"GRID BRIDGE","ID1":AdvancedExtraIDs[19]["id"],"ID2":AdvancedExtraIDs[19]["id"],"description":"Reach the goal with the fast forward switch on","Points":4,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":FastForward,"Comp2":"="},
102:{"title":"Branching Out","LevelName":"BRANCH","ID1":ExpertIDs[2]["id"],"ID2":World6IDs[12]["id"],"description":"Enter the red warp goal in 5 seconds or less","Points":4,"TotalSec":30,"SpeedrunSec":5,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":Red,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
103:{"title":"Underhanded Tactics","LevelName":"OVERTURN","ID1":ExpertIDs[3]["id"],"ID2":World6IDs[14]["id"],"description":"Enter the green warp goal","Points":3,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":Green,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
104:{"title":"Broken Barrier","LevelName":"EXCURSION","ID1":ExpertIDs[4]["id"],"ID2":World6IDs[16]["id"],"description":"Reach the goal in 7 seconds or less","Points":5,"TotalSec":60,"SpeedrunSec":7,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
105:{"title":"12 Sided Bananas","LevelName":"DODECAGON","ID1":ExpertIDs[5]["id"],"ID2":World6IDs[18]["id"],"description":"Collect all bananas and reach the goal","Points":4,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":Yes,"Speed":NULL,"Comp2":"NULL"},
106:{"title":"The C Stands For 'Crying'","LevelName":"EXAM-C","ID1":ExpertIDs[6]["id"],"ID2":World7IDs[2]["id"],"description":"Reach the goal without collecting any bananas","Points":25,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":0,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
107:{"title":"Just A Small Corner Cut","LevelName":"TRACKS","ID1":ExpertIDs[8]["id"],"ID2":World7IDs[5]["id"],"description":"Reach the goal in 10 seconds or less","Points":5,"TotalSec":60,"SpeedrunSec":10,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
108:{"title":"Dream On","LevelName":"FREE FALL","ID1":ExpertIDs[12]["id"],"ID2":World5IDs[3]["id"],"description":"Collect the banana bunch and reach the green warp goal","Points":5,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":1,"goal":Green,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
109:{"title":"Maddest Shuffle","LevelName":"MAD SHUFFLE","ID1":ExpertIDs[14]["id"],"ID2":World5IDs[6]["id"],"description":"Reach the goal with the fast forward switch on","Points":10,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":FastForward,"Comp2":"="},
110:{"title":"Bouncy Castle","LevelName":"JUMP MACHINE","ID1":ExpertIDs[15]["id"],"ID2":World5IDs[9]["id"],"description":"Collect all bananas and reach the red warp goal","Points":10,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":Red,"AllBananas":Yes,"Speed":NULL,"Comp2":"NULL"},
111:{"title":"Fighting Slope","LevelName":"ZIGZAG SLOPE","ID1":ExpertIDs[16]["id"],"ID2":World5IDs[11]["id"],"description":"Collect the banana bunch and reach the goal","Points":3,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":1,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
112:{"title":"Tilted Tower","LevelName":"TOWER","ID1":ExpertIDs[17]["id"],"ID2":World5IDs[13]["id"],"description":"Reach the goal in 11 seconds or less","Points":5,"TotalSec":60,"SpeedrunSec":11,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
113:{"title":"Combination Lock","LevelName":"COMBINATION","ID1":ExpertIDs[19]["id"],"ID2":World6IDs[1]["id"],"description":"Reach the goal in 7 seconds or less","Points":5,"TotalSec":60,"SpeedrunSec":7,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
114:{"title":"Cabella's Biggest Hunt","LevelName":"BONUS HUNTING","ID1":ExpertIDs[20]["id"],"ID2":ExpertIDs[20]["id"],"description":"Collect at least 20 bananas","Points":4,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":20,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
115:{"title":"Gear Grinding","LevelName":"GEARS","ID1":ExpertIDs[21]["id"],"ID2":World7IDs[8]["id"],"description":"Collect all bananas and reach the goal","Points":3,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":Yes,"Speed":NULL,"Comp2":"NULL"},
116:{"title":"Destruction Of All Monkeykind","LevelName":"DESTRUCTION","ID1":ExpertIDs[22]["id"],"ID2":World7IDs[10]["id"],"description":"Collect all bananas and reach the goal","Points":5,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":Yes,"Speed":NULL,"Comp2":"NULL"},
117:{"title":"Scuba Diver","LevelName":"DIVING","ID1":ExpertIDs[24]["id"],"ID2":World7IDs[14]["id"],"description":"Collect all bananas and reach the goal","Points":2,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":Yes,"Speed":NULL,"Comp2":"NULL"},
118:{"title":"Slant Style","LevelName":"FLOOR SLANT","ID1":ExpertIDs[25]["id"],"ID2":World7IDs[16]["id"],"description":"Reach the goal in 3 seconds or less","Points":3,"TotalSec":30,"SpeedrunSec":3,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
119:{"title":"Longing For A Snack","LevelName":"SWING BAR LONG","ID1":ExpertIDs[27]["id"],"ID2":World8IDs[2]["id"],"description":"Reach the goal without collecting any bananas","Points":10,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":0,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},

120:{"title":"Office Chair Racing","LevelName":"PAPER WORK","ID1":ExpertIDs[28]["id"],"ID2":World8IDs[19]["id"],"description":"Reach the goal in 3 seconds or less","Points":3,"TotalSec":60,"SpeedrunSec":3,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
121:{"title":"Charming Seige From All Sides","LevelName":"TWIN ATTACKER","ID1":ExpertIDs[29]["id"],"ID2":World8IDs[5]["id"],"description":"Reach the goal without collecting any bananas","Points":5,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":0,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
122:{"title":"Master Boot Record","LevelName":"PARTITION","ID1":ExpertIDs[30]["id"],"ID2":ExpertIDs[30]["id"],"description":"Collect all bananas","Points":5,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":Yes,"Speed":NULL,"Comp2":"NULL"},
123:{"title":"Seesaw Fisticuffs","LevelName":"PUNCHED SEESAWS","ID1":ExpertIDs[31]["id"],"ID2":World6IDs[3]["id"],"description":"Enter the green warp goal without collecting any bananas","Points":5,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":0,"BananaBunch":NULL,"goal":Green,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
124:{"title":"Sydney Sprint","LevelName":"OPERA","ID1":ExpertIDs[32]["id"],"ID2":World6IDs[4]["id"],"description":"Reach the goal in 12 seconds or less","Points":10,"TotalSec":60,"SpeedrunSec":12,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
125:{"title":"Tears","LevelName":"TIERS","ID1":ExpertIDs[34]["id"],"ID2":World6IDs[7]["id"],"description":"Enter the red warp goal","Points":25,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":Red,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
126:{"title":"Rapid Descent","LevelName":"CLIFFS","ID1":ExpertIDs[35]["id"],"ID2":World6IDs[9]["id"],"description":"Reach the goal in 7 seconds or less","Points":5,"TotalSec":60,"SpeedrunSec":7,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
127:{"title":"Himalayan Journey","LevelName":"NARROW PEAKS","ID1":ExpertIDs[36]["id"],"ID2":World6IDs[11]["id"],"description":"Collect all bananas and reach the goal","Points":5,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":Yes,"Speed":NULL,"Comp2":"NULL"},
129:{"title":"Big Bossed","LevelName":"SNAKE","ID1":ExpertIDs[42]["id"],"ID2":World8IDs[8]["id"],"description":"Reach the goal in 3 seconds or less","Points":5,"TotalSec":30,"SpeedrunSec":3,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
130:{"title":"Gust Front","LevelName":"WIND","ID1":ExpertIDs[43]["id"],"ID2":World8IDs[10]["id"],"description":"Reach the goal in 33 seconds or less","Points":4,"TotalSec":60,"SpeedrunSec":33,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
131:{"title":"Banana Cushions","LevelName":"FALL DOWN","ID1":ExpertIDs[45]["id"],"ID2":World8IDs[14]["id"],"description":"Collect all bananas and reach the goal in 15 seconds or less","Points":3,"TotalSec":30,"SpeedrunSec":15,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":Yes,"Speed":NULL,"Comp2":"NULL"},
132:{"title":"Thin Crossed","LevelName":"TWIN CROSS","ID1":ExpertIDs[46]["id"],"ID2":World8IDs[16]["id"],"description":"Reach the goal in 4 seconds or less","Points":4,"TotalSec":60,"SpeedrunSec":4,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
133:{"title":"Crusader King","LevelName":"SPIRAL HARD","ID1":ExpertIDs[47]["id"],"ID2":World8IDs[18]["id"],"description":"Reach the goal in 5 seconds or less","Points":2,"TotalSec":60,"SpeedrunSec":5,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
134:{"title":"Part Of A Problem","LevelName":"CONVEYOR PARTS","ID1":ExpertIDs[48]["id"],"ID2":World9IDs[2]["id"],"description":"Reach the goal in 5 seconds or less","Points":3,"TotalSec":60,"SpeedrunSec":5,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
135:{"title":"Richter's Nap","LevelName":"EARTHQUAKE","ID1":ExpertIDs[50]["id"],"ID2":ExpertIDs[50]["id"],"description":"Reach the goal without pressing the switch","Points":3,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":Paused,"Comp2":"="},
136:{"title":"Slam Dunk","LevelName":"OBSTACLE","ID1":ExpertIDs[52]["id"],"ID2":World7IDs[4]["id"],"description":"Reach the goal in 6 seconds or less","Points":25,"TotalSec":60,"SpeedrunSec":6,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
137:{"title":"Hierarchy Of Needs","LevelName":"HIERARCHY","ID1":ExpertIDs[57]["id"],"ID2":World7IDs[13]["id"],"description":"Reach the goal in 10 seconds or less","Points":5,"TotalSec":60,"SpeedrunSec":10,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
138:{"title":"Banana Bracelet","LevelName":"8 BRACELETS","ID1":ExpertIDs[58]["id"],"ID2":World7IDs[15]["id"],"description":"Collect all banana bunches and reach the goal","Points":10,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":4,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
139:{"title":"Bananant Lion","LevelName":"ANT LION SUPER","ID1":ExpertIDs[62]["id"],"ID2":World9IDs[20]["id"],"description":"Collect all bananas and reach the goal","Points":2,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":Yes,"Speed":NULL,"Comp2":"NULL"},
140:{"title":"Drum And Bass","LevelName":"DRUM","ID1":ExpertIDs[63]["id"],"ID2":World9IDs[8]["id"],"description":"Collect all bananas and reach the goal","Points":5,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":Yes,"Speed":NULL,"Comp2":"NULL"},
141:{"title":"Twist And Speed","LevelName":"TWIST & SPIN","ID1":ExpertIDs[64]["id"],"ID2":World9IDs[10]["id"],"description":"Reach the goal in 5 seconds or less","Points":2,"TotalSec":60,"SpeedrunSec":5,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
142:{"title":"Delicate Astronomer","LevelName":"CASSIOPEIA","ID1":ExpertIDs[67]["id"],"ID2":World9IDs[16]["id"],"description":"Reach the goal in 9 seconds or less without collecting any bananas","Points":3,"TotalSec":30,"SpeedrunSec":9,"Comp1":"<","BananaQty":0,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
143:{"title":"Bowl Over","LevelName":"BOWL OPEN","ID1":ExpertIDs[69]["id"],"ID2":World10IDs[2]["id"],"description":"Reach the goal in 3 seconds or less","Points":3,"TotalSec":30,"SpeedrunSec":3,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
144:{"title":"UFC Chimpion","LevelName":"FIGHTERS","ID1":ExpertIDs[70]["id"],"ID2":ExpertIDs[70]["id"],"description":"Collect at least 20 bananas and reach the goal","Points":10,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":20,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
145:{"title":"Frozen Yogurt","LevelName":"SOFT CREAM","ID1":ExpertIDs[71]["id"],"ID2":World8IDs[3]["id"],"description":"Reach the goal without pressing any switch","Points":5,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":Paused,"Comp2":"="},
146:{"title":"Conservation Of Potassium","LevelName":"MOMENTUM","ID1":ExpertIDs[72]["id"],"ID2":World8IDs[4]["id"],"description":"Reach the goal without collecting any bananas","Points":5,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":0,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
147:{"title":"Earbuds In Your Pocket","LevelName":"ENTANGLED PATH","ID1":ExpertIDs[73]["id"],"ID2":World8IDs[6]["id"],"description":"Enter the green warp goal","Points":10,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":Green,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
148:{"title":"Tater Totters","LevelName":"TOTTERS","ID1":ExpertIDs[74]["id"],"ID2":World8IDs[7]["id"],"description":"Collect all bananas and reach the goal","Points":5,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":Yes,"Speed":NULL,"Comp2":"NULL"},
149:{"title":"Shafted","LevelName":"SWING SHAFT","ID1":ExpertIDs[78]["id"],"ID2":World8IDs[15]["id"],"description":"Reach the goal in 10 seconds or less","Points":5,"TotalSec":60,"SpeedrunSec":10,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
150:{"title":"Serial Killer","LevelName":"SERIAL JUMP","ID1":ExpertIDs[79]["id"],"ID2":World9IDs[1]["id"],"description":"Collect all banana bunches and reach the goal","Points":25,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":4,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
151:{"title":"Bunker Down","LevelName":"SHELTER","ID1":ExpertIDs[80]["id"],"ID2":ExpertIDs[80]["id"],"description":"Collect all bananas","Points":5,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":Yes,"Speed":NULL,"Comp2":"NULL"},
152:{"title":"Google En Passant","LevelName":"CHECKER","ID1":ExpertIDs[81]["id"],"ID2":World10IDs[19]["id"],"description":"Enter the red warp goal in 2 seconds or less","Points":5,"TotalSec":60,"SpeedrunSec":2,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":Red,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
153:{"title":"Red Carpet Premiere","LevelName":"CARPET","ID1":ExpertIDs[82]["id"],"ID2":World10IDs[5]["id"],"description":"Reach the goal in 10 seconds or less","Points":5,"TotalSec":60,"SpeedrunSec":10,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
154:{"title":"Sonic's Best Friend","LevelName":"RINGS","ID1":ExpertIDs[85]["id"],"ID2":World10IDs[10]["id"],"description":"Enter the green warp goal in 10 seconds or less","Points":10,"TotalSec":30,"SpeedrunSec":10,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":Green,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
155:{"title":"Unlucky Charms","LevelName":"CLOVER","ID1":ExpertIDs[87]["id"],"ID2":World10IDs[14]["id"],"description":"Reach the goal without collecting any bananas","Points":25,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":0,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
156:{"title":"Cold Brew","LevelName":"COFFEE CUP","ID1":ExpertIDs[88]["id"],"ID2":World10IDs[16]["id"],"description":"Collect all bananas and reach the goal","Points":10,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":Yes,"Speed":NULL,"Comp2":"NULL"},
157:{"title":"#MobiusSweep","LevelName":"MOBIUS","ID1":ExpertIDs[90]["id"],"ID2":ExpertIDs[90]["id"],"description":"Collect all bananas","Points":10,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":Yes,"Speed":NULL,"Comp2":"NULL"},
158:{"title":"Feeling Cross","LevelName":"CROSS FLOORS","ID1":ExpertIDs[91]["id"],"ID2":World9IDs[3]["id"],"description":"Reach the goal without collecting any bananas","Points":10,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":0,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
159:{"title":"No OSHA Compliance","LevelName":"SPINNING SAW","ID1":ExpertIDs[92]["id"],"ID2":World9IDs[4]["id"],"description":"Collect all bananas and reach the goal","Points":5,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":Yes,"Speed":NULL,"Comp2":"NULL"},
160:{"title":"Chip Skip","LevelName":"CHIPPED PIPES","ID1":ExpertIDs[93]["id"],"ID2":World9IDs[6]["id"],"description":"Reach the goal in 6 seconds or less","Points":4,"TotalSec":60,"SpeedrunSec":6,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
161:{"title":"Maze Master","LevelName":"FLAT MAZE","ID1":ExpertIDs[94]["id"],"ID2":World9IDs[7]["id"],"description":"Collect all bananas and reach the goal in 40 seconds or less","Points":5,"TotalSec":60,"SpeedrunSec":40,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":Yes,"Speed":NULL,"Comp2":"NULL"},
162:{"title":"Satellite Bananas","LevelName":"ORBITERS","ID1":ExpertIDs[97]["id"],"ID2":World9IDs[13]["id"],"description":"Collect all bananas and reach the goal","Points":5,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":Yes,"Speed":NULL,"Comp2":"NULL"},
163:{"title":"Spine Transfer","LevelName":"TWIN BASIN","ID1":ExpertIDs[98]["id"],"ID2":World9IDs[15]["id"],"description":"Reach the goal in 8 seconds or less","Points":2,"TotalSec":60,"SpeedrunSec":8,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
164:{"title":"Typographic Explorer","LevelName":"ASTERISK","ID1":ExpertIDs[100]["id"],"ID2":ExpertIDs[100]["id"],"description":"Collect all bananas and reach the goal","Points":5,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":Yes,"Speed":NULL,"Comp2":"NULL"},
165:{"title":"Speedrun Strata","LevelName":"STRATA","ID1":ExpertExtraIDs[2]["id"],"ID2":ExpertExtraIDs[2]["id"],"description":"Enter the green warp goal in 8 seconds or less","Points":5,"TotalSec":60,"SpeedrunSec":8,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":Green,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
166:{"title":"Cotton Banana Joe","LevelName":"SQUARE DANCE","ID1":ExpertExtraIDs[3]["id"],"ID2":ExpertExtraIDs[3]["id"],"description":"Collect all bananas and reach the goal","Points":10,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":Yes,"Speed":NULL,"Comp2":"NULL"},
167:{"title":"5 In 10","LevelName":"5 DRUMS","ID1":ExpertExtraIDs[5]["id"],"ID2":ExpertExtraIDs[5]["id"],"description":"Reach the goal in 10 seconds or less","Points":5,"TotalSec":60,"SpeedrunSec":10,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
168:{"title":"Newton's Cradle","LevelName":"PENDULUMS","ID1":ExpertExtraIDs[7]["id"],"ID2":ExpertExtraIDs[7]["id"],"description":"Reach the goal with the fast forward switch on","Points":5,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":FastForward,"Comp2":"="},
169:{"title":"Runaway Ferris Wheel","LevelName":"FERRIS WHEEL","ID1":ExpertExtraIDs[14]["id"],"ID2":ExpertExtraIDs[14]["id"],"description":"Reach the goal in 4 seconds or less","Points":4,"TotalSec":30,"SpeedrunSec":4,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
170:{"title":"BASED Jumping","LevelName":"FACTORY","ID1":ExpertExtraIDs[15]["id"],"ID2":ExpertExtraIDs[15]["id"],"description":"Collect the banana bunch and reach the goal","Points":3,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":1,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
171:{"title":"Pipeless Path","LevelName":"CURL PIPE","ID1":ExpertExtraIDs[16]["id"],"ID2":ExpertExtraIDs[16]["id"],"description":"Reach the goal in 5 seconds or less","Points":5,"TotalSec":30,"SpeedrunSec":5,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
172:{"title":"Hand It To 'Em","LevelName":"MAGIC HAND","ID1":ExpertExtraIDs[17]["id"],"ID2":ExpertExtraIDs[17]["id"],"description":"Collect all bananas and reach the goal in 4 seconds or less","Points":5,"TotalSec":30,"SpeedrunSec":4,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":Yes,"Speed":NULL,"Comp2":"NULL"},
173:{"title":"Spin Cycle","LevelName":"CENTRIFUGAL","ID1":MasterIDs[1]["id"],"ID2":MasterIDs[1]["id"],"description":"Reach the goal in 6 seconds or less","Points":5,"TotalSec":60,"SpeedrunSec":6,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
174:{"title":"Swing It Back","LevelName":"SWING BRIDGES","ID1":MasterIDs[2]["id"],"ID2":MasterIDs[2]["id"],"description":"Enter the green warp goal","Points":10,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":Green,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
175:{"title":"Circus Act","LevelName":"CYLINDERS","ID1":MasterIDs[3]["id"],"ID2":MasterIDs[3]["id"],"description":"Collect all bananas and reach the goal","Points":10,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":Yes,"Speed":NULL,"Comp2":"NULL"},
176:{"title":"Warping The Even Cooler Way","LevelName":"PASSAGE","ID1":MasterIDs[4]["id"],"ID2":MasterIDs[4]["id"],"description":"Enter the green warp goal in 10 seconds or less","Points":5,"TotalSec":60,"SpeedrunSec":10,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":Green,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
177:{"title":"Impatience","LevelName":"NOTCH","ID1":MasterIDs[5]["id"],"ID2":MasterIDs[5]["id"],"description":"Reach the goal in 15 seconds or less","Points":10,"TotalSec":60,"SpeedrunSec":15,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
178:{"title":"Torus Trouncing","LevelName":"LONG TORUS","ID1":MasterIDs[7]["id"],"ID2":MasterIDs[7]["id"],"description":"Reach the goal in 12 seconds or less","Points":10,"TotalSec":60,"SpeedrunSec":12,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
179:{"title":"Two For One Deal","LevelName":"DOUBLE TWIN","ID1":MasterIDs[9]["id"],"ID2":MasterIDs[9]["id"],"description":"Reach the goal in 12 seconds or less","Points":5,"TotalSec":60,"SpeedrunSec":12,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
180:{"title":"Time Travel","LevelName":"CLOCK FACE","ID1":MasterIDs[10]["id"],"ID2":MasterIDs[10]["id"],"description":"Collect the banana bunch and reach the goal","Points":4,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":1,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
181:{"title":"Master Fan","LevelName":"FAN MASTER","ID1":MasterIDs[12]["id"],"ID2":MasterIDs[12]["id"],"description":"Reach the goal in 4 seconds or less","Points":5,"TotalSec":60,"SpeedrunSec":4,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
182:{"title":"Not Enough Stamina","LevelName":"STAMINA MASTER","ID1":MasterIDs[13]["id"],"ID2":MasterIDs[13]["id"],"description":"Reach the goal in 7 seconds or less","Points":5,"TotalSec":60,"SpeedrunSec":7,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
183:{"title":"Spring-Loaded Barrier","LevelName":"SPRING MASTER","ID1":MasterIDs[14]["id"],"ID2":MasterIDs[14]["id"],"description":"Reach the goal in 10 seconds or less","Points":5,"TotalSec":60,"SpeedrunSec":10,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
184:{"title":"Polygonal Prowess","LevelName":"ROLL MASTER","ID1":MasterIDs[16]["id"],"ID2":MasterIDs[16]["id"],"description":"Reach the goal in 3 seconds or less","Points":2,"TotalSec":60,"SpeedrunSec":3,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
185:{"title":"Touhou Mode","LevelName":"DODGE MASTER","ID1":MasterIDs[18]["id"],"ID2":MasterIDs[18]["id"],"description":"Reach the goal in 5 seconds or less","Points":10,"TotalSec":60,"SpeedrunSec":5,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
186:{"title":"Golden Gap Bridge","LevelName":"BRIDGE MASTER","ID1":MasterIDs[19]["id"],"ID2":MasterIDs[19]["id"],"description":"Reach the goal in 10 seconds or less","Points":10,"TotalSec":60,"SpeedrunSec":10,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
187:{"title":"Monkey Strikers Charged","LevelName":"STRIKER","ID1":MasterExtraIDs[2]["id"],"ID2":MasterExtraIDs[2]["id"],"description":"Reach the goal in 7 seconds or less","Points":10,"TotalSec":60,"SpeedrunSec":7,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
188:{"title":"Out-Of-Place Bananas","LevelName":"OOPARTS","ID1":MasterExtraIDs[3]["id"],"ID2":MasterExtraIDs[3]["id"],"description":"Reach the goal in 8 seconds or less without collecting any bananas","Points":3,"TotalSec":60,"SpeedrunSec":8,"Comp1":"<","BananaQty":0,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
189:{"title":"Voyager 3","LevelName":"PLANETS","ID1":MasterExtraIDs[4]["id"],"ID2":MasterExtraIDs[4]["id"],"description":"Enter the red warp goal in 10 seconds or less","Points":5,"TotalSec":60,"SpeedrunSec":10,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":Red,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
190:{"title":"A Trip To Switzerland","LevelName":"SLICED CHEESE","ID1":MasterExtraIDs[5]["id"],"ID2":MasterExtraIDs[5]["id"],"description":"Reach the goal in 8 seconds or less","Points":5,"TotalSec":60,"SpeedrunSec":8,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
191:{"title":"Ribonucleic Awesome","LevelName":"HELIX","ID1":MasterExtraIDs[8]["id"],"ID2":MasterExtraIDs[8]["id"],"description":"Enter the green warp goal in 10 seconds or less","Points":10,"TotalSec":60,"SpeedrunSec":10,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":Green,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
192:{"title":"Ultimate Lucky Monkey","LevelName":"DIZZY SYSTEM","ID1":MasterExtraIDs[9]["id"],"ID2":MasterExtraIDs[9]["id"],"description":"Reach the goal in 6 seconds or less","Points":4,"TotalSec":60,"SpeedrunSec":6,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
193:{"title":"Snake Eye","LevelName":"DESTINY","ID1":MasterExtraIDs[10]["id"],"ID2":MasterExtraIDs[10]["id"],"description":"Reach the goal in 30 seconds or less","Points":3,"TotalSec":60,"SpeedrunSec":30,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
194:{"title":"Workout Session","LevelName":"TRAINING","ID1":World10IDs[1]["id"],"ID2":World10IDs[1]["id"],"description":"Collect all bananas and reach the goal","Points":25,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":Yes,"Speed":NULL,"Comp2":"NULL"},
195:{"title":"Gotta Gimmick Fast","LevelName":"GIMMICK","ID1":World10IDs[3]["id"],"ID2":World10IDs[3]["id"],"description":"Collect all bananas and reach the goal","Points":5,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":Yes,"Speed":NULL,"Comp2":"NULL"},
196:{"title":"Descending Denali","LevelName":"MOUNTAIN","ID1":World10IDs[4]["id"],"ID2":World10IDs[4]["id"],"description":"Reach the goal in 4.5 seconds or less","Points":5,"TotalSec":60,"SpeedrunSec":4.5,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
197:{"title":"Disorderly Conduct","LevelName":"DISORDER","ID1":World10IDs[6]["id"],"ID2":World10IDs[6]["id"],"description":"Reach the goal in 6 seconds or less","Points":3,"TotalSec":60,"SpeedrunSec":6,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
198:{"title":"A-Maze-Ment","LevelName":"3D MAZE","ID1":World10IDs[7]["id"],"ID2":World10IDs[7]["id"],"description":"Reach the goal in 11 seconds or less","Points":10,"TotalSec":60,"SpeedrunSec":11,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
199:{"title":"Skip Of Scrotum Eatery","LevelName":"CRAZY MAZE","ID1":World10IDs[9]["id"],"ID2":World10IDs[9]["id"],"description":"Reach the goal in 25 seconds or less","Points":25,"TotalSec":60,"SpeedrunSec":25,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
200:{"title":"The Art Of Climbing","LevelName":"POSTMODERN","ID1":World10IDs[11]["id"],"ID2":World10IDs[11]["id"],"description":"Reach the goal in 30 seconds or less","Points":10,"TotalSec":60,"SpeedrunSec":30,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
201:{"title":"Wii Like To Eat","LevelName":"REVOLUTION","ID1":World10IDs[13]["id"],"ID2":World10IDs[13]["id"],"description":"Collect all bananas and reach the goal","Points":10,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":Yes,"Speed":NULL,"Comp2":"NULL"},
202:{"title":"Learning How To Spell","LevelName":"INVISIBLE","ID1":World10IDs[15]["id"],"ID2":World10IDs[15]["id"],"description":"Reach the goal in 30 seconds or less","Points":5,"TotalSec":60,"SpeedrunSec":30,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
203:{"title":"Vision Amusement","LevelName":"CREATED BY","ID1":World10IDs[17]["id"],"ID2":World10IDs[17]["id"],"description":"Reach the goal without pressing the switch","Points":2,"TotalSec":NULL,"SpeedrunSec":NULL,"Comp1":"NULL","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":Paused,"Comp2":"="},
204:{"title":"Alaskan Bull Worm","LevelName":"TRAIN WORM","ID1":ExpertExtraIDs[10]["id"],"ID2":ExpertExtraIDs[10]["id"],"description":"Reach the goal in 7 seconds or less","Points":2,"TotalSec":60,"SpeedrunSec":7,"Comp1":"<","BananaQty":NULL,"BananaBunch":NULL,"goal":NULL,"AllBananas":NULL,"Speed":NULL,"Comp2":"NULL"},
}



function ChallengeBaseLogic(){
    return MenuProgressCheck() && InGame && NumberOfPlayers == 0 && Replay == 0 && MainMode == MainGame
}

function ResetIfDeathOrLevelChange(){
    return never(LevelID != prev(LevelID) || Timer == 0 || (TimeStopped == 1 && CompletedStage == 0) || NotInGame)
}

function HitLevelStart(ID){
    return once(MenuProgressCheck() &&
        LevelID == ID &&
        InGame &&
        Timer < prev(Timer) &&
        TimeStopped == 0 &&
        prev(TimeStopped) == 1 &&
        Replay == 0 &&
        NumberOfPlayers == 0)
}

function CompletedStage(){
    return
    CompletedStage == 1 &&
    prev(CompletedStage) == 0
}

function LevelSpeedrun(timeSeconds, comparison){
    time = timeSeconds * 60
    if(comparison == "<"){
    return
    (Timer >= time)
    }
    if(comparison == ">"){
    return
    (Timer < time)
    }
    if(comparison == "="){
    return
    (Timer == time)
    }
}
CurrentBananas = word(0x00540018)

function BananaBunches(count){
return
    trigger_when(tally(count, Score == prev(Score) + 1000))
}

BananasRemaining = word(0x0052f5d4)
function AllBananas(){
    return
    trigger_when(BananasRemaining == 0)
}


function WarpGoal(color){
    return
    trigger_when(WarpGoal == color)
}

function LevelCheck(LevelID1, LevelID2){
    return
    LevelID == LevelID1 || LevelID == LevelID2
}

Score = word(0x0054001c)
function BananaHitCount(count){
logic = []
for x in range(1,10){
    array_push(logic, Score == prev(Score) + 1000)
}
array_push(logic, Score == prev(Score) + 100)

return tally(count, logic)
}

SwitchSpeed = dword(dword(0x004c3240) + 0xd0) 
function SwitchSpeed(speed, comparison){
    if(comparison == "<"){
    return
    (SwitchSpeed >= speed)
    }
    if(comparison == ">"){
    return
    (SwitchSpeed <= speed)
    }
    if(comparison == "="){
    return
    (SwitchSpeed == speed)
    }
    if(comparison == "!="){
    return
    (SwitchSpeed != speed)
    }
}

function ChallengeMaking(level){
    logic = always_true()
    
    logic = logic && ChallengeBaseLogic() && LevelCheck(level["ID1"], level["ID2"]) && trigger_when(CompletedStage())
    
    if(level["SpeedrunSec"] != NULL){
        logic = logic && LevelSpeedrun(level["TotalSec"] - level["SpeedrunSec"], level["Comp1"])
    }
    
    if(level["BananaBunch"] != NULL){
        logic = logic && BananaBunches(level["BananaBunch"]) && ResetIfDeathOrLevelChange()
    }
    
    if(level["AllBananas"] != NULL){
        logic = logic && AllBananas()
    }
    
    if(level["BananaQty"] != NULL){
        if(level["BananaQty"] == 0){
            logic = logic && disable_when(BananaHitCount(1), LevelID != prev(LevelID) || Timer == 0 || (TimeStopped == 1 && CompletedStage == 0) || NotInGame)
        }else{
            logic = logic && trigger_when(BananaHitCount(level["BananaQty"])) && ResetIfDeathOrLevelChange()
        }
        
    }
    
    if(level["goal"] != NULL){
        logic = logic && WarpGoal(level["goal"])
    }
    
    if(level["Speed"] != NULL){
        logic = logic && SwitchSpeed(level["Speed"], level["Comp2"])
    }
    
    return logic
}

for level in LevelChallenges{
    achievement(
        title = LevelChallenges[level]["title"],
        description = "[Main Game] " + LevelChallenges[level]["LevelName"] + ": " + LevelChallenges[level]["description"],
        points = LevelChallenges[level]["Points"],
        trigger = 
        ChallengeMaking(LevelChallenges[level])
    )
}

function SpecialChallenge(title, description, id1, id2, logic, points){
logicTemp = logic && LevelCheck(id1,id2) && ChallengeBaseLogic()
    achievement(
        title, "[Main Game] " + description, points, logicTemp
    )
}
CoordinateX = float(0x005400a0)
CoordinateY = float(0x005400a4)
CoordinateZ = float(0x005400a8)

HUDPointer = dword(0x0052e208)
MPHOnes = low4(HUDPointer + 0xB32)
MPHTens = low4(HUDPointer + 0xB31)
MPHHundreds = low4(HUDPointer + 0xB30)

SFXID = byte(0x005b5038)
WormHole = 0x05
StrongBounce = 0x64
BumperHit = 0x5c

GamePaused = bit3(0x004c2f00)

LeftAnalogAxis = word(0x004cf71c)

function ResetWhenZero(){
    return disable_when(MPHOnes + MPHTens * 10 + MPHHundreds * 100 == 0, LevelID != prev(LevelID) || Timer == 0 || (TimeStopped == 1 && CompletedStage == 0) || NotInGame) && trigger_when(CompletedStage())
}

function NoWormhole(){
    return disable_when(SFXID == WormHole && prev(SFXID) != WormHole, LevelID != prev(LevelID) || Timer == 0 || (TimeStopped == 1 && CompletedStage == 0) || NotInGame) && trigger_when(CompletedStage())
}

function BumpersHit(hit){
    return
        tally(hit, SFXID == BumperHit && prev(SFXID) != BumperHit)

}


//Fallouts
SpecialChallenge("Stop Doing That!!!", "PLAIN: Fall out", BeginnerIDs[1]["id"],BeginnerIDs[1]["id"], 
ChallengeBaseLogic() && trigger_when(TimeStopped == 1 && CompletedStage == 0 && Timer != 60*60 && Timer != 0), 
3)
SpecialChallenge("Math Dropout", "PARABALOID: Fall out",AdvancedIDs[60]["id"],AdvancedIDs[60]["id"], ChallengeBaseLogic() && trigger_when(TimeStopped == 1 && CompletedStage == 0 && Timer != 60*60 && Timer != 0), 5)
//Touch
SpecialChallenge("Meet My Best Friend", "VEER FIELD: Touch the fish :)",BeginnerIDs[36]["id"],World3IDs[3]["id"], ChallengeBaseLogic() && CoordinateX < -174.0 && CoordinateZ < -271.0 && CoordinateY > -20.0, 2)
//Speed
SpecialChallenge("Monkey Gear Solid: Substance", "INVASION: Reach the goal without your speed dropping to 0",ExpertIDs[23]["id"],World7IDs[12]["id"], ChallengeBaseLogic() && ResetWhenZero(), 4)
SpecialChallenge("Curve Curse", "CURVATURE: Reach the goal without your speed dropping to 0",ExpertIDs[61]["id"],World9IDs[5]["id"], ChallengeBaseLogic() && ResetWhenZero(), 5)
//No Wormhole
SpecialChallenge("Road Work Ahead", "DETOUR: Enter the warp goal without entering the wormhole",ExpertIDs[37]["id"],World6IDs[13]["id"], ChallengeBaseLogic() && NoWormhole(), 5)
SpecialChallenge("Wormless", "WORMHOLE: Reach the goal without entering the wormhole",ExpertIDs[11]["id"],World5IDs[1]["id"], NoWormhole(), 5)
//Misc
SpecialChallenge("Demise Of The Dominoes", "DOMINO: Witness the downfall of domino society and live",ExpertIDs[53]["id"],World7IDs[6]["id"], 
trigger_when(tally(60*32, SwitchSpeed(Play, "="))) && ResetIfDeathOrLevelChange() && unless(GamePaused == 1) && never(CompletedStage()) , 3) 

SpecialChallenge("Exact Timing", "FLOCK: Enter the goal at 16.18 exactly",ExpertIDs[55]["id"],World7IDs[9]["id"], trigger_when(CompletedStage()) && trigger_when(Timer == 0x3cb),2)

SpecialChallenge("Wright Flyer", "PISTONS: Get launched high up and enter the goal after landing",ExpertIDs[59]["id"],World8IDs[1]["id"], 
trigger_when(CompletedStage()) && trigger_when(once(CoordinateY >= 70.0 && prev(CoordinateY) < 70.0)) && ResetIfDeathOrLevelChange(), 4)

SpecialChallenge("AiAi Wins By Doing Absolutely Nothing", "AIR HOCKEY: Have the goal cross you while currently not holding any inputs down",ExpertIDs[99]["id"],World9IDs[17]["id"], 
trigger_when(CompletedStage()) && trigger_when(LeftAnalogAxis== 0) ,2)

SpecialChallenge("Space Jam", "FREE THROW: Enter the red warp goal without bouncing on the ground after getting launched in the air",ExpertExtraIDs[6]["id"],ExpertExtraIDs[6]["id"], 
trigger_when(CompletedStage()) 
&& disable_when(once(CoordinateY >= -100.0 && prev(CoordinateY) < -100.0) && (once( SFXID == StrongBounce && prev(SFXID) != StrongBounce)), 
LevelID != prev(LevelID) || Timer == 0 || (TimeStopped == 1 && CompletedStage == 0) || NotInGame) 
&& WarpGoal(Red)
,10)

SpecialChallenge("Hold Up To Win!", "SYNCHRONIZED: Enter the blue goal with only forward inputs allowed",MasterExtraIDs[7]["id"],MasterExtraIDs[7]["id"], 
trigger_when(CompletedStage()) && WarpGoal(Blue) && disable_when(byte(0x004cf71c) != 0 || (byte(0x004cf71d) <= 110 && byte(0x004cf71d) > 1)
,LevelID != prev(LevelID) || Timer == 0 || (TimeStopped == 1 && CompletedStage == 0) || NotInGame)
, 3)

SpecialChallenge("RUI: Rolling Under Influence", "DORMANT PITS: Collect all bananas and reach the goal with fast forward or fast reverse only",BeginnerIDs[15]["id"],World1IDs[17]["id"],
trigger_when(CompletedStage()) && AllBananas() && disable_when(((SwitchSpeed < FastForward  && Score > prev(Score))) 
,LevelID != prev(LevelID) || Timer == 0 || (TimeStopped == 1 && CompletedStage == 0) || NotInGame
)
 ,5)
 
 SpecialChallenge("Soup Of The Day", "SKELETON: Bounce off the diner and make it to the goal (challenge mode only)",ExpertIDs[7]["id"],ExpertIDs[7]["id"],
 trigger_when(CompletedStage()) && trigger_when(once(CoordinateZ  <= -47.0)) && ResetIfDeathOrLevelChange() 
 ,5)
 
SpecialChallenge("Playing Stupid Games At A Speedier Pace", "SPEEDY JAM: Reach the goal in 15 seconds or less while getting hit by bumpers at least 5 times",ExpertIDs[65]["id"],World9IDs[12]["id"], 
 trigger_when(CompletedStage()) && LevelSpeedrun(30-15, "<") && trigger_when(tally(5, SFXID == BumperHit && prev(SFXID) != BumperHit)) && ResetIfDeathOrLevelChange() 

,5)

SpecialChallenge("Misfire", "PACHINKO: Reach the goal without collecting any bananas or hitting any bumpers",ExpertIDs[40]["id"],ExpertIDs[40]["id"], 
trigger_when(CompletedStage()) &&
disable_when(BananaHitCount(1) || BumpersHit(1), LevelID != prev(LevelID) || Timer == 0 || (TimeStopped == 1 && CompletedStage == 0) || NotInGame),
10)

SpecialChallenge("Warp And Weep", "WARP: Enter the green warp goal without getting hit by a bumper",ExpertIDs[76]["id"],World8IDs[11]["id"], 
trigger_when(CompletedStage()) && WarpGoal(Green) && disable_when(BumpersHit(1),LevelID != prev(LevelID) || Timer == 0 || (TimeStopped == 1 && CompletedStage == 0) || NotInGame)

,4)

function PressedSwitchHell(){
    disable_when(
    (byte(0x00532734) == 3 && prev(byte(0x00532734)) == 1) || (byte(0x00533a54) == 3 && prev(byte(0x00533a54)) == 1) || (byte(0x00534f0c) == 3 && prev(byte(0x00534f0c)) == 1),
    LevelID != prev(LevelID) || Timer == 0 || (TimeStopped == 1 && CompletedStage == 0) || NotInGame
    )
}
SpecialChallenge("Breaking The Law", "SWITCH INFERNO: Reach the goal without pressing any switch",ExpertIDs[38]["id"],World6IDs[15]["id"],
trigger_when(CompletedStage()) && 
(disable_when(byte(0x00532734) == 3 && prev(byte(0x00532734)) != 3,  LevelID != prev(LevelID) || Timer == 0 || (TimeStopped == 1 && CompletedStage == 0) || NotInGame) &&
disable_when(byte(0x00533a54) == 3 && prev(byte(0x00533a54)) != 3,  LevelID != prev(LevelID) || Timer == 0 || (TimeStopped == 1 && CompletedStage == 0) || NotInGame) &&
disable_when(byte(0x00534f0c) == 3 && prev(byte(0x00534f0c)) != 3,  LevelID != prev(LevelID) || Timer == 0 || (TimeStopped == 1 && CompletedStage == 0) || NotInGame))

, 2)
UnlockedMaster = bit0(0x00541310)
UnlockedUltimate = bit0(0x00541332) 



function ChallengeModeMode(mode){
    modeTemp = mode
if (mode == Ultimate){
    modeTemp = mode-1
}
return ((UnlockedMaster == 0 && UnlockedUltimate == 0 && ChallengeModeSelect1 == mode) ||
(UnlockedMaster == 1 && UnlockedUltimate == 0 && ChallengeModeSelect2 == mode) ||
(UnlockedMaster == 1 && UnlockedUltimate == 1 && ChallengeModeSelect3 == mode) ||
(UnlockedMaster == 0 && UnlockedUltimate == 1 && ChallengeModeSelect4 == modeTemp))
}
//Challenge Mode Cheevos
function ChallengeMainLogic(IDStart){

logic = always_true()

logic = logic && InGame &&
     NumberOfPlayers == 0 &&
     MenuProgressCheck() &&
     MainMode == MainGame &&
     (MainGameSelect == ChallengeMode) &&        
        once(LevelID == IDStart && prev(LevelID) != IDStart) && never(NotInGame)

return     
logic
}

function ChallengeMainLogicUltimate(){

logic = always_true()

logic = logic && 
     InGame &&
     NumberOfPlayers == 0 &&
     MenuProgressCheck() &&
     MainMode == MainGame &&
     (MainGameSelect == ChallengeMode) && never(NotInGame) 
     //&& once(UnlockedMaster == 1 && UnlockedUltimate == 1 && ChallengeModeSelect3 == Ultimate) ||
     //once(UnlockedMaster == 0 && UnlockedUltimate == 1 && ChallengeModeSelect4 == Ultimate)
     

return     
logic
}

function ChallengeProgression(IDEnd, name, description, points, IDStart){
    achievement(
        name, description, points,
        trigger = 
        ChallengeMainLogic(IDStart) &&        
        CompletedStage() &&
        LevelID == IDEnd &&
        once(LevelID == IDStart && prev(LevelID) != IDStart) && never(NotInGame)
    )
}   

UsedContinues = word(0x0052f5da)
UltimateContinuesUsed = dword(0x0052f848)



function ChallengeProgressionNoContinues(IDEnd, name, description, points, IDStart){
    achievement(
        name, description, points,
        trigger = 
        ChallengeMainLogic(IDStart) &&
        UsedContinues == 0 &&
        trigger_when(CompletedStage() &&
        LevelID == IDEnd) 
    )
}      

function FinishedUltimate(mode, name, description, points){
    achievement(
        name, description, points,
        trigger =  InGame &&
     NumberOfPlayers == 0 &&
     MenuProgressCheck() &&
     MainMode == MainGame &&
     MainGameSelect == ChallengeMode &&  
        (CompletedStage())   && ChallengeMainLogicUltimate()
        
        &&
        ((LevelID == ExpertIDs[100]["id"] && UltimateContinuesUsed > 0) ||
        (LevelID == ExpertExtraIDs[20]["id"] && UltimateContinuesUsed > 0) ||
        LevelID == MasterExtraIDs[10]["id"])
        
        )
}
currentLives = byte(0x0053ff92)
function ExtraLivesCheck(quantity, start){
    tally(quantity, currentLives == prev(currentLives+1) && once(LevelID == start && prev(LevelID) != start))
}

function LevelCount(count, start){
    disable_when(tally(count,  LevelID != prev(LevelID)), NotInGame || (LevelID == start && prev(LevelID) != start))
}

function ChallengeProgressionShortest(IDEnd, name, description, points, quantity, startingStage){
    achievement(
        name, description, points,
        trigger = 
        ChallengeMainLogic(startingStage) &&
        trigger_when(CompletedStage() &&
        LevelID == IDEnd) 
        &&
        LevelCount(quantity, startingStage)
    )
}      


ChallengeProgression(BeginnerIDs[40]["id"], "Beginner Monkey DX", "[Challenge Mode] Clear Beginner", 5, BeginnerIDs[1]["id"])
ChallengeProgression(AdvancedIDs[70]["id"], "Advanced Monkey DX", "[Challenge Mode] Clear Advanced", 10, AdvancedIDs[1]["id"])
ChallengeProgression(ExpertIDs[100]["id"], "Expert Monkey DX", "[Challenge Mode] Clear Expert", 25, ExpertIDs[1]["id"])
ChallengeProgression(MasterIDs[20]["id"], "Mastering The Monkey", "[Challenge Mode] Clear Master", 25, MasterIDs[1]["id"])


ChallengeProgressionNoContinues( BeginnerExtraIDs[20]["id"], "Notable Monkey DX", "[Challenge Mode] Clear Beginner Extra (No Continues)", 5, BeginnerExtraIDs[1]["id"])
ChallengeProgressionNoContinues( AdvancedExtraIDs[20]["id"], "Skilled Monkey DX", "[Challenge Mode] Clear Advanced Extra (No Continues)", 10, AdvancedExtraIDs[1]["id"])
ChallengeProgressionNoContinues( ExpertExtraIDs[20]["id"], "Top Monkey DX", "[Challenge Mode] Clear Expert Extra (No Continues)", 25, ExpertExtraIDs[1]["id"])
ChallengeProgressionNoContinues(MasterExtraIDs[10]["id"], "Monkey Ball Is Your Destiny!", "[Challenge Mode] Clear Master Extra (No Continues)", 25, MasterExtraIDs[1]["id"])

ChallengeProgressionShortest(BeginnerExtraIDs[20]["id"], "Beginner Speedster", "[Challenge Mode] Clear Beginner and Beginner Extra in the shortest route", 10, 56, BeginnerIDs[1]["id"])
ChallengeProgressionShortest(AdvancedExtraIDs[20]["id"], "Advanced Skipper", "[Challenge Mode] Clear Advanced and Advanced Extra in the shortest route", 25, 76, AdvancedIDs[1]["id"])
ChallengeProgressionShortest(ExpertExtraIDs[20]["id"], "Expert Sprinter", "[Challenge Mode] Clear Expert and Expert Extra in the shortest route", 50,99, ExpertIDs[1]["id"])
ChallengeProgressionShortest(MasterExtraIDs[10]["id"], "Master Speedrunner", "[Challenge Mode] Clear Master and Master Extra in the shortest route", 25, 24, MasterIDs[1]["id"])

FinishedUltimate(Ultimate, "Ultimate Baller", "[Challenge Mode] Clear Ultimate", 50)

achievement("Potassium Power", "[Story Mode] Collect 999 bananas", 10, 
MenuProgressCheck() &&
MainMode == MainGame &&
MainGameSelect == StoryMode &&
CurrentBananas >= 999 && prev(CurrentBananas) < 999
)

achievement(
        "Banana Allergies", "[Story Mode] Clear all worlds with 0 bananas", 25,
        MenuProgressCheck() &&
        MainMode == MainGame &&
        MainGameSelect == StoryMode &&
        CurrentBananas == 0 &&
        trigger_when(prev(LevelID) != 0x00c5 &&
        
        LevelID == 0x00c5)
        )
StoryModeTimeFrames = dword(0x00515c28) 
achievement(
        "Home In Time For Lunch", "[Story Mode] Clear all worlds under 30 minutes in-game time", 25,
        MenuProgressCheck() &&
        MainMode == MainGame &&
        MainGameSelect == StoryMode &&
        trigger_when(prev(LevelID) != 0x00c5 &&
        LevelID == 0x00c5) && StoryModeTimeFrames <= (30*60*60)
        )
achievement(
        "Just Warming Up!", "[Challenge Mode] Clear Master Extra by starting at Expert (No Continues)", 50,
        ChallengeMainLogic(ExpertExtraIDs[1]["id"]) &&
        UsedContinues == 0 &&
        trigger_when(CompletedStage() &&
        LevelID == MasterExtraIDs[10]["id"]) &&
        ((UnlockedMaster == 1 && UnlockedUltimate == 1 && ChallengeModeSelect3 != Ultimate) ||
(UnlockedMaster == 0 && UnlockedUltimate == 1 && ChallengeModeSelect4 != Ultimate))
        )

achievement(    
"Beginner's Banana", "[Challenge Mode] Earn 10 extra lives in Beginner without using a continue", 5, 
     ChallengeMainLogic(BeginnerIDs[1]["id"]) &&
     never(UsedContinues == prev(UsedContinues) + 1) &&
     never(NotInGame) &&
     never(LevelID == AdvancedIDs[1]["id"]) && 
     measured(ExtraLivesCheck(10, BeginnerIDs[1]["id"]))
)

achievement(    
"Advanced Acquisition", "[Challenge Mode] Earn 10 extra lives in Advanced without using a continue", 10, 
     ChallengeMainLogic(AdvancedIDs[1]["id"]) &&
     never(UsedContinues == prev(UsedContinues) + 1) &&
     never(NotInGame) &&
     never(LevelID == ExpertIDs[1]["id"]) &&
     measured(ExtraLivesCheck(10, AdvancedIDs[1]["id"]))
)

achievement(    
"Expert Entrepeneur", "[Challenge Mode] Earn 15 extra lives in Expert without using a continue", 10, 
     ChallengeMainLogic(ExpertIDs[1]["id"]) &&
     never(UsedContinues == prev(UsedContinues) + 1) &&
     never(NotInGame) &&
     never(LevelID == MasterIDs[1]["id"]) && 
     measured(ExtraLivesCheck(15, ExpertIDs[1]["id"]))
)

achievement(    
"Master Muncher", "[Challenge Mode] Earn 3 extra lives in Master without using a continue", 5, 
     ChallengeMainLogic(MasterIDs[1]["id"]) &&
     never(UsedContinues == prev(UsedContinues) + 1) &&
     never(NotInGame) &&
     measured(ExtraLivesCheck(3, MasterIDs[1]["id"]))
)
UltimateBananas = dword(0x0052f850)
achievement(
    "Ultimate Banana Connoisseur", "[Challenge Mode] Clear Ultimate with 4000 bananas collected", 50, 
    ChallengeMainLogicUltimate() &&
    trigger_when(CompletedStage())  && 
    UltimateBananas >= 4000
    &&
    trigger_when((LevelID == ExpertIDs[100]["id"] && UltimateContinuesUsed > 0) ||
    (LevelID == ExpertExtraIDs[20]["id"] && UltimateContinuesUsed > 0) ||
    LevelID == MasterExtraIDs[10]["id"])
        
)
UltimateContinuesUsed = dword(0x0052f848)
achievement(
    title = "Daro's Certificate Of Monkey Mastery",
    description = "[Challenge Mode] Clear Ultimate with no warps and no continues in a single session",
  points = 100,
    trigger = ChallengeMainLogicUltimate() &&
    UltimateContinuesUsed == 0 &&
    once(LevelID == BeginnerIDs[1]["id"] && prev(LevelID) != BeginnerIDs[1]["id"]) &&
    never(NotInGame) &&
    never(WarpGoal != 0) &&
    trigger_when(CompletedStage() && LevelID == MasterExtraIDs[10]["id"])
    
)