// ~Hack~ Pokemon Radical Red
// #ID = 17361

items={
1:{"bit":5, "location":"Viridian City","address":0x02e445},
2:{"bit":0, "location":"Viridian City","address":0x043182},
3:{"bit":0, "location":"Pewter City","address":0x02e497},
4:{"bit":1, "location":"Cerulean City","address":0x43182},
5:{"bit":1, "location":"Cerulean City","address":0x2e48f},
6:{"bit":0, "location":"Vermilion City","address":0x02e48f},
7:{"bit":1, "location":"Celadon City","address":0x02e446},
8:{"bit":7, "location":"Celadon City","address":0x02e48e},
10:{"bit":5, "location":"Fuchsia City","address":0x02e499},
11:{"bit":1, "location":"Fuchsia City","address":0x02e443},
12:{"bit":7, "location":"Viridian Forest","address":0x2e436},
13:{"bit":0, "location":"Viridian Forest","address":0x2e437},
14:{"bit":1, "location":"Viridian Forest","address":0x2e489},
15:{"bit":6, "location":"Viridian Forest","address":0x2e443},
16:{"bit":0, "location":"Viridian Forest","address":0x2e489},
17:{"bit":4, "location":"Viridian Forest","address":0x43182},
18:{"bit":1, "location":"Viridian Forest","address":0x04317b},
19:{"bit":4, "location":"Viridian Forest","address":0x043187},
20:{"bit":2, "location":"Mt. Moon","address":0x2e437},
21:{"bit":1, "location":"Mt. Moon","address":0x2e437},
22:{"bit":3, "location":"Mt. Moon","address":0x2e437},
23:{"bit":4, "location":"Mt. Moon","address":0x2e437},
24:{"bit":5, "location":"Mt. Moon","address":0x2e437},
25:{"bit":6, "location":"Mt. Moon","address":0x2e437},
26:{"bit":7, "location":"Mt. Moon","address":0x2e437},
27:{"bit":5, "location":"Mt. Moon","address":0x04317f},
28:{"bit":3, "location":"Mt. Moon","address":0x02e489},
29:{"bit":7, "location":"Mt. Moon","address":0x2e443},
30:{"bit":5, "location":"Mt. Moon","address":0x4325a},
31:{"bit":2, "location":"Mt. Moon","address":0x2e489},
32:{"bit":0, "location":"Mt. Moon","address":0x2e444},
33:{"bit":2, "location":"Route 3","address":0x4317f},
34:{"bit":2, "location":"Route 3","address":0x4325b},
35:{"bit":2, "location":"Route 4","address":0x2e497},
36:{"bit":6, "location":"Route 4","address":0x4325a},
37:{"bit":7, "location":"Route 4","address":0x4325a},
38:{"bit":4, "location":"Route 4","address":0x2e49c},
39:{"bit":1, "location":"Route 4","address":0x2e438},
40:{"bit":2, "location":"Route 24","address":0x2e438},
41:{"bit":7, "location":"Route 24","address":0x4317a},
42:{"bit":4, "location":"Route 24","address":0x02e442},
43:{"bit":0, "location":"Route 25","address":0x4325b},
44:{"bit":3, "location":"Route 25","address":0x2e438},
45:{"bit":5, "location":"Route 25","address":0x2e497},
46:{"bit":4, "location":"Route 25","address":0x2e497},
47:{"bit":5, "location":"Route 25","address":0x2e489},
48:{"bit":4, "location":"Route 25","address":0x2e489},
49:{"bit":0, "location":"Route 5","address":0x43180},
50:{"bit":7, "location":"Route 6","address":0x2e497},
51:{"bit":6, "location":"Route 6","address":0x2e497},
52:{"bit":7, "location":"Route 6","address":0x4317f},
53:{"bit":4, "location":"Route 6","address":0x043186},
54:{"bit":2, "location":"Route 11","address":0x43254},
55:{"bit":1, "location":"Route 11","address":0x4325b},
56:{"bit":1, "location":"Route 11","address":0x43254},
57:{"bit":1, "location":"Route 11","address":0x2e48e},
58:{"bit":0, "location":"S.S. Anne","address":0x2e48a},
59:{"bit":7, "location":"S.S. Anne","address":0x2e438},
60:{"bit":0, "location":"S.S. Anne","address":0x2e439},
61:{"bit":1, "location":"S.S. Anne","address":0x2e439},
62:{"bit":0, "location":"S.S. Anne","address":0x43254},
63:{"bit":2, "location":"S.S. Anne","address":0x2e439},
64:{"bit":2, "location":"S.S. Anne","address":0x2e498},
65:{"bit":1, "location":"S.S. Anne","address":0x2e498},
66:{"bit":0, "location":"S.S. Anne","address":0x2e498},
67:{"bit":5, "location":"S.S. Anne","address":0x2e438},
68:{"bit":7, "location":"S.S. Anne","address":0x43187},
69:{"bit":6, "location":"Route 2","address":0x04317a},
70:{"bit":4, "location":"Route 2","address":0x04317b},
71:{"bit":0, "location":"Diglett's Cave","address":0x2e438},
72:{"bit":7, "location":"Diglett's Cave","address":0x43254},
73:{"bit":3, "location":"Route 9","address":0x2e439},
74:{"bit":2, "location":"Route 9","address":0x2e444},
75:{"bit":6, "location":"Route 9","address":0x2e489},
76:{"bit":6, "location":"Route 9","address":0x2e49b},
77:{"bit":3, "location":"Route 9","address":0x2e498},
78:{"bit":5, "location":"Route 10","address":0x2e498},
79:{"bit":6, "location":"Route 10","address":0x2e498},
80:{"bit":1, "location":"Route 10","address":0x2e48a},
81:{"bit":4, "location":"Route 10","address":0x4317f},
82:{"bit":7, "location":"Route 10","address":0x2e49b},
83:{"bit":0, "location":"Route 10","address":0x043185},
84:{"bit":2, "location":"Route 10","address":0x02e48a},
85:{"bit":3, "location":"Rock Tunnel","address":0x2e444},
86:{"bit":6, "location":"Rock Tunnel","address":0x2e444},
87:{"bit":5, "location":"Rock Tunnel","address":0x2e444},
88:{"bit":3, "location":"Rock Tunnel","address":0x04317b},
89:{"bit":7, "location":"Rock Tunnel","address":0x2e444},
90:{"bit":4, "location":"Rock Tunnel","address":0x2e444},
91:{"bit":4, "location":"Rock Tunnel","address":0x043257},
92:{"bit":3, "location":"Rock Tunnel","address":0x043257},
93:{"bit":7, "location":"Route 8","address":0x2e444},
94:{"bit":0, "location":"Route 8","address":0x2e499},
95:{"bit":1, "location":"Route 8","address":0x2e499},
96:{"bit":1, "location":"Route 8","address":0x4325a},
98:{"bit":0, "location":"Route 7","address":0x2e49c},
99:{"bit":7, "location":"Route 7","address":0x43255},
100:{"bit":4, "location":"Rocket Hideout","address":0x2e439},
101:{"bit":3, "location":"Rocket Hideout","address":0x2e48a},
102:{"bit":3, "location":"Rocket Hideout","address":0x2e43a},
103:{"bit":4, "location":"Rocket Hideout","address":0x2e48a},
104:{"bit":2, "location":"Rocket Hideout","address":0x2e43a},
105:{"bit":2, "location":"Rocket Hideout","address":0x2e446},
106:{"bit":5, "location":"Rocket Hideout","address":0x2e43a},
107:{"bit":4, "location":"Rocket Hideout","address":0x2e43a},
108:{"bit":5, "location":"Rocket Hideout","address":0x2e460},
109:{"bit":6, "location":"Rocket Hideout","address":0x2e439},
110:{"bit":7, "location":"Rocket Hideout","address":0x2e439},
111:{"bit":0, "location":"Rocket Hideout","address":0x2e43a},
112:{"bit":1, "location":"Rocket Hideout","address":0x2e43a},
113:{"bit":5, "location":"Rocket Hideout","address":0x2e439},
114:{"bit":6, "location":"Rocket Hideout","address":0x2e43a},
115:{"bit":6, "location":"Rocket Hideout","address":0x2e499},
116:{"bit":5, "location":"Rocket Hideout","address":0x2e48a},
117:{"bit":7, "location":"Pokemon Tower","address":0x2e43a},
118:{"bit":0, "location":"Pokemon Tower","address":0x2e43b},
119:{"bit":1, "location":"Pokemon Tower","address":0x2e43b},
120:{"bit":2, "location":"Pokemon Tower","address":0x2e43b},
121:{"bit":0, "location":"Pokemon Tower","address":0x2e446},
122:{"bit":6, "location":"Pokemon Tower","address":0x2e48a},
123:{"bit":3, "location":"Pokemon Tower","address":0x2e43b},
124:{"bit":5, "location":"Pokemon Tower","address":0x2e43b},
125:{"bit":4, "location":"Pokemon Tower","address":0x2e43b},
126:{"bit":0, "location":"Pokemon Tower","address":0x4325a},
127:{"bit":5, "location":"Pokemon Tower","address":0x04325f},
128:{"bit":4, "location":"Pokemon Tower","address":0x04325f},
129:{"bit":1, "location":"Silph Co.","address":0x43185},
130:{"bit":2, "location":"Silph Co.","address":0x2e43e},
131:{"bit":7, "location":"Silph Co.","address":0x2e499},
132:{"bit":0, "location":"Silph Co.","address":0x2e49a},
133:{"bit":4, "location":"Silph Co.","address":0x2e43d},
134:{"bit":1, "location":"Silph Co.","address":0x2e49a},
135:{"bit":6, "location":"Silph Co.","address":0x2e44b},
136:{"bit":7, "location":"Silph Co.","address":0x2e43d},
137:{"bit":5, "location":"Silph Co.","address":0x2e43d},
138:{"bit":6, "location":"Silph Co.","address":0x2e43d},
139:{"bit":2, "location":"Silph Co.","address":0x2e49a},
140:{"bit":0, "location":"Silph Co.","address":0x2e48c},
141:{"bit":0, "location":"Silph Co.","address":0x2e43e},
142:{"bit":1, "location":"Silph Co.","address":0x2e43e},
143:{"bit":3, "location":"Silph Co.","address":0x02e49a},
144:{"bit":3, "location":"Silph Co.","address":0x02e43e},
145:{"bit":4, "location":"Silph Co.","address":0x02e43e},
146:{"bit":4, "location":"Silph Co.","address":0x02e49a},
147:{"bit":6, "location":"Silph Co.","address":0x02e43e},
148:{"bit":5, "location":"Silph Co.","address":0x02e43e},
149:{"bit":0, "location":"Silph Co.","address":0x02e445},
150:{"bit":5, "location":"Silph Co.","address":0x02e49a},
151:{"bit":1, "location":"Silph Co.","address":0x02e48c},
152:{"bit":6, "location":"Silph Co.","address":0x02e49a},
153:{"bit":7, "location":"Silph Co.","address":0x02e49a},
154:{"bit":7, "location":"Silph Co.","address":0x02e43e},
155:{"bit":1, "location":"Silph Co.","address":0x02e43f},
156:{"bit":0, "location":"Silph Co.","address":0x02e43f},
157:{"bit":1, "location":"Silph Co.","address":0x02e445},
158:{"bit":0, "location":"Silph Co.","address":0x02e49b},
159:{"bit":6, "location":"Route 16","address":0x043256},
160:{"bit":2, "location":"Route 17","address":0x043255},
161:{"bit":3, "location":"Route 17","address":0x02e48b},
162:{"bit":4, "location":"Route 17","address":0x02e48b},
163:{"bit":2, "location":"Route 17","address":0x043185},
164:{"bit":2, "location":"Route 17","address":0x02e48b},
165:{"bit":1, "location":"Route 17","address":0x02e48b},
166:{"bit":5, "location":"Route 17","address":0x02e48b},
167:{"bit":3, "location":"Route 18","address":0x04317f},
168:{"bit":6, "location":"Route 12","address":0x02e43b},
169:{"bit":5, "location":"Route 12","address":0x043180},
170:{"bit":7, "location":"Route 12","address":0x02e43b},
171:{"bit":2, "location":"Route 12","address":0x02e499},
172:{"bit":4, "location":"Route 12","address":0x043183},
173:{"bit":7, "location":"Route 13","address":0x02e48a},
174:{"bit":1, "location":"Route 13","address":0x043180},
175:{"bit":5, "location":"Route 14","address":0x02e49c},
176:{"bit":5, "location":"Route 14","address":0x02e49b},
177:{"bit":2, "location":"Route 14","address":0x02e441},
178:{"bit":0, "location":"Route 15","address":0x02e43c},
179:{"bit":5, "location":"Safari Zone","address":0x02e43c},
180:{"bit":4, "location":"Safari Zone","address":0x02e43c},
181:{"bit":2, "location":"Safari Zone","address":0x02e43c},
182:{"bit":3, "location":"Safari Zone","address":0x02e43c},
183:{"bit":6, "location":"Safari Zone","address":0x043255},
184:{"bit":3, "location":"Safari Zone","address":0x02e446},
185:{"bit":7, "location":"Safari Zone","address":0x02e43c},
186:{"bit":6, "location":"Safari Zone","address":0x02e43c},
187:{"bit":1, "location":"Safari Zone","address":0x02e43d},
188:{"bit":0, "location":"Safari Zone","address":0x02e43d},
189:{"bit":7, "location":"Safari Zone","address":0x02e48b},
190:{"bit":2, "location":"Safari Zone","address":0x02e43d},
191:{"bit":5, "location":"Safari Zone","address":0x043255},
192:{"bit":3, "location":"Safari Zone","address":0x02e43d},
193:{"bit":4, "location":"Safari Zone","address":0x043255},
194:{"bit":6, "location":"Safari Zone","address":0x02e48b},
195:{"bit":4, "location":"Seafoam Islands","address":0x02e446},
196:{"bit":6, "location":"Seafoam Islands","address":0x02e446},
197:{"bit":5, "location":"Seafoam Islands","address":0x02e446},
198:{"bit":7, "location":"Seafoam Islands","address":0x02e446},
199:{"bit":5, "location":"Seafoam Islands","address":0x02e48c},
200:{"bit":6, "location":"Seafoam Islands","address":0x02e48c},
201:{"bit":0, "location":"Seafoam Islands","address":0x02e447},
202:{"bit":2, "location":"Seafoam Islands","address":0x04325e},
203:{"bit":0, "location":"Pokemon Mansion","address":0x02e440},
204:{"bit":3, "location":"Pokemon Mansion","address":0x02e445},
205:{"bit":1, "location":"Pokemon Mansion","address":0x02e440},
206:{"bit":2, "location":"Pokemon Mansion","address":0x02e440},
207:{"bit":3, "location":"Pokemon Mansion","address":0x02e440},
208:{"bit":0, "location":"Pokemon Mansion","address":0x02e48d},
209:{"bit":4, "location":"Pokemon Mansion","address":0x02e445},
210:{"bit":7, "location":"Pokemon Mansion","address":0x02e43f},
211:{"bit":5, "location":"Pokemon Mansion","address":0x02e440},
212:{"bit":4, "location":"Pokemon Mansion","address":0x02e440},
213:{"bit":0, "location":"Pokemon Mansion","address":0x02e441},
214:{"bit":7, "location":"Pokemon Mansion","address":0x02e440},
215:{"bit":1, "location":"Route 19","address":0x043255},
216:{"bit":1, "location":"Route 20","address":0x043256},
217:{"bit":5, "location":"Route 20","address":0x04317d},
218:{"bit":6, "location":"Route 21","address":0x04317d},
219:{"bit":3, "location":"Route 22","address":0x043186},
220:{"bit":2, "location":"Cerulean Cave","address":0x043182},
221:{"bit":2, "location":"Cerulean Cave","address":0x02e442},
222:{"bit":5, "location":"Cerulean Cave","address":0x02e442},
223:{"bit":3, "location":"Cerulean Cave","address":0x02e442},
224:{"bit":1, "location":"Cerulean Cave","address":0x02e442},
225:{"bit":3, "location":"Cerulean Cave","address":0x043255},
226:{"bit":7, "location":"Cerulean Cave","address":0x02e442},
227:{"bit":3, "location":"Power Plant","address":0x02e43f},
228:{"bit":6, "location":"Power Plant","address":0x02e43f},
229:{"bit":4, "location":"Power Plant","address":0x02e43f},
230:{"bit":5, "location":"Power Plant","address":0x02e43f},
231:{"bit":3, "location":"Power Plant","address":0x02e48c},
232:{"bit":4, "location":"Power Plant","address":0x02e48c},
233:{"bit":4, "location":"Route 23","address":0x02e49b},
234:{"bit":4, "location":"Route 23","address":0x02e48d},
235:{"bit":3, "location":"Route 23","address":0x02e48d},
236:{"bit":3, "location":"Route 23","address":0x02e49b},
237:{"bit":0, "location":"Route 23","address":0x043255},
238:{"bit":2, "location":"Route 23","address":0x02e48d},
239:{"bit":2, "location":"Route 23","address":0x02e49b},
240:{"bit":1, "location":"Route 23","address":0x02e49b},
241:{"bit":3, "location":"Route 23","address":0x02e49c},
242:{"bit":1, "location":"Victory Road","address":0x02e441},
243:{"bit":5, "location":"Victory Road","address":0x043256},
244:{"bit":6, "location":"Victory Road","address":0x02e48d},
245:{"bit":5, "location":"Victory Road","address":0x02e48d},
246:{"bit":3, "location":"Victory Road","address":0x02e441},
247:{"bit":6, "location":"Victory Road","address":0x02e441},
248:{"bit":5, "location":"Victory Road","address":0x02e441},
249:{"bit":4, "location":"Victory Road","address":0x02e441},
250:{"bit":7, "location":"Victory Road","address":0x02e441},
251:{"bit":0, "location":"Victory Road","address":0x02e442},
252:{"bit":6, "location":"Treasure Beach","address":0x04325f},
253:{"bit":5, "location":"Kindle Road","address":0x02e447},
254:{"bit":4, "location":"Kindle Road","address":0x02e447},
255:{"bit":3, "location":"Kindle Road","address":0x02e447},
256:{"bit":7, "location":"Mt. Ember","address":0x02e449},
257:{"bit":6, "location":"Mt. Ember","address":0x02e49c},
258:{"bit":5, "location":"Mt. Ember","address":0x02e449},
259:{"bit":6, "location":"Mt. Ember","address":0x02e449},
260:{"bit":2, "location":"Two Island","address":0x02e443},
261:{"bit":7, "location":"Cape Brink","address":0x02e496},
262:{"bit":3, "location":"Three Isle Path","address":0x02e49d},
263:{"bit":3, "location":"Three Island","address":0x02e443},
264:{"bit":4, "location":"Three Island","address":0x02e49d},
265:{"bit":5, "location":"Bond Bridge","address":0x02e49d},
266:{"bit":3, "location":"Berry Forest","address":0x02e449},
267:{"bit":4, "location":"Berry Forest","address":0x02e449},
268:{"bit":2, "location":"Berry Forest","address":0x02e449},
269:{"bit":3, "location":"Safari Zone","address":0x04326b},
270:{"bit":1, "location":"Silph Co.","address":0x043268},
271:{"bit":3, "location":"Pokemon Mansion","address":0x04326a},
272:{"bit":4, "location":"Pokemon Mansion","address":0x04326a},
273:{"bit":0, "location":"Power Plant","address":0x04326b},
274:{"bit":2, "location":"Route 13","address":0x04326b},
275:{"bit":1, "location":"Route 3","address":0x02e497},
276:{"bit":2, "location":"Route 12","address":0x02e48e},
277:{"bit":4, "location":"Route 16","address":0x02e499},
278:{"bit":3, "location":"Route 12","address":0x02e499},
279:{"bit":7, "location":"Pokemon Mansion","address":0x02e48c},
280:{"bit":0, "location":"Pokemon Mansion","address":0x02e465},
}

trainers={
1:{"bit":5, "location":"Berry Forest","address":0x2e4b6},
2:{"bit":0, "location":"Berry Forest","address":0x2e4b7},
3:{"bit":6, "location":"Berry Forest","address":0x2e4c1},
4:{"bit":7, "location":"Berry Forest","address":0x2e4c1},
5:{"bit":7, "location":"Bond Bridge","address":0x2e4ec},
6:{"bit":3, "location":"Bond Bridge","address":0x2e4ed},
7:{"bit":6, "location":"Bond Bridge","address":0x2e4f1},
8:{"bit":7, "location":"Bond Bridge","address":0x2e4f1},
9:{"bit":0, "location":"Bond Bridge","address":0x2e4f2},
10:{"bit":1, "location":"Bond Bridge","address":0x2e4f2},
11:{"bit":3, "location":"Cerulean Cave","address":0x2e4b4},
12:{"bit":4, "location":"Cerulean Cave","address":0x2e4b4},
13:{"bit":5, "location":"Cerulean Cave","address":0x2e4b4},
14:{"bit":6, "location":"Cerulean Cave","address":0x2e4b4},
15:{"bit":7, "location":"Cerulean Cave","address":0x2e4b4},
16:{"bit":0, "location":"Cerulean Cave","address":0x2e4b5},
17:{"bit":1, "location":"Cerulean Cave","address":0x2e4b5},
18:{"bit":5, "location":"Cinnabar Island","address":0x2e4b3},
19:{"bit":0, "location":"Indigo Plateau","address":0x2e4af},
20:{"bit":6, "location":"Kindle Road","address":0x2e4ec},
21:{"bit":3, "location":"Kindle Road","address":0x2e4f0},
22:{"bit":4, "location":"Kindle Road","address":0x2e4f0},
23:{"bit":5, "location":"Kindle Road","address":0x2e4f0},
24:{"bit":6, "location":"Kindle Road","address":0x2e4f0},
25:{"bit":7, "location":"Kindle Road","address":0x2e4f0},
26:{"bit":0, "location":"Kindle Road","address":0x2e4f1},
27:{"bit":1, "location":"Kindle Road","address":0x2e4f1},
28:{"bit":2, "location":"Kindle Road","address":0x2e4f1},
29:{"bit":3, "location":"Kindle Road","address":0x2e4f1},
30:{"bit":4, "location":"Kindle Road","address":0x2e4f1},
31:{"bit":5, "location":"Kindle Road","address":0x2e4f1},
32:{"bit":0, "location":"Mt. Ember","address":0x2e4f6},
33:{"bit":3, "location":"Mt. Ember","address":0x2e4f6},
34:{"bit":5, "location":"Mt. Ember","address":0x2e4f6},
35:{"bit":3, "location":"Mt. Moon","address":0x2e4b7},
36:{"bit":4, "location":"Mt. Moon","address":0x2e4b9},
37:{"bit":5, "location":"Mt. Moon","address":0x2e4b9},
38:{"bit":0, "location":"Mt. Moon","address":0x2e4bb},
39:{"bit":1, "location":"Mt. Moon","address":0x2e4bb},
40:{"bit":1, "location":"Mt. Moon","address":0x2e4c1},
41:{"bit":2, "location":"Mt. Moon","address":0x2e4c1},
42:{"bit":5, "location":"Mt. Moon","address":0x2e4c2},
43:{"bit":7, "location":"Mt. Moon","address":0x2e4d7},
44:{"bit":0, "location":"Mt. Moon","address":0x2e4d8},
45:{"bit":1, "location":"Mt. Moon","address":0x2e4d8},
46:{"bit":2, "location":"Mt. Moon","address":0x2e4d8},
47:{"bit":0, "location":"Pokemon Mansion","address":0x2e4c7},
48:{"bit":2, "location":"Pokemon Mansion","address":0x2e4c7},
49:{"bit":3, "location":"Pokemon Mansion","address":0x2e4c7},
50:{"bit":7, "location":"Pokemon Mansion","address":0x2e4d5},
51:{"bit":2, "location":"Pokemon Mansion","address":0x2e4d7},
52:{"bit":3, "location":"Pokemon Mansion","address":0x2e4d7},
53:{"bit":6, "location":"Pokemon Mansion","address":0x2e4ee},
54:{"bit":2, "location":"Pokemon Tower","address":0x2e4b6},
55:{"bit":1, "location":"Pokemon Tower","address":0x2e4ba},
56:{"bit":4, "location":"Pokemon Tower","address":0x2e4bb},
57:{"bit":1, "location":"Pokemon Tower","address":0x2e4da},
58:{"bit":2, "location":"Pokemon Tower","address":0x2e4da},
59:{"bit":3, "location":"Pokemon Tower","address":0x2e4da},
60:{"bit":1, "location":"Pokemon Tower","address":0x2e4e3},
61:{"bit":2, "location":"Pokemon Tower","address":0x2e4e3},
62:{"bit":3, "location":"Pokemon Tower","address":0x2e4e3},
63:{"bit":4, "location":"Pokemon Tower","address":0x2e4e3},
64:{"bit":5, "location":"Pokemon Tower","address":0x2e4e3},
65:{"bit":6, "location":"Pokemon Tower","address":0x2e4e3},
66:{"bit":7, "location":"Pokemon Tower","address":0x2e4e3},
67:{"bit":0, "location":"Pokemon Tower","address":0x2e4e4},
68:{"bit":1, "location":"Pokemon Tower","address":0x2e4e4},
69:{"bit":2, "location":"Pokemon Tower","address":0x2e4e4},
70:{"bit":3, "location":"Pokemon Tower","address":0x2e4e4},
71:{"bit":4, "location":"Pokemon Tower","address":0x2e4e4},
72:{"bit":5, "location":"Pokemon Tower","address":0x2e4e4},
73:{"bit":2, "location":"Power Plant","address":0x2e4b4},
74:{"bit":6, "location":"Rock Tunnel","address":0x2e4bf},
75:{"bit":7, "location":"Rock Tunnel","address":0x2e4bf},
76:{"bit":3, "location":"Route 10","address":0x2e4c0},
77:{"bit":4, "location":"Rock Tunnel","address":0x2e4c0},
78:{"bit":5, "location":"Rock Tunnel","address":0x2e4c0},
79:{"bit":6, "location":"Rock Tunnel","address":0x2e4c0},
80:{"bit":0, "location":"Rock Tunnel","address":0x2e4c1},
81:{"bit":5, "location":"Rock Tunnel","address":0x2e4c3},
82:{"bit":6, "location":"Rock Tunnel","address":0x2e4c3},
83:{"bit":7, "location":"Rock Tunnel","address":0x2e4c3},
84:{"bit":0, "location":"Rock Tunnel","address":0x2e4c4},
85:{"bit":1, "location":"Rock Tunnel","address":0x2e4c4},
86:{"bit":2, "location":"Rock Tunnel","address":0x2e4c4},
87:{"bit":4, "location":"Rocket Hideout","address":0x2e4d7},
88:{"bit":6, "location":"Rocket Hideout","address":0x2e4d8},
89:{"bit":7, "location":"Rocket Hideout","address":0x2e4d8},
90:{"bit":0, "location":"Rocket Hideout","address":0x2e4d9},
91:{"bit":1, "location":"Rocket Hideout","address":0x2e4d9},
92:{"bit":2, "location":"Rocket Hideout","address":0x2e4d9},
93:{"bit":3, "location":"Rocket Hideout","address":0x2e4d9},
94:{"bit":4, "location":"Rocket Hideout","address":0x2e4d9},
95:{"bit":5, "location":"Rocket Hideout","address":0x2e4d9},
96:{"bit":6, "location":"Rocket Hideout","address":0x2e4d9},
97:{"bit":7, "location":"Rocket Hideout","address":0x2e4d9},
98:{"bit":0, "location":"Rocket Hideout","address":0x2e4da},
99:{"bit":4, "location":"Route 14","address":0x2e4c4},
100:{"bit":4, "location":"Route 10","address":0x2e4bf},
101:{"bit":5, "location":"Route 10","address":0x2e4bf},
102:{"bit":2, "location":"Route 10","address":0x2e4c0},
103:{"bit":3, "location":"Route 10","address":0x2e4c3},
104:{"bit":4, "location":"Route 10","address":0x2e4c3},
105:{"bit":1, "location":"Route 11","address":0x2e4b8},
106:{"bit":2, "location":"Route 11","address":0x2e4b8},
107:{"bit":3, "location":"Route 11","address":0x2e4b8},
108:{"bit":4, "location":"Route 11","address":0x2e4b8},
109:{"bit":5, "location":"Route 11","address":0x2e4c7},
110:{"bit":6, "location":"Route 11","address":0x2e4c7},
111:{"bit":2, "location":"Route 11","address":0x2e4cc},
112:{"bit":3, "location":"Route 11","address":0x2e4cc},
113:{"bit":4, "location":"Route 11","address":0x2e4cc},
114:{"bit":5, "location":"Route 11","address":0x2e4cc},
115:{"bit":1, "location":"Route 12","address":0x2e4c8},
116:{"bit":2, "location":"Route 12","address":0x2e4c8},
117:{"bit":3, "location":"Route 12","address":0x2e4c8},
118:{"bit":4, "location":"Route 12","address":0x2e4c8},
119:{"bit":1, "location":"Route 12","address":0x2e4c9},
120:{"bit":5, "location":"Route 12","address":0x2e4cf},
121:{"bit":3, "location":"Route 13","address":0x2e4c4},
122:{"bit":4, "location":"Route 13","address":0x2e4cd},
123:{"bit":5, "location":"Route 13","address":0x2e4cd},
124:{"bit":4, "location":"Route 13","address":0x2e4d1},
125:{"bit":5, "location":"Route 13","address":0x2e4d1},
126:{"bit":6, "location":"Route 13","address":0x2e4d1},
127:{"bit":2, "location":"Route 13","address":0x2e4e6},
128:{"bit":3, "location":"Route 13","address":0x2e4e6},
129:{"bit":4, "location":"Route 13","address":0x2e4e6},
130:{"bit":5, "location":"Route 13","address":0x2e4e6},
131:{"bit":7, "location":"Route 14","address":0x2e4c5},
132:{"bit":0, "location":"Route 14","address":0x2e4c6},
133:{"bit":1, "location":"Route 14","address":0x2e4c6},
134:{"bit":7, "location":"Route 14","address":0x2e4d1},
135:{"bit":0, "location":"Route 14","address":0x2e4d2},
136:{"bit":1, "location":"Route 14","address":0x2e4d3},
137:{"bit":2, "location":"Route 14","address":0x2e4d3},
138:{"bit":3, "location":"Route 14","address":0x2e4d3},
139:{"bit":4, "location":"Route 14","address":0x2e4d3},
140:{"bit":7, "location":"Route 14","address":0x2e4e8},
141:{"bit":5, "location":"Route 15","address":0x2e4c4},
142:{"bit":6, "location":"Route 15","address":0x2e4c4},
143:{"bit":1, "location":"Route 15","address":0x2e4ce},
144:{"bit":2, "location":"Route 15","address":0x2e4ce},
145:{"bit":1, "location":"Route 15","address":0x2e4d2},
146:{"bit":2, "location":"Route 15","address":0x2e4d2},
147:{"bit":0, "location":"Route 15","address":0x2e4e8},
148:{"bit":1, "location":"Route 15","address":0x2e4e8},
150:{"bit":0, "location":"Route 15","address":0x2e4e9},
151:{"bit":7, "location":"Route 16","address":0x2e4c4},
152:{"bit":1, "location":"Route 16","address":0x2e4c5},
153:{"bit":2, "location":"Route 16","address":0x2e4c5},
154:{"bit":1, "location":"Route 16","address":0x2e4cb},
155:{"bit":2, "location":"Route 16","address":0x2e4cb},
156:{"bit":3, "location":"Route 16","address":0x2e4cb},
157:{"bit":1, "location":"Route 16","address":0x2e4e9},
158:{"bit":3, "location":"Route 17","address":0x2e4c5},
159:{"bit":4, "location":"Route 17","address":0x2e4c5},
160:{"bit":5, "location":"Route 17","address":0x2e4c5},
161:{"bit":4, "location":"Route 17","address":0x2e4cb},
162:{"bit":5, "location":"Route 17","address":0x2e4cb},
163:{"bit":6, "location":"Route 17","address":0x2e4cb},
164:{"bit":7, "location":"Route 17","address":0x2e4cb},
165:{"bit":0, "location":"Route 17","address":0x2e4cc},
166:{"bit":6, "location":"Route 17","address":0x2e4e6},
167:{"bit":6, "location":"Route 18","address":0x2e4c5},
168:{"bit":3, "location":"Route 18","address":0x2e4d2},
169:{"bit":4, "location":"Route 18","address":0x2e4d2},
170:{"bit":5, "location":"Route 18","address":0x2e4d2},
171:{"bit":3, "location":"S.S. Anne","address":0x2e4e8},
172:{"bit":3, "location":"Route 19","address":0x2e4c9},
173:{"bit":4, "location":"Route 19","address":0x2e4c9},
174:{"bit":5, "location":"Route 19","address":0x2e4c9},
175:{"bit":6, "location":"Route 19","address":0x2e4c9},
176:{"bit":7, "location":"Route 19","address":0x2e4c9},
177:{"bit":0, "location":"Route 19","address":0x2e4ca},
178:{"bit":1, "location":"Route 19","address":0x2e4ca},
179:{"bit":4, "location":"Route 19","address":0x2e4ce},
180:{"bit":5, "location":"Route 19","address":0x2e4ce},
181:{"bit":6, "location":"Route 19","address":0x2e4ce},
182:{"bit":2, "location":"Route 19","address":0x2e4e9},
183:{"bit":2, "location":"Route 20","address":0x2e4ca},
184:{"bit":3, "location":"Route 20","address":0x2e4ca},
185:{"bit":4, "location":"Route 20","address":0x2e4ca},
186:{"bit":6, "location":"Route 20","address":0x2e4cd},
187:{"bit":7, "location":"Route 20","address":0x2e4cd},
188:{"bit":0, "location":"Route 20","address":0x2e4ce},
189:{"bit":7, "location":"Route 20","address":0x2e4ce},
190:{"bit":6, "location":"Route 20","address":0x2e4d2},
191:{"bit":0, "location":"Route 20","address":0x2e4e7},
192:{"bit":1, "location":"Route 20","address":0x2e4e7},
193:{"bit":5, "location":"Route 21","address":0x2e4c8},
194:{"bit":6, "location":"Route 21","address":0x2e4c8},
195:{"bit":7, "location":"Route 21","address":0x2e4c8},
196:{"bit":0, "location":"Route 21","address":0x2e4c9},
197:{"bit":5, "location":"Route 21","address":0x2e4ca},
198:{"bit":6, "location":"Route 21","address":0x2e4ca},
199:{"bit":7, "location":"Route 21","address":0x2e4ca},
200:{"bit":0, "location":"Route 21","address":0x2e4cb},
201:{"bit":3, "location":"Route 21","address":0x2e4e9},
202:{"bit":2, "location":"Route 23","address":0x2e4af},
203:{"bit":4, "location":"Route 24","address":0x2e4b7},
204:{"bit":6, "location":"Route 24","address":0x2e4b9},
205:{"bit":2, "location":"Route 24","address":0x2e4bb},
206:{"bit":3, "location":"Route 24","address":0x2e4bb},
207:{"bit":7, "location":"Route 24","address":0x2e4bd},
208:{"bit":0, "location":"Route 24","address":0x2e4be},
209:{"bit":4, "location":"Route 24","address":0x2e4d8},
210:{"bit":5, "location":"Route 25","address":0x2e4b7},
211:{"bit":6, "location":"Route 25","address":0x2e4b7},
212:{"bit":7, "location":"Route 25","address":0x2e4b7},
213:{"bit":5, "location":"Route 25","address":0x2e4bb},
214:{"bit":1, "location":"Route 25","address":0x2e4bf},
215:{"bit":6, "location":"Route 25","address":0x2e4c2},
216:{"bit":7, "location":"Route 25","address":0x2e4c2},
217:{"bit":0, "location":"Route 25","address":0x2e4c3},
218:{"bit":7, "location":"Route 25","address":0x2e4e6},
219:{"bit":1, "location":"Route 3","address":0x2e4b7},
220:{"bit":2, "location":"Route 3","address":0x2e4b7},
221:{"bit":1, "location":"Route 3","address":0x2e4b9},
222:{"bit":2, "location":"Route 3","address":0x2e4b9},
223:{"bit":3, "location":"Route 3","address":0x2e4b9},
224:{"bit":4, "location":"Route 3","address":0x2e4ba},
225:{"bit":5, "location":"Route 3","address":0x2e4ba},
226:{"bit":6, "location":"Route 3","address":0x2e4ba},
227:{"bit":7, "location":"Route 6","address":0x2e4b9},
228:{"bit":0, "location":"Route 6","address":0x2e4ba},
229:{"bit":1, "location":"Route 6","address":0x2e4be},
230:{"bit":2, "location":"Route 6","address":0x2e4be},
231:{"bit":7, "location":"Route 6","address":0x2e4be},
232:{"bit":0, "location":"Route 6","address":0x2e4bf},
233:{"bit":0, "location":"Route 8","address":0x2e4bc},
234:{"bit":1, "location":"Route 8","address":0x2e4bc},
235:{"bit":2, "location":"Route 8","address":0x2e4bc},
236:{"bit":3, "location":"Route 8","address":0x2e4bc},
237:{"bit":3, "location":"Route 8","address":0x2e4c1},
238:{"bit":4, "location":"Route 8","address":0x2e4c1},
239:{"bit":5, "location":"Route 8","address":0x2e4c1},
240:{"bit":6, "location":"Route 8","address":0x2e4cc},
241:{"bit":0, "location":"Route 8","address":0x2e4cd},
242:{"bit":7, "location":"Route 8","address":0x2e4ee},
243:{"bit":0, "location":"Route 8","address":0x2e4ef},
244:{"bit":2, "location":"Route 9","address":0x2e4ba},
245:{"bit":3, "location":"Route 9","address":0x2e4ba},
246:{"bit":4, "location":"Route 9","address":0x2e4be},
247:{"bit":5, "location":"Route 9","address":0x2e4be},
248:{"bit":2, "location":"Route 9","address":0x2e4bf},
249:{"bit":3, "location":"Route 9","address":0x2e4bf},
250:{"bit":1, "location":"Route 9","address":0x2e4c3},
251:{"bit":2, "location":"Route 9","address":0x2e4c3},
252:{"bit":1, "location":"Route 9","address":0x2e4e6},
253:{"bit":2, "location":"S.S. Anne","address":0x2e4b2},
254:{"bit":0, "location":"S.S. Anne","address":0x2e4b8},
255:{"bit":6, "location":"S.S. Anne","address":0x2e4bb},
256:{"bit":7, "location":"S.S. Anne","address":0x2e4bb},
257:{"bit":6, "location":"S.S. Anne","address":0x2e4bc},
258:{"bit":7, "location":"S.S. Anne","address":0x2e4bc},
259:{"bit":0, "location":"S.S. Anne","address":0x2e4bd},
260:{"bit":1, "location":"S.S. Anne","address":0x2e4bd},
261:{"bit":2, "location":"S.S. Anne","address":0x2e4bd},
262:{"bit":3, "location":"S.S. Anne","address":0x2e4bd},
263:{"bit":4, "location":"S.S. Anne","address":0x2e4bd},
264:{"bit":7, "location":"S.S. Anne","address":0x2e4c7},
265:{"bit":0, "location":"S.S. Anne","address":0x2e4c8},
266:{"bit":5, "location":"S.S. Anne","address":0x2e4e0},
267:{"bit":6, "location":"S.S. Anne","address":0x2e4e0},
268:{"bit":6, "location":"Silph Co.","address":0x2e4cf},
269:{"bit":0, "location":"Silph Co.","address":0x2e4d6},
270:{"bit":1, "location":"Silph Co.","address":0x2e4d6},
271:{"bit":2, "location":"Silph Co.","address":0x2e4d6},
272:{"bit":3, "location":"Silph Co.","address":0x2e4d6},
273:{"bit":4, "location":"Silph Co.","address":0x2e4d6},
274:{"bit":5, "location":"Silph Co.","address":0x2e4d6},
275:{"bit":6, "location":"Silph Co.","address":0x2e4d6},
276:{"bit":7, "location":"Silph Co.","address":0x2e4d6},
277:{"bit":0, "location":"Silph Co.","address":0x2e4d7},
278:{"bit":1, "location":"Silph Co.","address":0x2e4d7},
279:{"bit":5, "location":"Silph Co.","address":0x2e4d7},
280:{"bit":5, "location":"Silph Co.","address":0x2e4da},
281:{"bit":6, "location":"Silph Co.","address":0x2e4da},
282:{"bit":7, "location":"Silph Co.","address":0x2e4da},
283:{"bit":0, "location":"Silph Co.","address":0x2e4db},
284:{"bit":1, "location":"Silph Co.","address":0x2e4db},
285:{"bit":2, "location":"Silph Co.","address":0x2e4db},
286:{"bit":3, "location":"Silph Co.","address":0x2e4db},
287:{"bit":4, "location":"Silph Co.","address":0x2e4db},
288:{"bit":5, "location":"Silph Co.","address":0x2e4db},
289:{"bit":6, "location":"Silph Co.","address":0x2e4db},
290:{"bit":7, "location":"Silph Co.","address":0x2e4db},
291:{"bit":0, "location":"Silph Co.","address":0x2e4dc},
292:{"bit":1, "location":"Silph Co.","address":0x2e4dc},
293:{"bit":2, "location":"Silph Co.","address":0x2e4dc},
294:{"bit":3, "location":"Silph Co.","address":0x2e4dc},
295:{"bit":4, "location":"Silph Co.","address":0x2e4dc},
296:{"bit":5, "location":"Silph Co.","address":0x2e4dc},
297:{"bit":6, "location":"Silph Co.","address":0x2e4dc},
298:{"bit":7, "location":"Silph Co.","address":0x2e4dc},
299:{"bit":2, "location":"Treasure Beach","address":0x2e4f0},
300:{"bit":7, "location":"Victory Road","address":0x2e4c0},
301:{"bit":7, "location":"Victory Road","address":0x2e4cf},
302:{"bit":2, "location":"Victory Road","address":0x2e4d0},
303:{"bit":2, "location":"Victory Road","address":0x2e4d1},
304:{"bit":5, "location":"Victory Road","address":0x2e4d4},
305:{"bit":1, "location":"Victory Road","address":0x2e4dd},
306:{"bit":2, "location":"Victory Road","address":0x2e4dd},
307:{"bit":4, "location":"Victory Road","address":0x2e4dd},
308:{"bit":3, "location":"Victory Road","address":0x2e4de},
309:{"bit":4, "location":"Victory Road","address":0x2e4de},
310:{"bit":6, "location":"Victory Road","address":0x2e4de},
311:{"bit":5, "location":"Victory Road","address":0x2e4e8},
312:{"bit":4, "location":"Viridian Forest","address":0x2e4ac},
313:{"bit":5, "location":"Viridian Forest","address":0x2e4ae},
314:{"bit":4, "location":"Viridian Forest","address":0x2e4b1},
315:{"bit":6, "location":"Viridian Forest","address":0x2e4b8},
316:{"bit":7, "location":"Viridian Forest","address":0x2e4b8},
317:{"bit":0, "location":"Viridian Forest","address":0x2e4b9},
318:{"bit":3, "location":"Viridian Forest","address":0x2e4ee},
319:{"bit":4, "location":"Viridian Forest","address":0x2e4ee},
320:{"bit":6, "location":"Pokemon Mansion","address":0x02e4e4},
321:{"bit":7, "location":"Pokemon Mansion","address":0x02e4e4},
322:{"bit":6, "location":"Route 12","address":0x02e4e8},
323:{"bit":4, "location":"Route 8","address":0x043259},
324:{"bit":7, "location":"Route 4","address":0x02e4ba},
}

function bitSum(flags){
    sum = 0
    count = 0
    for flag in flags{
        sum = sum + bit(flags[flag]["bit"], flags[flag]["address"])
        count = count + 1
    }
    return measured(sum == count)
}

//Cheats
carePackage=bit7(0x04325b)
rareCandy=bit0(0x04325c)
dexNav=bit6(0x04325e)
teamPreview=bit3(0x043264)
seviian=bit2(0x043266)
mega=bit4(0x043266)
randomSix=bit5(0x043266)
puzzle=bit6(0x043266)
EZCatch=bit5(0x043267)
Shiny=bit4(0x04326b)
Monotype=bit7(0x04326b)
function noCheats(){
    return
    //carePackage == 0&&
//rareCandy== 0&&
dexNav== 0&&
teamPreview== 0&&
seviian== 0&&
mega== 0&&
randomSix== 0&&
puzzle== 0&&
EZCatch== 0&&
//Shiny== 0&&
Monotype== 0
}

//Randomization Options
randomScaledSpecies = bit2(0x04317b)
randomNormalSpecies = bit0(0x04317c)
randomAbilities = bit2(0x04317c)
randomLearnset = bit1(0x04317c)


function noRando(){
    return 
    randomScaledSpecies == 0 &&
    randomNormalSpecies == 0 &&
    randomAbilities == 0 &&
    randomLearnset == 0 &&
    noCheats()
}

bosses = {
1:{"title":"Smell Ya Later!","description":"Defeat your rival in Pallet Town (Randomized mode is blocked for every achievement except for the randomized achievements, good luck!)", "points":2, "mapID":0x304, "trainerID":[0x146, 0x147, 0x148],"type":"Missable"},
2:{"title":"Ya Snooze Ya Lose!","description":"Defeat your rival on Route 22", "points":5, "mapID":0x2903, "trainerID":[0x149, 0x14a, 0x14b],"type":"Missable"},
3:{"title":"All the Way From the Hoenn Region...","description":"Defeat Brendan in Viridian Forest", "points":5, "mapID":0x0001, "trainerID":[0x002c],"type":"Progression"},
4:{"title":"Falkner the Falconer","description":"Defeat Falkner", "points":5, "mapID":0x0106, "trainerID":[0x002d],"type":"Progression"},
5:{"title":"Brock Solid","description":"Defeat Brock", "points":5, "mapID":0x0206, "trainerID":[0x019e],"type":"Progression"},
6:{"title":"To the Moon!","description":"Defeat Archer in Mt. Moon", "points":5, "mapID":0x0301, "trainerID":[0x002e],"type":"Progression"},
7:{"title":"He's Our Man!","description":"Defeat your rival in Cerulean City", "points":5, "mapID":0x0303, "trainerID":[0x014c, 0x014d, 0x014e],"type":"Progression"},
8:{"title":"Scyther Master Bugsy","description":"Defeat Bugsy", "points":5, "mapID":0x2c03, "trainerID":[0x002f, 0x0008],"type":""},
9:{"title":"The Misty Mermaid","description":"Defeat Misty", "points":5, "mapID":0x0507, "trainerID":[0x019f],"type":"Progression"},
10:{"title":"Rematch with Brendan","description":"Defeat Brendan in the SS. Anne", "points":5, "mapID":0x0601, "trainerID":[0x0032],"type":"Progression"},
11:{"title":"Dairy Farmer Whitney","description":"Defeat Whitney", "points":5, "mapID":0x1d03, "trainerID":[0x0031],"type":""},
12:{"title":"Hey Baby! Ready for a Match?","description":"Defeat Lt. Surge", "points":5, "mapID":0x0609, "trainerID":[0x01a0],"type":"Progression"},
13:{"title":"Erika the Scent-sational","description":"Defeat Erika", "points":5, "mapID":0x100a, "trainerID":[0x01a1],"type":"Progression"},
14:{"title":"Fighting Spirit","description":"Defeat Morty", "points":5, "mapID":0x0208, "trainerID":[0x0034],"type":""},
15:{"title":"Do Not Look Under the Poster","description":"Defeat Giovanni in Rocket Hideout", "points":5, "mapID":0x2d01, "trainerID":[0x015c],"type":"Progression"},
16:{"title":"How Good Are You?","description":"Defeat Boss Giovanni in Silph Co", "points":5, "mapID":0x3901, "trainerID":[0x015d],"type":"Progression"},
17:{"title":"Chuck This!","description":"Defeat Chuck", "points":5, "mapID":0x020e, "trainerID":[0x013d],"type":""},
18:{"title":"Mega Rivalry","description":"Defeat Brendan near the Safari Zone", "points":5, "mapID":0x0703, "trainerID":[0x0039],"type":"Progression"},
19:{"title":"Rematch with Brock","description":"Defeat Brock in a rematch", "points":5, "mapID":0x0206, "trainerID":[0x0038],"type":"Progression"},
20:{"title":"Rematch with Misty","description":"Defeat Misty in a rematch", "points":5, "mapID":0x0507, "trainerID":[0x0030],"type":"Progression"},
21:{"title":"Rematch with Surge","description":"Defeat Lt. Surge in a rematch", "points":5, "mapID":0x0609, "trainerID":[0x0033],"type":"Progression"},
22:{"title":"Rematch with Erika","description":"Defeat Erika in a rematch", "points":5, "mapID":0x100a, "trainerID":[0x0041],"type":""},
23:{"title":"Swift Battle With Koga","description":"Defeat Koga", "points":5, "mapID":0x030b, "trainerID":[0x01a2],"type":"Progression"},
24:{"title":"Double Trouble","description":"Defeat Sabrina", "points":5, "mapID":0x030e, "trainerID":[0x01a4],"type":"Progression"},
25:{"title":"Steeling Victory","description":"Defeat Jasmine", "points":5, "mapID":0x010c, "trainerID":[0x3e, 0x003f, 0x40],"type":""},
26:{"title":"Radical May","description":"Defeat May in Cinnabar Island", "points":5, "mapID":0x0803, "trainerID":[0x003d],"type":"Progression"},
27:{"title":"When You're Hot You're Hot","description":"Defeat Blaine", "points":5, "mapID":0x000c, "trainerID":[0x01a3],"type":"Progression"},
28:{"title":"The Pryce is Right","description":"Defeat Pryce", "points":5, "mapID":0x2603, "trainerID":[0x3a, 0x3b, 0x003c],"type":""},
29:{"title":"Master Plan","description":"Defeat Giovanni in Cerulean Cave", "points":5, "mapID":0x4a01, "trainerID":[0x0045],"type":"Progression"},
30:{"title":"Clairvoyance","description":"Defeat Clair", "points":5, "mapID":0x0105, "trainerID":[0x004a],"type":"Progression"},
31:{"title":"How About a Match?","description":"Defeat your rival on Route 22 before the Elite Four", "points":5, "mapID":0x2903, "trainerID":[0x1b3, 0x1b4, 0x1b5],"type":"Progression"},
32:{"title":"Dumb*ss Fight","description":"Defeat Soupercell before the Elite Four", "points":2, "mapID":0x0903, "trainerID":[0x0018],"type":"Progression"},
33:{"title":"Radical Champ","description":"Become the League Champion", "points":25, "mapID":0x4f01, "trainerID":[0x01b6, 0x01b7, 0x01b8],"type":"Win_Condition"},
36:{"title":"Poke Vial Puzzle","description":"Defeat the friendly teacher in the Trainers School", "points":5, "mapID":0x0205, "trainerID":[0x0007],"type":""},
37:{"title":"Show Me Your Moves!","description":"Defeat the Pokemon Move Maniac in Cerulean City", "points":10, "mapID":0x0807, "trainerID":[0x0006],"type":""},
38:{"title":"Thrill of Battle","description":"Defeat Gentleman Komodo in the day care", "points":10, "mapID":0x0011, "trainerID":[0x0005],"type":""},
40:{"title":"Thorn in your Side","description":"Defeat Ace Trainer Cole in Route 8", "points":10, "mapID":0x1a03, "trainerID":[0x0012],"type":""},
41:{"title":"i Herd U Liek Mudkipz","description":"Defeat Dumb*ss Mudkip Kid in Saffron City", "points":10, "mapID":0x000e, "trainerID":[0x0019],"type":""},
42:{"title":"Super Bored Gals","description":"Defeat the beauties in the Celadon City Hotel", "points":10, "mapID":0x130a, "trainerID":[0x0011],"type":""},
43:{"title":"New Powerful Strategy","description":"Defeat Ace Trainer Haley in Route 15", "points":10, "mapID":0x2103, "trainerID":[0x000f],"type":""},
44:{"title":"Training Partner","description":"Defeat Cerulean Cave Black Belt Ketchup in Cerulean Cave", "points":10, "mapID":0x4901, "trainerID":[0x0014],"type":""},
45:{"title":"Giving Your All","description":"Defeat Cerulean Cave Black Belt Ketchup in a rematch in Cerulean Cave", "points":10, "mapID":0x4901, "trainerID":[0x0013],"type":""},
46:{"title":"Are You Approaching Me?","description":"Defeat Power Plant Dumb*ss Jojo", "points":10, "mapID":0x5f01, "trainerID":[0x0042],"type":""},
47:{"title":"Oak Cheating?!","description":"Defeat Professor Oak in his lab", "points":10, "mapID":0x0304, "trainerID":[0x00d2],"type":""},
48:{"title":"No Fairies Zone","description":"Defeat Clair in a rematch", "points":10, "mapID":0x0105, "trainerID":[0x0026],"type":""},
49:{"title":"Third Time is the Charm","description":"Defeat Misty in a rematch for the 2nd time", "points":10, "mapID":0x0507, "trainerID":[0x0020],"type":""},
50:{"title":"A New Challenge","description":"Defeat Falkner in a rematch", "points":10, "mapID":0x7b01, "trainerID":[0x002b],"type":""},
51:{"title":"u seem stwonger","description":"Defeat Dumb*ss Mudkip Kid in a rematch", "points":10, "mapID":0x000e, "trainerID":[0x0023],"type":""},
52:{"title":"Adapt and Overcome","description":"Defeat Pryce in a rematch", "points":10, "mapID":0x7c01, "trainerID":[0x004f],"type":""},
53:{"title":"Expected Outcome","description":"Defeat Morty in a rematch", "points":10, "mapID":0x7e01, "trainerID":[0x001c],"type":""},
54:{"title":"Yare Yare Daze","description":"Defeat Dumb*ss fan Jojo in a rematch", "points":10, "mapID":0x0c03, "trainerID":[0x0028],"type":""},
55:{"title":"...","description":"Defeat Red in Kindle Road", "points":10, "mapID":0x2e03, "trainerID":[0x0003],"type":""},
56:{"title":"Limit Testing","description":"Defeat Bugsy on a rematch", "points":10, "mapID":0x2d03, "trainerID":[0x004b],"type":""},
57:{"title":"Power Creep","description":"Defeat Whitney on a rematch", "points":10, "mapID":0x0121, "trainerID":[0x004c],"type":""},
58:{"title":"Starter Fan","description":"Defeat Joyful Game Corner Ace Trainer Andrew", "points":10, "mapID":0x0021, "trainerID":[0x0002],"type":""},
59:{"title":"Dark Hole","description":"Defeat Cape Brink Channeler Racher", "points":10, "mapID":0x0028, "trainerID":[0x0093],"type":""},
}

hardcore = {
61:{"title":"Hardcore Zephyr","description":"Defeat Falkner on hardcore mode", "points":10, "mapID":0x0106, "trainerID":[0x002d]},
62:{"title":"Hardcore Boulder","description":"Defeat Brock on hardcore mode", "points":10, "mapID":0x0206, "trainerID":[0x019e]},
63:{"title":"Hardcore Hive","description":"Defeat Bugsy on hardcore mode", "points":10, "mapID":0x2c03, "trainerID":[0x002f, 0x0008]},
64:{"title":"Hardcore Cascade","description":"Defeat Misty on hardcore mode", "points":10, "mapID":0x0507, "trainerID":[0x019f]},
65:{"title":"Plain Hardcore","description":"Defeat Whitney on hardcore mode", "points":10, "mapID":0x1d03, "trainerID":[0x0031]},
66:{"title":"Hardcore Thunder","description":"Defeat Lt. Surge on hardcore mode", "points":10, "mapID":0x0609, "trainerID":[0x01a0]},
67:{"title":"Hardcore Rainbow","description":"Defeat Erika on hardcore mode", "points":10, "mapID":0x100a, "trainerID":[0x01a1]},
68:{"title":"Hardcore Fog","description":"Defeat Morty on hardcore mode", "points":10, "mapID":0x0208, "trainerID":[0x0034]},
69:{"title":"Hardcore Storm","description":"Defeat Chuck on hardcore mode", "points":10, "mapID":0x020e, "trainerID":[0x013d]},
70:{"title":"Hardcore Soul","description":"Defeat Koga on hardcore mode", "points":10, "mapID":0x030b, "trainerID":[0x01a2]},
71:{"title":"Hardcore Marsh","description":"Defeat Sabrina on hardcore mode", "points":10, "mapID":0x030e, "trainerID":[0x01a4]},
72:{"title":"Hardcore Mineral","description":"Defeat Jasmine on hardcore mode", "points":10, "mapID":0x010c, "trainerID":[0x3e, 0x003f, 0x40]},
73:{"title":"Hardcore Volcano","description":"Defeat Blaine on hardcore mode", "points":10, "mapID":0x000c, "trainerID":[0x01a3]},
74:{"title":"Hardcore Glacier","description":"Defeat Pryce on hardcore mode", "points":10, "mapID":0x2603, "trainerID":[0x003a, 0x003b, 0x003c]},
75:{"title":"Hardcore Rising","description":"Defeat Clair on hardcore mode", "points":10, "mapID":0x0105, "trainerID":[0x004a]},
76:{"title":"Hardcore Radical Champ","description":"Become the League Champion on hardcore mode", "points":50, "mapID":0x4f01, "trainerID":[0x01b6, 0x01b7, 0x01b8]},
}

random=
{
77:{"title":"Random Zephyr","description":"Defeat Falkner on default or harder mode and randomized species mode", "points":10, "mapID":0x0106, "trainerID":[0x002d]},
78:{"title":"Random Boulder","description":"Defeat Brock on default or harder mode and randomized species mode", "points":10, "mapID":0x0206, "trainerID":[0x019e]},
79:{"title":"Random Hive","description":"Defeat Bugsy on default or harder mode and randomized species mode", "points":10, "mapID":0x2c03, "trainerID":[0x002f, 0x0008]},
80:{"title":"Random Cascade","description":"Defeat Misty on default or harder mode and randomized species mode", "points":10, "mapID":0x0507, "trainerID":[0x019f]},
81:{"title":"Plain Random","description":"Defeat Whitney on default or harder mode and randomized species mode", "points":10, "mapID":0x1d03, "trainerID":[0x0031]},
82:{"title":"Random Thunder","description":"Defeat Lt. Surge on default or harder mode and randomized species mode", "points":10, "mapID":0x0609, "trainerID":[0x01a0]},
83:{"title":"Random Rainbow","description":"Defeat Erika on default or harder mode and randomized species mode", "points":10, "mapID":0x100a, "trainerID":[0x01a1]},
84:{"title":"Random Fog","description":"Defeat Morty on default or harder mode and randomized species mode", "points":10, "mapID":0x0208, "trainerID":[0x0034]},
85:{"title":"Random Storm","description":"Defeat Chuck on default or harder mode and randomized species mode", "points":10, "mapID":0x020e, "trainerID":[0x013d]},
86:{"title":"Random Soul","description":"Defeat Koga on default or harder mode and randomized species mode", "points":10, "mapID":0x030b, "trainerID":[0x01a2]},
87:{"title":"Random Marsh","description":"Defeat Sabrina on default or harder mode and randomized species mode", "points":10, "mapID":0x030e, "trainerID":[0x01a4]},
88:{"title":"Random Mineral","description":"Defeat Jasmine on default or harder mode and randomized species mode", "points":10, "mapID":0x010c, "trainerID":[0x3e, 0x003f, 0x40]},
89:{"title":"Random Volcano","description":"Defeat Blaine on default or harder mode and randomized species mode", "points":10, "mapID":0x000c, "trainerID":[0x01a3]},
90:{"title":"Random Glacier","description":"Defeat Pryce on default or harder mode and randomized species mode", "points":10, "mapID":0x2603, "trainerID":[0x003a, 0x003b, 0x003c]},
91:{"title":"Random Rising","description":"Defeat Clair on default or harder mode and randomized species mode", "points":25, "mapID":0x0105, "trainerID":[0x004a]},
92:{"title":"Random Radical Champ","description":"Become League Champ on default or harder mode and randomized species mode", "points":25, "mapID":0x4f01, "trainerID":[0x01b6, 0x01b7, 0x01b8]},
}

collectables={
93:{"title":"City Completion","description":"Obtain all overworld items in the cities of Kanto", "points":5, "maps":["Viridian City", "Pewter City", "Cerulean City", "Vermilion City", "Celadon City", "Fuchsia City"], "type":""},
94:{"title":"Forest Completion","description":"Obtain all overworld items and defeat all trainers in Viridian Forest", "points":5, "maps":["Viridian Forest"], "type":""},
95:{"title":"Moon Completion","description":"Obtain all overworld items and defeat all trainers in Mt. Moon", "points":5, "maps":["Mt. Moon"], "type":""},
96:{"title":"Route Completion I","description":"Obtain all overworld items and defeat all trainers in Route 3 and Route 4", "points":5, "maps":["Route 3", "Route 4"], "type":""},
97:{"title":"Route Completion II","description":"Obtain all overworld items and defeat all trainers in Route 24 and Route 25", "points":5, "maps":["Route 24", "Route 25"], "type":""},
98:{"title":"Route Completion III","description":"Obtain all overworld items and defeat all trainers in Route 5, Route 6 and Route 11", "points":5, "maps":["Route 5", "Route 6", "Route 11"], "type":""},
99:{"title":"Cruise Completion","description":"Obtain all overworld items and defeat all trainers in S.S. Anne", "points":5, "maps":["S.S. Anne"], "type":"Missable"},
100:{"title":"Route Completion IV","description":"Obtain all overworld items and defeat all trainers in Route 2, Route 9, Route 10 and Diglett's Cave", "points":5, "maps":["Route 2", "Route 9", "Route 10", "Diglett's Cave"], "type":""},
101:{"title":"Tunnel Completion","description":"Obtain all overworld items and defeat all trainers in Rock Tunnel", "points":5, "maps":["Rock Tunnel"], "type":""},
102:{"title":"Route Completion V","description":"Obtain all overworld items and defeat all trainers in Route 7 and Route 8", "points":5, "maps":["Route 7", "Route 8"], "type":""},
103:{"title":"Hideout Completion","description":"Obtain all overworld items and defeat all trainers in Rocket Hideout", "points":5, "maps":["Rocket Hideout"], "type":""},
104:{"title":"Tower Completion","description":"Obtain all overworld items and defeat all trainers in Pokemon Tower", "points":5, "maps":["Pokemon Tower"], "type":""},
105:{"title":"Company Completion","description":"Obtain all overworld items and defeat all trainers in Silph Co.", "points":5, "maps":["Silph Co."], "type":"Missable"},
106:{"title":"Route Completion VI","description":"Obtain all overworld items and defeat all trainers in Route 12, Route 13, Route 14 and Route 15", "points":5, "maps":["Route 12", "Route 13", "Route 14", "Route 15"], "type":""},
107:{"title":"Route Completion VII","description":"Obtain all overworld items and defeat all trainers in Route 16, Route 17 and Route 18", "points":5, "maps":["Route 16", "Route 17", "Route 18"], "type":""},
108:{"title":"Safari Completion","description":"Obtain all overworld items in the Safari Zone", "points":5, "maps":["Safari Zone"], "type":""},
109:{"title":"Seafoam Completion","description":"Obtain all overworld items in Seafoam Islands", "points":5, "maps":["Seafoam Islands"], "type":""},
110:{"title":"Mansion Completion","description":"Obtain all overworld items and defeat all trainers in Pokemon Mansion", "points":5, "maps":["Pokemon Mansion"], "type":""},
111:{"title":"Route Completion VIII","description":"Obtain all overworld items and defeat all trainers in Route 19, Route 20, Route 21 and Route 22", "points":5, "maps":["Route 19", "Route 20", "Route 21", "Route 22"], "type":""},
112:{"title":"Cerulean Completion","description":"Obtain all overworld items and defeat all trainers in Cerulean Cave", "points":5, "maps":["Cerulean Cave"], "type":"Missable"},
113:{"title":"Power Completion","description":"Obtain all overworld items and defeat all trainers in Power Plant", "points":5, "maps":["Power Plant"], "type":""},
114:{"title":"Route Completion IX","description":"Obtain all overworld items and defeat all trainers in Route 23", "points":5, "maps":["Route 23"], "type":""},
115:{"title":"Victory Completion","description":"Obtain all overworld items and defeat all trainers in Victory Road", "points":5, "maps":["Victory Road"], "type":""},
116:{"title":"Island Completion I","description":"Obtain all overworld items and defeat all trainers in One Island", "points":5, "maps":["Kindle Road", "Mt. Ember"], "type":"Missable"},
117:{"title":"Island Completion II","description":"Obtain all overworld items in Two Island", "points":5, "maps":["Two Island", "Cape Brink"], "type":""},
118:{"title":"Island Completion III","description":"Obtain all overworld items and defeat all trainers in Three Island", "points":5, "maps":["Three Isle Path", "Three Island", "Bond Bridge", "Berry Forest"], "type":""},
}

function collectables(maps){
    sum = 0
    count = 0
    for item in items{
        for map in maps{
            if(map == items[item]["location"]){
                sum = sum + bit(items[item]["bit"], items[item]["address"])
                count = count+1
            }
        }
    }
    
     for item in trainers{
        for map in maps{
            if(map == trainers[item]["location"]){
                sum = sum + bit(trainers[item]["bit"], trainers[item]["address"])
                count = count+1
            }
        }
    }
    
    
    
    return measured(sum == count, when= mapID != 0 && prev(mapID) != 0  && mapID2 != 0 && prev(mapID2) != 0 && noRando() && noCheats()) && ((prev(sum) == count - 1) || prev(sum) == count - 2)
}
mapID = word(0x02d530)
mapID2= word(0x03ee10)

for cheevo in collectables{
    achievement(
        collectables[cheevo]["title"],
        collectables[cheevo]["description"],
        collectables[cheevo]["points"],
        collectables(collectables[cheevo]["maps"]),
        type = collectables[cheevo]["type"]
        )
}

battleOutcome = word(0x02be8a)
inBattle = 0
win = 1

trainerBattle = bit3(0x02ab4c) == 1 && prev(bit3(0x02ab4c)) == 1
trainerID = word(0x0406ae)

function trainerWin(trainerIDs, map){
    logic = noCheats()
    logic = logic && noRando()
    logic = logic && battleOutcome == win && prev(battleOutcome) == inBattle
    logic = logic && mapID == map && prev(mapID) == map && trainerBattle
    
    logicIDs=always_false()
    for ID in trainerIDs{
        logicIDs = logicIDs || trainerID == ID
    }
    
    logic = logic && logicIDs
    return logic
}

function trainerWinRando(trainerIDs, map){
    logic = noCheats()
    logic = logic && (randomScaledSpecies == 1 || randomNormalSpecies == 1)
    logic = logic && battleOutcome == win && prev(battleOutcome) == inBattle
    logic = logic && mapID == map && prev(mapID) == map
    
    logicIDs=always_false()
    for ID in trainerIDs{
        logicIDs = logicIDs || trainerID == ID
    }
    
    logic = logic && logicIDs
    return logic
}


hardcoreMode = bit4(0x04325a)
for boss in bosses{
    achievement(
        title = bosses[boss]["title"],
        description = bosses[boss]["description"],
        points = bosses[boss]["points"],
        trigger = trainerWin(bosses[boss]["trainerID"], bosses[boss]["mapID"]),
        type = bosses[boss]["type"]
    )
}

for boss in hardcore{
    achievement(
        title = hardcore[boss]["title"],
        description = hardcore[boss]["description"],
        points = hardcore[boss]["points"],
        trigger = trainerWin(hardcore[boss]["trainerID"], hardcore[boss]["mapID"]) && hardcoreMode == 1
    )
}

for boss in random{
    achievement(
        title = random[boss]["title"],
        description = random[boss]["description"],
        points = random[boss]["points"],
        trigger = trainerWinRando(random[boss]["trainerID"], random[boss]["mapID"])
    )
}

//achievement(
 //   "all items",
 //   "just for rp",
 //   0,
 //   bitSum(items)
    
//)

//achievement(
//    "all trainers",
//    "just for rp",
//    0,
//    bitSum(trainers)
//)

StartPokedex=0x02d8e0
function PokemonBit(pokemonID){
    logic = always_true()
    StartTemp = StartPokedex
    PokemonAddress = 0
    Count = 0 
    AddOne = 0
    for number in range(0, pokemonID-1){            
        if(number == pokemonID-1){
            if((Count) == 0){
                PokemonAddress =  bit0(StartTemp)
            }
            if((Count) == 1){
                PokemonAddress =  bit1(StartTemp)
            }
            if((Count) == 2){
                PokemonAddress =  bit2(StartTemp)
            }
            if((Count) == 3){
               PokemonAddress =  bit3(StartTemp)
            }
            if((Count) == 4){
               PokemonAddress =  bit4(StartTemp)
            }
            if((Count) == 5){
               PokemonAddress =  bit5(StartTemp)
            }
            if((Count) == 6){
               PokemonAddress =  bit6(StartTemp)
            }
            if((Count) == 7){
               PokemonAddress =  bit7(StartTemp)
            }
         }
         Count = Count + 1
         if(Count == 8){
            Count = 0
            StartTemp = StartTemp + 0x01
         }

    }
    return 
    PokemonAddress 
}
// && (number != 493 && number != 890)
function CatchedPokemon(startOffset, start, finish){
    logic = always_true()
    StartTemp = startOffset
    PokemonAddress = 0
    Count = 0 
    count = 0
    AddBitFlags = 1
    BitFlags = []
    for number in range(1, 1025){            
        if(number >= start && number < finish  ){
            if(finish - number > 8 && Count == 0){
                array_push(BitFlags, bitcount(StartTemp))
                AddBitFlags = 0
            }else if(AddBitFlags == 1 ){
                      
                if((Count) == 0){
                    array_push(BitFlags, bit0(StartTemp))
                }
                if((Count) == 1){
                    array_push(BitFlags, bit1(StartTemp))
                }
                if((Count) == 2){
                   array_push(BitFlags, bit2(StartTemp))
                }
                if((Count) == 3){
                  array_push(BitFlags, bit3(StartTemp))
                }
                if((Count) == 4){
                   array_push(BitFlags, bit4(StartTemp))
                }
                if((Count) == 5){
                   array_push(BitFlags, bit5(StartTemp))
                }
                if((Count) == 6){
                   array_push(BitFlags, bit6(StartTemp))
                }
                if((Count) == 7){
                   array_push(BitFlags, bit7(StartTemp))
                }
                
            }
         }
         Count = Count + 1
         if(Count == 8){
            Count = 0
            StartTemp = StartTemp + 0x01
            AddBitFlags = 1
         }
         count = count + 1
    }
    return 
    measured(sum_of(BitFlags, f => f) == finish-start) && sum_of(BitFlags, f => prev(f)) == finish-start-1 
}



achievement(
    "test all poke",
    "chien pao",
    0,
    trigger= CatchedPokemon(StartPokedex, 1,1026)
)

achievement(
    "arceus",
    "chien pao",
    0,
    trigger= PokemonBit(493) == 1
)

achievement(
    "eternatus",
    "chien pao",
    0,
    trigger= PokemonBit(890) == 1
)



specificPokemon = {
    119:{"title":"Legendary Birds","description":"Catch Articuno, Zapdos and Moltres", "points":5, "pokemon":[144, 145, 146]},
120:{"title":"Ancient Genes","description":"Catch Mewtwo and Mew", "points":5, "pokemon":[150, 151]},
121:{"title":"Legendary Beasts","description":"Catch Raikou, Entei, and Suicune", "points":5, "pokemon":[243, 244, 245]},
122:{"title":"Astral Radiance","description":"Catch Celebi, Necrozma and Calyrex", "points":5, "pokemon":[251, 800, 898]},
123:{"title":"Legendary Giants","description":"Catch Regirock, Regice, Registeel and Regigigas", "points":5, "pokemon":[377, 378, 379, 486]},
124:{"title":"Eon Trio","description":"Catch Latias, Latios and Kyogre", "points":5, "pokemon":[380, 381, 382]},
125:{"title":"Victory Gang","description":"Catch Jirachi, Meloetta, Genesect and Zygarde", "points":5, "pokemon":[385, 648, 649, 718]},
126:{"title":"Lake Guardians","description":"Catch Uxie, Mesprit and Azelf", "points":5, "pokemon":[480, 481, 482]},
127:{"title":"Hopes and Dreams","description":"Catch Cresselia, Victini and Volcanion", "points":5, "pokemon":[488, 494, 721]},
128:{"title":"Cold Seafoam","description":"Catch Manaphy, Kyurem, Keldeo, Tapu Fini and Glastrier", "points":5, "pokemon":[490, 646, 647, 788, 896]},
129:{"title":"Grassy Viridians","description":"Catch Shaymin, Virizion, Tapu Bulu and Zarude", "points":5, "pokemon":[492, 640, 787, 893]},
130:{"title":"Rocky Encounters","description":"Catch Terrakion, Magearna, Iron Leaves, Iron Boulder and Iron Crown", "points":5, "pokemon":[639, 801, 1010, 1022, 1023]},
131:{"title":"Forces of Nature","description":"Catch Tornadus, Thundurus and Landorus", "points":5, "pokemon":[641, 642, 645]},
132:{"title":"Mochi Jewels","description":"Catch Diancie and Pecharunt", "points":5, "pokemon":[719, 1025]},
133:{"title":"Mansion of Spooks","description":"Catch Hoopa, Tapu Lele, Regidrago and Spectrier", "points":5, "pokemon":[720, 786, 895, 897]},
134:{"title":"Electric Generators","description":"Catch Tapu Koko, Zeraora and Regieleki", "points":5, "pokemon":[785, 807, 894]},
135:{"title":"Sun and Moon","description":"Catch Cosmog, Cosmoem, Solgaleo and Lunala", "points":5, "pokemon":[789, 790, 791, 792]},
136:{"title":"Extradimensional Beings","description":"Catch Nihilego, Buzzwole, Pheromosa, Xurkitree, Celesteela, Kartana, Guzzlord, Poipole, Stakataka and Blacephalon", "points":5, "pokemon":[793, 794, 795, 796, 797, 798, 799, 803, 805, 806]},
137:{"title":"Reinforcements of Nature","description":"Catch Heatran, Marshadow and Enamorus", "points":5, "pokemon":[485, 802, 905]},
138:{"title":"Paradox Dogs","description":"Catch Walking Wake, Gouging Fire and Raging Bolt", "points":5, "pokemon":[1009, 1020, 1021]},
139:{"title":"Treasures of Ruin","description":"Catch Ting-Lu, Chien-Pao, Wo-Chien, Chi-Yu and Terapagos", "points":5, "pokemon":[1003, 1004, 1002, 1001, 1024]},
140:{"title":"Monthly Gift","description":"Obtain all the mystery gift Pokemon", "points":5, "pokemon":[250, 249, 384, 491, 716, 889, 643, 484, 888, 386, 1007, 644, 487, 717, 483, 1008, 383]},
141:{"title":"Starter Pack","description":"Obtain all the Pokemon that come from shard trading in Celadon City", "points":5, "pokemon":[1, 152, 252, 387, 495, 650, 722, 810, 906, 4, 155, 255, 390, 498, 653, 725, 813, 909, 7, 158, 258, 393, 501, 656, 728, 816, 912]},
142:{"title":"Pseudo-Gambling","description":"Obtain all the Celadon City Game Corner buyable Pokemon", "points":5, "pokemon":[147, 246, 374, 371, 447, 479, 443, 636, 633, 704, 782, 848, 885, 679, 996]},
}

function calculatePokemonSum(list){
    sum = 0
    count = 0
    for pokemon in list{
        sum = sum + PokemonBit(pokemon)
        count = count + 1
    }
    return measured(sum == count, when=mapID != 0 && prev(mapID) != 0  && mapID2 != 0 && prev(mapID2) != 0 && noRando()) && prev(sum) == count -1
}

for group in specificPokemon{
    achievement(
        specificPokemon[group]["title"],
        specificPokemon[group]["description"],
        specificPokemon[group]["points"],
        calculatePokemonSum(specificPokemon[group]["pokemon"]) 
    )
}
Pokedex = {
    1: {"title": "Origins Unearthed", "points": 10, "description": "Catch every available Pokemon from Kanto", "start": 1, "end": 152},
    2: {"title": "Shrine Seeker", "points": 10, "description": "Catch every available Pokemon from Johto", "start": 152, "end": 252},
    3: {"title": "Power Keepers", "points": 10, "description": "Catch every available Pokemon from Hoenn", "start": 252, "end": 387},
    4: {"title": "Secret Wonders", "points": 10, "description": "Catch every available Pokemon from Sinnoh", "start": 387, "end": 494},
    5: {"title": "Boundaries Crossed", "points": 10, "description": "Catch every available Pokemon from Unova", "start": 494, "end": 650},
    6: {"title": "Fates Collide", "points": 10, "description": "Catch every available Pokemon from Kalos", "start": 650, "end": 722},
    7: {"title": "Unbroken Bonds", "points": 10, "description": "Catch every available Pokemon from Alola", "start": 722, "end": 810},
    8: {"title": "Crown Zenith", "points": 10, "description": "Catch every available Pokemon from Galar", "start": 810, "end": 906},
    9: {"title": "Temporal Forces", "points": 10, "description": "Catch every available Pokemon from Paldea", "start": 906, "end": 1026},
    10: {"title": "Gotta Catch em' All - Radical Red", "points": 50, "description": "Catch all 1023 available Pokemon", "start": 1, "end": 1026},
}

for pokedex in Pokedex{
    achievement(
        title = Pokedex[pokedex]["title"],
        description = Pokedex[pokedex]["description"],
        points = Pokedex[pokedex]["points"],
        trigger = CatchedPokemon(StartPokedex, Pokedex[pokedex]["start"], Pokedex[pokedex]["end"]) && mapID != 0 && prev(mapID) != 0  && mapID2 != 0 && prev(mapID2) != 0 && noRando()
        
    )
}

function addBits(list){
    count = 0
    sum = 0
    for item in list{
        count = count + 1
        sum = sum + item
        
    }
    return measured(sum  == count, when=mapID != 0 && prev(mapID) != 0  && mapID2 != 0 && prev(mapID2) != 0 && noRando() && noCheats()) && prev(sum) == (count -1)
}

showingPokemon = [bit1(0x04317e),
bit4(0x043180),
bit6(0x043181),
bit7(0x043181),
bit0(0x04317f)]

achievement(
    "Show Off",
    "Obtain all the gifts from showing powerful Pokemon to gym leaders",
    5,
    addBits(showingPokemon)
)

ZCrystals = [
    bit1(0x043257)	,
bit7(0x02e449)	,
bit7(0x043256)	,
bit0(0x043257)	,
bit4(0x02e4af)	,
bit2(0x02e468)	,
bit3(0x04325e)	,
bit0(0x043258)	,
bit3(0x02e460)	,
bit4(0x02e46b)	,
bit5(0x043185)	,
bit5(0x043263)	,
bit4(0x043261)	,
bit4(0x04325f)	
]

TMs = [
    bit3(0x043255)	,
bit2(0x02e441)	,
bit1(0x02e510)	,
bit4(0x043183)	,
bit1(0x02e438)	,
bit2(0x02e440)	,
bit6(0x02e43e)	,
bit2(0x02e437)	,
bit1(0x043185)	,
bit0(0x02e4af)	,
bit0(0x02e43a)	,
bit4(0x02e440)	,
bit4(0x043182)	,
bit0(0x02e43c)	,
bit3(0x02e510)	,
bit7(0x02e440)	,
bit4(0x02e444)	,
bit4(0x02e43f)	,
bit5(0x043185)	,
bit3(0x02e457)	,
bit3(0x02e4d8)	,
bit5(0x02e454)	,
bit3(0x043254)	,
bit0(0x043254)	,
bit0(0x02e43d)	,
bit2(0x04317f)	,
bit5(0x02e510)	,
bit6(0x02e441)	,
bit6(0x02e510)	,
bit0(0x02e510)	,
bit0(0x03046d)	,
bit6(0x02e44b)	,
bit4(0x04317f)	,
bit3(0x02e438)	,
bit7(0x043254)	,
bit2(0x02e438)	,
bit0(0x02e438)	,
bit6(0x02e43b)	,
bit4(0x02e43a)	,
bit0(0x02e442)	,
bit5(0x02e4b1)	,
bit5(0x04317d)	,
bit4(0x043255)	,
bit5(0x043255)	,
bit6(0x04317a)	,
bit6(0x043255)	,
bit7(0x02e43c)	,
bit0(0x04317e)	,
bit7(0x043255)	,
bit7(0x04317f)	,
bit2(0x02e443)	,
bit5(0x043256)	,
bit0(0x0433f6)	,
bit7(0x043187)	,
bit6(0x02e446)	,
bit1(0x04317f)	,
bit4(0x043263)	,
bit1(0x02e464)	,
bit2(0x02e440)	,
bit7(0x04317a)	,
bit5(0x04325a)	,
bit6(0x043254)	,
bit1(0x04317b)	,
bit1(0x043180)	,
bit0(0x04317d)	,
bit1(0x04317a)	,
bit0(0x02e465)	,
bit2(0x02e510)	,
bit6(0x02e449)	,
bit4(0x02e449)	,
bit0(0x043180)	,
bit2(0x04325e)	,
bit1(0x043254)	,
bit0(0x043185)	,
bit6(0x043256)	,
bit3(0x02e439)	,
bit3(0x043257)	,
bit3(0x02e43a)	,
bit1(0x04325a)	,
bit3(0x02e43f)	,
bit3(0x02e464)	,
bit2(0x043255)	,
bit1(0x02e43e)	,
bit4(0x02e510)	,
bit6(0x043259)	,
bit7(0x02e510)	,
bit0(0x043182)	
]

HMs = [bit7(0x02e452)	,
bit4(0x03046e)	,
bit1(0x02e453)	,
bit2(0x02e453)	,
bit5(0x04317a)	,
bit1(0x02e4b3)	,
bit7(0x02e469)	]

MegaStones = [
    bit6(0x043180)	,
bit0(0x043181)	,
bit5(0x02e4b3)	,
bit2(0x043181)	,
bit7(0x02e43a)	,
bit4(0x02e43e)	,
bit0(0x04317f)	,
bit6(0x04317d)	,
bit1(0x043255)	,
bit4(0x043180)	,
bit2(0x02e43d)	,
bit3(0x02e446)	,
bit7(0x02e446)	,
bit1(0x043256)	,
bit3(0x04317d)	,
bit6(0x043181)	,
bit7(0x043181)	,
bit4(0x02e4b4)	,
bit5(0x02e4b4)	,
bit5(0x02e43f)	,
bit3(0x04317b)	,
bit5(0x02e4b4)	,
bit4(0x04317b)	,
bit0(0x043255)	,
bit4(0x02e441)	,
bit2(0x04317a)	,
bit1(0x04317e)	,
bit4(0x043259)	,
bit6(0x043259)	,
bit5(0x02e440)	,
bit7(0x04325f)	,
bit7(0x043180)	,
bit2(0x02e4af)	,
bit2(0x043183)	,
bit3(0x043185)	,
bit5(0x02e43e)	,
bit6(0x02e43d)	,
bit2(0x043185)	,
bit3(0x04317f)	,
bit4(0x043185)	,
bit3(0x02e43c)	,
bit6(0x02e43c)	,
bit4(0x043181)	,
bit5(0x02e446)	,
bit5(0x043181)	,
bit2(0x043180)	,
bit7(0x02e43f)	,
bit4(0x02e442)	,
bit3(0x02e4b4)	,
bit4(0x043186)	,
bit2(0x02e4b4)	,
bit5(0x043180)	,
bit4(0x043187)	,
bit3(0x043186)	,
bit7(0x02e442)	,
bit1(0x04317f)	,
bit4(0x04317a)	,
bit4(0x043254)	,
bit7(0x043259)	,
bit5(0x043259)	,
bit2(0x043182)	
]

Trades=
[bit2(0x02e455),
bit3(0x02e455),
bit5(0x02e455),
bit4(0x02e45a),
bit0(0x02e455),
bit5(0x02e45a),
bit7(0x02e456),
bit1(0x02e456),
bit6(0x02e45a)
]

achievement(
    "HM Master",
    "Collect all of the HMs",
    10,
    addBits(HMs)
)

achievement(
    "TM Master",
    "Collect all of the non-buyable TMs",
    25,
    addBits(TMs),
    type ="Missable"
)

achievement(
    "Mega Master",
    "Collect all of the Mega Stones",
    25,
    addBits(MegaStones)
)

achievement(
    "Z-Crystal Master",
    "Collect all of the non-buyable Z-Crystals (Except for Mewium Z)",
    25,
    addBits(ZCrystals)
)

achievement(
    "Aren't They Cute?",
    "Complete all 9 in-game trades",
    10,
    addBits(Trades)
)